"""Checkpoint 2 · boards 05 (the important alternatives), 06 (connected route), 07 (decisions and return to the app). Fixture; PROPOSED."""
import os, sys
from gen_c2 import *
from gen_c3 import linkframe, guestbar, pill, person_row, contribution, WEEK_SAT
from gen_c4 import sam_choice
from gen_c6 import pasta_opened
from gen_c2 import HP
sys.path.insert(0, HP)
from gen_generous import arow
from gen_generous3 import u2
from gen_artifact import ways_seq_card
from gen_p2_common import header, question_line, place_unit, ending as pl_ending, PLACE_NAMES, PACKET
from gen_p2_04 import maya_print_room, by
from kit import anchor_row, orientation, row
from gen_se import thumb, tbl, blk, two

LINE_D7 = 'The side room was my favorite. Go on a weekday, it was empty.'
LINE_D7B = 'If you go before dinner, the side room empties after four and the shop shuts at five.'
def frame(inner, tag_text=''):
    """A compact comparison frame: 393 wide, paper, no tab bar."""
    return f'<div style="width: 393px; background: {PAPER}; {SANS} color: {INK}; box-sizing: border-box; padding-bottom: 22px; border: 1px solid rgba(27,23,20,0.06);">{inner}</div>'
def pair_cap(d, t, a_label, b_label, rec):
    return (f'<div style="display: flex; flex-direction: column; gap: 6px; margin-bottom: 14px;"><div class="kick" style="color: {GOLDD};">{d}</div><div style="{SERIF} font-weight: 600; font-size: 22px; line-height: 28px;">{t}</div>'
            f'<div style="font-size: 13px; line-height: 19px; color: {INK2}; max-width: 840px;"><b>Recommendation:</b> {rec}</div></div>')
def side(label, fr, note):
    return f'<div style="width: 393px; flex: none; display: flex; flex-direction: column; gap: 8px;"><div class="kickm">{label}</div>{fr}<div class="fn" style="color: {ANCHOR}; line-height: 15px;">{note}</div></div>'
def pair(d, t, rec, a, b):
    return f'<div style="display: flex; flex-direction: column;">{pair_cap(d, t, "", "", rec)}<div style="display: flex; gap: 26px;">{a}{b}</div></div>'

# ───────────────────────────── D1 · openness ─────────────────────────────
def d1a():
    inner = f'<div style="padding: 24px 22px 0 22px;"><div class="kick" style="color: {GOLDD};">NATURAL LANGUAGE &middot; AUDIENCE ONLY</div></div>'
    inner += gut(f'<div style="border-radius: 12px; overflow: hidden;">{standin(150, "THE PASTA &middot; STAND-IN")}</div><div style="{SERIF} font-size: 18px; line-height: 25px; color: {INK}; margin-top: 10px;">Second try. Thinking of Saturday, if anyone&rsquo;s around.</div>' + meta('TO FRIENDS &middot; NO GUEST COUNT EXISTS', 8), top=14)
    inner += sect('What a friend sees') + gut(contribution('N', 'Nora', 'THURSDAY', 'Second try. Thinking of Saturday, if anyone&rsquo;s around.', scope='A LINE, NOT AN INVITATION &middot; REPLY IF YOU LIKE') + door('Reply to Nora'))
    inner += gut(src('Participation begins only when Nora sends the dinner (03.1) or a guest answers. &ldquo;Looks fun&rdquo; produces nothing.'), top=16)
    return frame(inner)
def d1b():
    inner = f'<div style="padding: 24px 22px 0 22px;"><div class="kick" style="color: {GOLDD};">ONE OPENNESS AFFORDANCE &middot; AUTHOR-CONTROLLED</div></div>'
    inner += gut(f'<div style="border-radius: 12px; overflow: hidden;">{standin(150, "THE PASTA &middot; STAND-IN")}</div><div style="{SERIF} font-size: 18px; line-height: 25px; color: {INK}; margin-top: 10px;">Second try.</div>'
                 + f'<div style="display: flex; align-items: center; gap: 10px; margin-top: 12px; padding: 10px 12px; border: 1px solid rgba(27,23,20,0.12); border-radius: 12px;"><span style="width: 34px; height: 20px; border-radius: 10px; background: {INK}; position: relative; flex: none;"><span style="position: absolute; right: 2px; top: 2px; width: 16px; height: 16px; border-radius: 8px; background: {CARD};"></span></span><span style="font-size: 14px; color: {INK};">Happy for company Saturday</span></div>' + meta('TO FRIENDS &middot; THE TOGGLE IS THE ONLY NEW STATE', 8), top=14)
    inner += sect('What a friend sees') + gut(contribution('N', 'Nora', 'THURSDAY', 'Second try.', scope='HAPPY FOR COMPANY SATURDAY &middot; SAY SO IF YOU&rsquo;D COME') + f'<div style="display: flex; gap: 18px;">{door("I&rsquo;d come")}{door("Reply to Nora")}</div>')
    inner += gut(src('&ldquo;I&rsquo;d come&rdquo; is a request; Nora still decides and sends. The cost: a second state to explain, and a request that can be ignored in silence.'), top=16)
    return frame(inner)

# ───────────────────────────── D2 · acknowledgment ─────────────────────────────
def maya_return_min(ack=False):
    inner = header('Yours', 'Thursday &middot; to friends &middot; through Sunday', back=True)
    inner += gut(f'<div style="{SERIF} font-size: 20px; line-height: 27px; color: {INK};">{by("Maya", "print_room")[2]}</div>', top=14)
    if ack:
        inner += sect('From friends') + gut('<div>' + arow('Nora &middot; <span style="color: #6E6862;">lovely</span>', avatars=['N']) + arow('Nora &middot; That side room. I want to see it before Sunday.', avatars=['N'], last=True) + '</div>' + meta('ONE WORD, HERS TO CHOOSE, SEEN ONLY BY MAYA &middot; NO COUNT', 8))
    else:
        inner += sect('A reply') + gut('<div>' + arow('Nora &middot; That side room. I want to see it before Sunday.', avatars=['N'], last=True) + '</div>' + meta('A REPLY, IF ONE COMES &middot; NOTHING ELSE', 8))
    inner += gut(f'<div style="display: flex; gap: 22px;">{door("Edit")}{door("Take it back", MUTE)}</div>', top=20)
    return frame(inner)

# ───────────────────────────── D3 · authored signals ─────────────────────────────
def d3a():
    from gen_c2 import friends_scope_phone
    return friends_scope_phone()
def d3b():
    inner = header('NEW YORK', 'From friends') + question_line(ctx='From friends')
    inner += gut(f'<div style="{SERIF} font-size: 18px; line-height: 25px; color: {INK2};">Nothing from friends yet.</div>', top=22)
    inner += sect('New York, anyway') + gut(place_unit('room', PLACE_NAMES['print_room'], 'Tue&ndash;Sun 11&ndash;6 &middot; listed, not checked today', '<i>Rooms Remade</i> through Sunday.', last=True))
    inner += gut(pl_ending(['All of New York']), top=20)
    return frame(inner)

# ───────────────────────────── D4 · hospitality ─────────────────────────────
def d4b():
    inner = guestbar('SATURDAY 7:10 PM &middot; THE INVITATION, UPDATED')
    inner += gut(f'<div style="{SERIF} font-weight: 600; font-size: 22px; line-height: 28px;">Pasta trial night. Saturday from seven; come at seven-thirty.</div>', top=14)
    inner += gut(f'<div style="{SERIF} font-size: 16px; line-height: 23px; color: {INK2};">&ldquo;Second attempt at the Sorrento thing. Maya&rsquo;s coming. Bring nothing, honestly.&rdquo;</div>', top=12)
    inner += gut('<div>' + row('You said: I&rsquo;m in &middot; <span style="color: #6E6862;">leaving by nine is fine</span>', mark='solid', color=GOLD)
                 + row('Court Street, 3F &middot; <span style="color: #6E6862;">the buzzer says N; the door sticks, push</span>', mark='hollow')
                 + row('With Nora and Maya &middot; nothing to bring', mark='hollow', last=True) + '</div>', top=16)
    inner += gut(door('Running late? Say so'), top=18)
    return linkframe(inner)
def d4a():
    from gen_c3 import sam_arrival
    return sam_arrival()

# ───────────────────────────── D5 · enrichment ─────────────────────────────
def d5a():
    inner = anchor_row('NEW YORK &middot; SATURDAY', '1:44 PM')
    inner += gut(ways_seq_card('This afternoon, if you want it', [('4:00', 'The Print Room, the side room', 'Maya says it empties after four and the shop shuts at five.', 'MAYA&rsquo;S SUGGESTION'), ('4:45', 'Home on foot by 5:10', 'Twenty minutes. The pasta from six.', 'YOUR WORDS')],
                              meta_t='The cost: your only free stretch this afternoon, and Maya cannot join until dinner. Listed hours 12&ndash;6, not checked today.'), top=18)
    inner += gut(src('The same four inputs as B, as a sequence with the cost as its own line. Original-only (02.3) stands beside both.'), top=12)
    return frame(inner)
def d5b():
    inner = anchor_row('NEW YORK &middot; SATURDAY', '1:44 PM')
    inner += gut(card(f'<div class="kick" style="color: {GOLDD};">FOR YOUR AFTERNOON</div>' + title('Go at four, and you are home before the pasta', 20, 25, 600)
                      + f'<div style="{SERIF} font-size: 15px; line-height: 22px; color: {INK2}; margin-top: 8px;">Maya suggests the side room after four and says the shop shuts at five, so four to a quarter to five covers both. The gallery lists 12 to 6. It is a twenty-minute walk home, which puts you in the kitchen by 5:10, before six. It is your only free stretch this afternoon, and Maya can join at dinner, not before.</div>' + meta('MAYA&rsquo;S SUGGESTION &middot; YOUR WORDS &middot; LISTED HOURS &middot; A WALK', 8)), top=18)
    inner += gut(src('The same four inputs and the same permissions as A, as prose. It claims nothing unsupported. The cost sits in the last sentence, where a reader can miss it.'), top=12)
    return frame(inner)

# ───────────────────────────── D6 · continuity ─────────────────────────────
def d6a():
    inner = guestbar('AFTER SUNDAY &middot; OCCASION-BOUND')
    inner += gut(f'<div style="{SERIF} font-weight: 600; font-size: 22px; line-height: 28px;">Saturday, at Nora&rsquo;s</div><div style="font-size: 14px; line-height: 20px; color: {INK2}; margin-top: 8px;">Maya&rsquo;s photograph of the table, here as long as she leaves it, and the dinner&rsquo;s shared facts: Saturday Sep 19, from seven, at Nora&rsquo;s. The evening&rsquo;s details closed on Sunday. Nothing Nora wrote for herself.</div>', top=14)
    inner += gut(f'<div style="border-radius: 12px; overflow: hidden;">{standin(140, "THE TABLE &middot; STAND-IN")}</div>', top=14)
    inner += gut(src('A complete ending.'), top=14)
    return linkframe(inner)
def d6b():
    inner = anchor_row('NEW YORK &middot; LATER', '')
    inner += sect('In motion') + gut('<div>' + arow('Sam &middot; <span style="color: #6E6862;">in touch &middot; share things and invite each other again</span>', avatars=['S'], last=True) + '</div>')
    inner += gut(src('Both said yes (04.6, 04.7). Nothing of the past opened; each share still chooses its audience. Mute, disconnect, block and report are separate choices, none a prerequisite for another.'), top=14)
    return frame(inner)

def message_thread():
    """The control: the same photograph and line in a capable ordinary messaging app. Not a straw alternative."""
    head_ = (f'<div style="display: flex; align-items: center; gap: 10px; padding: 24px 22px 14px 22px; border-bottom: 1px solid rgba(27,23,20,0.10);">{BACK}'
             f'<span style="width: 30px; height: 30px; border-radius: 15px; background: {INK}; color: {CARD}; display: flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 700;">M</span>'
             f'<span style="font-size: 16px; font-weight: 600;">Maya</span><span class="fn" style="margin-left: auto; color: {MUTE};">MESSAGES</span></div>')
    bub = (f'<div style="display: flex; justify-content: flex-start; padding: 0 22px; margin-top: 16px;"><div style="max-width: 280px; background: {CARD}; border-radius: 18px; overflow: hidden;">'
           f'{plate("room", 170, tag="ILLUSTRATION &middot; NOT HER PHOTOGRAPH")}<div style="padding: 10px 14px; font-size: 15px; line-height: 21px;">{LINE_D7}</div></div></div>')
    react = (f'<div style="padding: 8px 22px 0 34px; display: flex; gap: 14px; align-items: center;"><span class="fn" style="color: {MUTE};">DELIVERED 7:41 PM</span>'
             f'<span style="border: 1px solid rgba(27,23,20,0.16); border-radius: 999px; padding: 3px 10px; font-size: 12px;">&hearts;</span>'
             f'<span style="border: 1px solid rgba(27,23,20,0.16); border-radius: 999px; padding: 3px 10px; font-size: 12px;">Save image</span></div>')
    bub2 = (f'<div style="padding: 14px 22px 0 22px;"><div class="kickm" style="color: {MUTE};">FRIDAY</div></div>'
            f'<div style="display: flex; justify-content: flex-start; padding: 0 22px; margin-top: 8px;"><div style="max-width: 280px; background: {CARD}; border-radius: 18px; padding: 10px 14px; font-size: 15px; line-height: 21px;">{LINE_D7B}</div></div>'
            f'<div style="padding: 6px 22px 0 34px;"><span class="fn" style="color: {MUTE};">DELIVERED 6:12 PM</span></div>')
    field = (f'<div style="padding: 22px;"><div style="display: flex; align-items: center; gap: 10px; min-height: 44px; border: 1px solid rgba(27,23,20,0.14); border-radius: 22px; padding: 0 16px;">'
             f'<span style="font-size: 15px; color: {GHOST}; flex: 1;">Message</span></div></div>')
    return frame(head_ + f'<div style="padding: 14px 22px 0 22px;"><div class="kickm" style="color: {MUTE};">THURSDAY</div></div>' + bub + react + bub2 + field)

def board05():
    pairs = [
        pair('D1 &middot; SHARING INTO POSSIBILITY &middot; OPENNESS', 'Natural language alone, or one author-controlled openness affordance?',
             'Natural language remains the leading option, with the audience chosen per share. Sharing, openness and an actual invitation must stay distinguishable without required composer modes: a line is a line; an opening is a line that says so; an invitation is a Send to named people with a preview. The toggle is a fair alternative that makes openness explicit at the cost of a second state. Observe whether recipients can tell the three apart before adopting either.',
             side('A &middot; LANGUAGE ONLY &middot; LEADING', d1a(), 'B0 FROM THE HANDOFF &middot; NORA&rsquo;S OWN SHARE'), side('B &middot; ONE OPENNESS AFFORDANCE', d1b(), 'AN AUTHOR-CHOSEN STATE; &ldquo;I&rsquo;D COME&rdquo; IS A REQUEST, NOT PARTICIPATION')),
        pair('D2 &middot; ACKNOWLEDGMENT', 'Is a private Reply sufficient, or does one voluntary acknowledgment earn its place?',
             'Not adopted either way. Both alternatives let the recipient leave without responding; neither reports passive consumption or counts anything. A shows the contributor one reply if one comes; B adds one voluntary, author-only word the recipient chooses. The cost of A is that Maya cannot tell silence from absence; the cost of B is a small new gesture to understand. The first decision to observe with a real friend.',
             side('A &middot; REPLY ONLY', maya_return_min(False), 'REUSES 02.7'), side('B &middot; REPLY + ONE WARM WORD', maya_return_min(True), 'AUTHOR-ONLY &middot; NO COUNT &middot; NOT A READ RECEIPT &middot; TESTED AS WARMTH, NOT UTILITY')),
        pair('D3 &middot; FRIEND-AWARE DISCOVERY &middot; AUTHORED SIGNALS', 'Which authored signals make a useful opening possible, and what stays private?',
             'Use relevant, authorized evidence: authored intent, declared precision, current world facts, and the recipient&rsquo;s own permitted context. No universal cap on signals and no one-card-per-friend law; the fixture&rsquo;s supply is not a product limit. Hidden location and inferred willingness stay excluded. With sparse supply the same composition holds fewer things and returns to the world; nobody is asked to post.',
             side('A &middot; RICH, AUTHORIZED SUPPLY', d3a(), 'REUSES 02.3 &middot; PHOTOS, A MAP, LINES, ELSEWHERE'), side('B &middot; SPARSE SUPPLY &middot; THE SAME COMPOSITION', d3b(), 'A FIXTURE LIMIT, NOT A PRODUCT CAP &middot; NEVER A RECRUITMENT PAYOFF')),
        pair('D4 &middot; HOSPITALITY', 'What is the minimum arrival experience that makes Sam practically included, without a profile or host work?',
             'Both alternatives now carry the same necessary facts: the door, the buzzer, the time he is expected, nothing to bring, a way to say he is late. A composes them for tonight and adds the foothold; B keeps the invitation layout updated. The recommendation is A, on understanding: the day-of composition puts what matters tonight first. Observe whether it actually improves understanding; the facts are equal.',
             side('A &middot; THE DAY-OF COMPOSITION &middot; RECOMMENDED', d4a(), 'REUSES 03.7'), side('B &middot; THE INVITATION, UPDATED &middot; SAME FACTS', d4b(), 'EQUALLY COMPLETE; THE LAYOUT IS THE ONLY DIFFERENCE')),
        pair('D5 &middot; ENRICHMENT', 'Which original-only treatment wins, and where does added context materially improve receiving?',
             'Original-only stands for receiving (02.3, reused). For the afternoon, A and B use the same four inputs under the same permissions. A, the sequence with the cost on its own line, is recommended for legibility; B, the prose, is a fair presentation that is not disqualified as a category. What disqualifies a specimen is invented quiet or unauthorized sourcing, and neither appears here. Vesper&rsquo;s addition is marked as its own, not as Maya&rsquo;s endorsement.',
             side('A &middot; THE SEQUENCE &middot; RECOMMENDED', d5a(), 'REUSES 03.5&rsquo;S CARD &middot; LEDGER &sect;8.2'), side('B &middot; GENERATED-LED PROSE &middot; SAME INPUTS', d5b(), 'FAIR: NO INVENTED QUIET, NO A1 &middot; THE COST IS HARDER TO SEE')),
        pair('D6 &middot; CONTINUITY', 'Occasion-bounded exchange, or an optional ongoing connection?',
             'One understandable optional connection, sought rather than solicited, with the audience still chosen per share. Occasion-bounded contact stays valid and complete. Connecting enables exchanging eligible things (a photo, a place, a recipe, a line) and inviting without a new link; nothing of the past. No second friends-membership ritual, no post-photo prompt, no cap at photos and text.',
             side('A &middot; OCCASION-BOUND &middot; VALID AND COMPLETE', d6a(), 'SAM&rsquo;S LINK AFTER SUNDAY'), side('B &middot; CONNECTED &middot; SOUGHT, MUTUAL', d6b(), 'REUSES 04.6 / 04.7 &middot; THE NAMED CAPABILITY ON HOME')),
    ]
    pairs.append(pair('D7 &middot; THE ORDINARY ALTERNATIVE &middot; WHAT THE SHARE MAKES POSSIBLE', 'The same two people and, on both sides, the same three inputs. What can follow that a capable thread cannot do?',
             'Matched evidence, stated exactly. The later case does not run on Thursday&rsquo;s note. It needs three things: A1, Maya&rsquo;s photograph and her weekday line, shared to friends on Thursday; B2b, a second and separate contribution from Maya on Friday, addressed to Nora as the evening&rsquo;s owner, saying the side room empties after four and the shop shuts at five; and a fact Nora supplied herself, that she has to be home by six to start the pasta. Both sides get all three, plus the gallery&rsquo;s listed hours, the walk time, ordinary search and the link Maya already sent. Vesper is credited with nothing the thread was denied and with no retyping the thread would not have to do. Honest reading: receiving is not the difference and neither is custody. What is left is that on Saturday the two contributions and her own constraint compose once, at the moment the afternoon is usable, with the cost said plainly and the option to leave it (03.5); in the thread she reads back two messages from two days, checks the hours herself, and works out whether four to 5:10 fits before six. That is a real difference and a small one, and it costs Maya a second contribution. Vesper does not need to win every share: most end at &ldquo;enjoyed it&rdquo;, complete on both sides.',
             side('A &middot; A1 RECEIVED &middot; REUSES 02.4; THE AFTERNOON IS 03.5', reader_phone(), 'THURSDAY: A1, HER WORDS AND THE LISTING AND THE GALLERY&rsquo;S NOTES APART; REPLY OPTIONAL, NOTHING OWED &middot; FRIDAY: B2b ARRIVES SEPARATELY, A SECOND CONTRIBUTION FROM MAYA, NOT THIS ONE &middot; SATURDAY: B2b AND NORA&rsquo;S OWN &ldquo;HOME BY SIX&rdquo; COMPOSE THE AFTERNOON ONCE, WITH ITS COST (03.5) &middot; SHE GOES OR LEAVES IT, AND MAYA IS TOLD NEITHER'),
             side('B &middot; A CAPABLE MESSAGE THREAD &middot; THE SAME THREE INPUTS', message_thread(), 'BOTH OF MAYA&rsquo;S MESSAGES ARE HERE, THURSDAY AND FRIDAY &middot; ORDINARY SEARCH, THE LINK SHE SENT, THE ADDRESS ALREADY IN THE THREAD &middot; ARRIVES AT ONCE, COSTS NOTHING, EVERYONE HAS IT &middot; ON SATURDAY SHE READS BACK TWO DAYS, CHECKS THE HOURS AND FITS IT AGAINST SIX HERSELF &middot; NOTHING HERE KNOWS SHE HAS AN AFTERNOON')))
    rows = ['<div style="display: flex; gap: 60px; align-items: flex-start;">' + pairs[0] + pairs[1] + '</div>',
            '<div style="display: flex; gap: 60px; align-items: flex-start; margin-top: 46px; padding-top: 34px; border-top: 1px solid rgba(27,23,20,0.12);">' + pairs[2] + pairs[3] + '</div>',
            '<div style="display: flex; gap: 60px; align-items: flex-start; margin-top: 46px; padding-top: 34px; border-top: 1px solid rgba(27,23,20,0.12);">' + pairs[4] + pairs[5] + '</div>',
            '<div style="display: flex; gap: 60px; align-items: flex-start; margin-top: 46px; padding-top: 34px; border-top: 1px solid rgba(27,23,20,0.12);">' + pairs[6] + '</div>']
    return (HEAD_VDL + f'<div style="width: 2260px; min-height: {hh("05")}px; background: #F4F0E7; box-sizing: border-box; padding: 30px 32px 36px 32px; {SANS} color: {INK}; display: flex; flex-direction: column;">'
            + head(f'VESPER &middot; SOCIAL EXPERIENCE &middot; 05 &middot; THE IMPORTANT ALTERNATIVES &middot; {STAMP}', '05 &middot; The important alternatives',
                   'Thirteen frames, one pair per decision plus D7&rsquo;s ordinary control (its A side reused from 02.4, so one frame is added against a ceiling of twelve; recorded, not resolved), revised per &sect;14: the same facts and the same grants on both sides of every pair, so presentation is what is compared. Each pair carries one recommendation, its cost, and where it should be observed rather than argued.')
            + ''.join(rows) + f'<div class="fn" style="margin-top: 30px; line-height: 16px;">{FOOT2}</div></div>' + TAIL)

# ───────────────────────────── 06 · connected route ─────────────────────────────
ROUTES = {
    'NORA': [('02.1', 'Ask about the sauce', 'CHAT'), ('02.3', 'From friends', 'PLACES'), ('02.4', 'The Print Room', 'PLACES'), ('02.5 / 02.6', 'Reply, or Ask', 'IN CONTEXT'), ('03.1', 'Host once', 'CHAT'), ('03.4', 'The dinner page', 'OCCASION'), ('03.5', 'Saturday afternoon', 'HOME'), ('04.2', 'The photo arrives', 'HOME'), ('04.4', 'The record', 'LIFE'), ('04.5', 'Find it again', 'LIFE'), ('04.7', 'Sam&rsquo;s request', 'HOME'), ('04.8', 'Another evening', 'CHAT'), ('04.9', 'Maya&rsquo;s page', 'LIFE')],
    'MAYA': [('02.2', 'Share the Print Room', 'PLACES'), ('02.7', 'Her share, later', 'PLACES'), ('03.4 &middot; hers', 'Her view of the dinner page: proposing eight (not drawn)', 'OCCASION'), ('04.1', 'The table photograph', 'OCCASION'), ('02.7', 'Take it back; 04.9 is Nora&rsquo;s result', 'PLACES'), ('08.1 &rarr; 08.3', 'Nora&rsquo;s pasta: receive, open, find again', 'HOME / LIFE')],
    'DANA': [('03.3', 'Nora&rsquo;s line; one thing sent', 'HOME')],
    'SAM': [('03.2', 'The invitation', 'LINK'), ('03.6', 'Adopted branch, if any', 'LINK'), ('03.7', 'Arrival, for what he said', 'LINK'), ('04.3', 'The photo, later', 'LINK'), ('04.6', 'Stay in touch, if sought', 'LINK'), ('08.5', 'Where he returns', 'LINK')],
}
ACTIONS = [
    ['Open a friend&rsquo;s share', '02.3 &rarr; 02.4', 'The place page with her words, the listing, the gallery&rsquo;s notes', 'Back to the same scroll position; nothing marked viewed'],
    ['Private Ask', '02.4 &rarr; 02.6', 'A private answer with the object as context; Maya sees nothing', 'Return restores the question, form and scroll'],
    ['Human Reply', '02.4 &rarr; 02.5 &rarr; 02.7', 'A message to Maya; her page shows one reply', 'Back to the photo; not a memory'],
    ['Share from the object', '02.2', 'Maya&rsquo;s photo and line reach her chosen audience; owner readback once', 'Return restores the place page'],
    ['Host once', '03.1 &rarr; 03.2 / 03.4', 'Two recipients get their invitation; the dinner page exists', 'One readback line on Home'],
    ['Respond to an invitation', '03.2 &rarr; 03.4', 'A provisional answer on the bare link; confirmed by the same one-time code that unlocks the address; then Nora sees it as his', 'The link stays his'],
    ['Contribute from elsewhere', '03.3 &rarr; 03.4', 'One thing under the dinner row, attributed', 'Done; nothing asked of her'],
    ['Accept a scoped change', '03.5 &rarr; 03.6 (branch) &rarr; 03.7 variant', 'Seven stands; or, adopted, the dinner&rsquo;s start is eight for Nora, Maya and Sam, each in their own view; Sam&rsquo;s seven-thirty and nine stay his until he answers', 'Home unchanged except the one row; his row shows what he has answered'],
    ['Contribute the photograph', '04.1 &rarr; 04.2 / 04.3', 'Nora and Sam receive the image once; the authorized Send crosses the audience boundary with owner readback', 'Life holds it under the dinner'],
    ['Refind', '04.5 &rarr; 04.4', 'A door with its containment', 'Open, or leave; nothing written'],
    ['Seek to connect', '04.6 &rarr; 04.7', 'A request, or nothing; accept enables the named capability', 'Ignored, declined, accepted are all complete'],
    ['Continue by reference', '04.8', 'The last dinner&rsquo;s shape offered back; fresh invitations', 'Send, or change something'],
    ['Send the promised photo', '04.4 inset (its own record)', 'One email through the address they gave', 'The record stands either way'],
    ['Withdraw', '02.7 (Maya&rsquo;s Take it back) &rarr; 04.9 (Nora&rsquo;s result)', 'A2 and its derivatives gone; the rest as it was', 'No new contact'],
    ['Receive something without a place', '08.1 &rarr; 08.2 &rarr; 08.3', 'Nora&rsquo;s pasta and line arrive once on Home; the exact source opens; Life &middot; People holds it', 'Enjoy it and leave; Reply, or not'],
    ['Share to a connected guest', '08.4 &rarr; 08.5', 'One thing to Maya and Sam; Sam by text to his verified number; his link says From Nora', 'Sent once; he can leave, ask for fewer, or stop'],
]
def route_row(who, steps):
    rc, rb = ROLE[who]
    boxes = []
    for i, (n, t, root) in enumerate(steps):
        boxes.append(f'<div style="width: 150px; flex: none; border: 1px solid rgba(27,23,20,0.10); background: {CARD}; border-radius: 8px; padding: 10px 12px; display: flex; flex-direction: column; gap: 4px;"><div style="display: flex; gap: 6px; align-items: center;"><span style="{MONO} font-size: 10px; font-weight: 700; color: {MUTE};">{n}</span>{tag(root, MUTE, "rgba(27,23,20,0.06)")}</div><div style="font-size: 12.5px; line-height: 17px; color: {INK};">{t}</div></div>')
        if i < len(steps) - 1: boxes.append(f'<div style="flex: none; align-self: center; color: {GHOST};">{ARROW}</div>')
    return (f'<div style="display: flex; flex-direction: column; gap: 10px; margin-top: 22px;"><div style="display: flex; gap: 8px; align-items: center;">{tag(who, rc, rb)}<span class="fn" style="color: {ANCHOR};">FOLLOW WITHOUT READING ANYONE ELSE&rsquo;S PRIVATE CONTEXT</span></div>'
            f'<div style="display: flex; gap: 8px; align-items: stretch; flex-wrap: wrap;">' + ''.join(boxes) + '</div></div>')
def board06():
    inner = blk('ONE ROUTE PER PARTICIPANT &middot; LINKED FRAMES', ''.join(route_row(w, s) for w, s in ROUTES.items()))
    inner += '<div style="height: 34px;"></div>' + blk('ACTION &rarr; RESULT &rarr; RETURN &middot; EVERY KEY INTERACTION HAS A DESTINATION', tbl(['ACTION', 'FRAMES', 'RESULT', 'RETURN'], ACTIONS))
    inner += '<div style="height: 34px;"></div>' + blk('BRANCHES, LABELLED', tbl(['BRANCH', 'WHERE', 'RULE'], [
        ['The live change', 'Unchanged seven: 03.5 &rarr; 03.7. Adopted eight: 03.5 (adopt) &rarr; 03.6 &rarr; 03.7 variant (eight)', 'Each route reaches its own arrival view; &ldquo;seven stands&rdquo; and &ldquo;moved to eight&rdquo; never coexist. Adoption reaches Nora, Maya and Sam (tailored); Dana&rsquo;s contribution is unchanged; Sam&rsquo;s silence is not acceptance of eight'],
        ['The RSVP', '03.2 &rarr; 03.4', 'Provisional on the bare link; confirmed by the code that unlocks the address; if never confirmed, the host never sees a confirmed &ldquo;in&rdquo;'],
        ['Participation versus arrangement', '03.6 &rarr; 03.7 variant', 'The dinner&rsquo;s start (eight) and Sam&rsquo;s accepted arrival are different facts; his row keeps seven-thirty and nine until he answers; hiding, muting or blocking a person never changes who is attending (Home 10 delta)'],
        ['The ongoing connection', '04.6 &rarr; 04.7', 'Ignored, declined and accepted are three endings; only accepted produces D6-B'],
        ['The boat couple', 'A separate record, inset beside 04.4', 'Email leads; the no-path branch is the same record without the door'],
        ['Guest identity', '03.2 &rarr; 03.7 &rarr; 04.3 &rarr; 04.6', 'Branch V throughout: verified at the address boundary; the same principal sees the photo and may seek the connection'],
        ['Withdrawal', '04.9', 'A Sunday branch; the recommended route ends at 04.8 without it'],
    ]))
    inner += '<div style="height: 34px;"></div>' + N('No stub claims an external message was really sent. Participant switching belongs to the reviewer, not the product. Interactivity is out of scope for this pass; the frames above are the navigable set for a later prototype.')
    return sheet(1820, hh('06'), f'VESPER &middot; SOCIAL EXPERIENCE &middot; 06 &middot; CONNECTED ROUTE &middot; {STAMP}', '06 &middot; Connected route',
                 'Linked frames, one route per participant, with an action &rarr; result &rarr; return map. The founder can follow Nora, Maya, Dana or Sam through boards 02&ndash;04 and 08 without reading another person&rsquo;s private context. Each route points only at that person&rsquo;s own views; a view not drawn is named as such. Branches are labelled so accepted and unadopted states never coexist in one scenario.', inner)

# ───────────────────────────── 07 · decisions and return to the app ─────────────────────────────
ADOPT = [
    ['02.4 &middot; the Print Room, opened', 'OriginalReader', 'density full; show reader, then show ask; supplied media and thumbnail', 'The gallery&rsquo;s notes and Priya&rsquo;s visit, which this page owns, placed between the reader and the private Ask: the selected order is restored, and the Print Room drawing and thumbnail are back'],
    ['02.5 &middot; Reply to Maya, in context', 'OriginalReader', 'density full, compose; show reader, then show ask; supplied media and thumbnail', 'As 02.4, with the editor and Send kept; the result below it on the shared Notice'],
    ['05 D7-A &middot; A1 received', 'OriginalReader', 'density full; show reader, then show ask; supplied media and thumbnail', 'As 02.4. Both sides of the comparison now carry the Print Room drawing again'],
    ['03.1 &middot; host once', 'InviteCard &times;2', 'view host, labelled facts, delivery line on Sam&rsquo;s', 'The chat around them: Nora&rsquo;s sentence, the answer line, Send and the field'],
    ['03.2 &middot; Sam&rsquo;s link', 'InviteCard', 'view guest, shape pill', 'The link page&rsquo;s address bar and its footer'],
    ['02.2 continued, 02.5 result', 'Notice', 'tone applied, failed', 'The inset frame around them'],
    ['09.1, 09.2, 09.4 &middot; choosing, previewing, withdrawing', '.vdl-sheet, .vdl-field, .vdl-btn, .vdl-recipient', 'shared styles, not components', 'The sender&rsquo;s own share view, which has no shared variant'],
    ['09.3, 09.5, 09.7 &middot; the results', 'Notice', 'tone applied, failed, unknown, stale', 'The frames around them'],
]
MISSING = [
    'OriginalReader full with an optional Keep and a non-spatial &ldquo;where it lives&rdquo; in place of the place row (08.2; Life 07.7/07.8 is the donor), so 08.2 stays local',
    'OriginalReader for the sender&rsquo;s own share, with its one reply, Edit and Take it back and a withdrawal that can fail; now drawn locally on 09.4 and 09.5 and offered to the shared owner as the next variant',
    'OriginalReader open or card with a photograph (04.2 and 08.1, a friend&rsquo;s photo arriving on Home), so both stay local',
    'InviteCard for a changed arrangement seen by a guest, with a primary and a secondary answer under his own labels (03.6); the answered view offers two secondary actions only, so 03.6 stays local',
    'InviteCard for the day of arrival (03.7), and the guest link page&rsquo;s bar and footer, neither of which is in the package',
    'An attributed contribution on an occasion page, with its scope line and optional media (03.3, 03.4), not in the package',
    'OriginalReader with a small photo set: a lead picture, the rest in order, per-image attribution and a casual line in sans rather than the serif quote (10.3, 10.4, 10.6; copy companion &sect;7). Local on board 10; offered to the shared owner only after Life&rsquo;s viewer anatomy is reconciled',
]
COVERAGE = [
    ['Choose or correct one recipient, with a no-match case', '09.1 to 09.3; 02.2 keeps the entry', 'Completed September 12: the sheet lists only people already connected, two friends called Nora are told apart by how she knows them, a mistyped name finds nobody, the preview is the message itself, and the result is sent, not sent, or not yet known', 'Shared-library owner, for a recipient picker built on .vdl-field and .vdl-recipient', 'Shared review of a picker component'],
    ['Optional words, audience and time, Change, send or leave', '02.2', 'Existing donor, now with its result on the shared Notice. No posting wizard', 'Shared-library owner', 'Composer component in the next package'],
    ['Reply versus private Ask, and the return', '02.5, 02.6', 'Existing donor, now built on OriginalReader full (compose) with the result on Notice; the Ask returns to the same scroll and the original is not summarised', 'Shared-library owner; Chat owner for 02.6&rsquo;s frame', 'Later native check'],
    ['The sender&rsquo;s own share: edit, take back, and a withdrawal that fails', '09.4, 09.5; 02.7 keeps the quiet return', 'Completed September 12 as local construction: the confirmation says what taking it back does before she does it, the result says what survives with its owner, and failure is stated plainly. The shared package still has no sender variant', 'Shared-library owner, with Plans 90&rsquo;s recovery semantics', 'Sender variant in a later package'],
    ['The first host step', '03.1 inset', 'Targeted addition, drawn: known facts reused, the one missing fact asked once, the same previews and Send; counted in 03&rsquo;s work table', 'Social', 'Founder review of this pass'],
    ['Guest invitation and arrival; later media', '03.2&ndash;03.7, 04.3', 'Existing donor: 03.2 adopted on InviteCard guest', 'Guest identity proposal owner', 'If the guest branch is selected for delivery'],
    ['Supported controls: fewer, mute, leave, block, report', '09.6', 'Completed September 12 as entry and actual effect, including what none of them does. No policy is adopted and no relationship model is invented; the account-wide versions belong to You &amp; Trust', 'Social with the You &amp; Trust owner', 'Founder ruling on block, mute, disconnect and report'],
    ['Photos, sent and received: select, preview, send or leave, partial failure, original-first receiving, viewer and return, later retrieval', '10.1&ndash;10.6', 'Drawn September 21 on Life&rsquo;s fixture set (ledger &sect;10, PH-01 to PH-07) and revised after the export review: selection starts from Life 04b.11, the preview names what is left out, each ending returns by outcome, and 10P runs the path with real selection and typing under one outcome rule (general selection vs pending send) offered to Life 04c. None of the photographs is supplied: every picture is a stand-in at its real proportions with its ledger ID. 10.5 compares original only, light context and earned enrichment on matched inputs; light context is selected for Home', 'Social, with Life (viewer, selection donor) and Home (placement)', 'Approved photographs; Life&rsquo;s viewer reconciliation; set delivery and copies stay separate agreements'],
    ['Guest access: preview, code, payoff, wrong or expired code, retry, changed or reopened invitation, unavailable ending', '09.7 and its endings inset', 'Drawn conditionally, as the proposed guest branch only. No verification mechanism is adopted and a failed code never removes the evening he already has', 'Guest identity and delivery proposal', 'Selection of the guest service'],
]
WORKLEFT = [
    ['Nora &middot; host, 14 slots', 'One sentence to host (03.1); one Send. On the day, nothing', 'Reply to Maya; ask privately; adopt or leave Maya&rsquo;s eight; answer Sam&rsquo;s connection request; send the boat photo; start another evening from one line (04.8)', 'No guest list to build, no address to retype, no thanks to collect, no recap to write, no reflection prompt', 'Seven stands, the dinner happens, the record still forms from what people did'],
    ['Maya &middot; friend, 3 slots', 'Nothing. She is a friend, not an operator', 'Share from an object with one line (02.2); propose eight once (03.5); contribute the photograph (04.1); take her note back (02.7, 04.9); receive Nora&rsquo;s pasta and keep it or not (08.1&ndash;08.3)', 'No acknowledgment owed, no read receipt, no reciprocal photo, no audience management after the fact', 'She keeps her photograph and her words; nobody is told she was quiet'],
    ['Dana &middot; elsewhere, 1 slot', 'Nothing. She is not attending', 'Send one thing to the dinner&rsquo;s people from an addressed line (03.3)', 'No membership, no address, no answers to give, no thank-you expected', 'Nothing happens and nothing is missing; her tip simply is not there'],
    ['Sam &middot; guest with no account, 5 slots', 'Open a link; answer once; confirm his number when the address is needed (03.2, 03.4)', 'Say his constraint in his own words; answer the changed time; look at the photograph later; seek a connection under Nora&rsquo;s name (04.6); ask for fewer or stop (08.5)', 'No app, no profile, no account, no reason for declining, no upgrade to a friendship to receive anything', 'He is a link-holder who never confirmed: the host sees no confirmed attendance, and nothing else happens'],
    ['The couple from the boat &middot; 1 note', 'Nothing at all', '&mdash;', 'They are never contacted by the product; only Nora&rsquo;s one promised email exists, through the address they gave', 'The record stands either way'],
]
DECISIONS = [
    ['D1 &middot; Sharing into possibility', 'Natural language leads; audience chosen per share; sharing, openness and invitation distinguishable without composer modes. The explicit-openness toggle is a fair alternative, not rejected', 'A friend&rsquo;s interest may go unnoticed; an explicit state costs a second thing to learn', '05 pair 1; 02.2; 03.1', 'Can a recipient tell a line, an opening and an invitation apart?'],
    ['D2 &middot; Acknowledgment', 'Not adopted. Reply-only and one voluntary author-only acknowledgment compared fairly; both let the recipient leave without responding; no counts, no consumption report', 'A: silence is indistinguishable from absence. B: one more gesture to understand', '05 pair 2; 02.7', 'First to observe with a real friend'],
    ['D3 &middot; Friend-aware discovery', 'Relevant authorized evidence: authored intent, declared precision, current world facts, the recipient&rsquo;s permitted context. No signal cap, no one-card-per-friend law; hidden location and inferred willingness excluded', 'Generous supply needs authored material to exist', '05 pair 3; 02.3', 'Sparse and empty states on a real account'],
    ['D4 &middot; Hospitality', 'Equally complete facts on both sides; the day-of composition recommended for understanding, not for containing more', 'The host supplies the door facts once', '05 pair 4; 03.7', 'Does the day-of composition improve understanding?'],
    ['D5 &middot; Enrichment', 'Original-only for receiving. The sequence for the afternoon, compared with prose on the same inputs and grants; the category is not disqualified, unsupported claims are', 'Enrichment needs an authorized source', '05 pair 5; 03.5; ledger &sect;8.2', 'Whether the afternoon possibility is used'],
    ['D6 &middot; Continuity', 'One understandable optional connection, sought not solicited: share things and invite each other again; audiences still chosen per share; occasion-bounded contact stays valid and complete; hiding, muting or blocking a person never changes who attended or is attending', 'People who want more must seek it; nothing widens by itself', '05 pair 6; 04.6, 04.7', 'How often either side seeks it; whether leaving it feels complete'],
]
STATUS = [
    ['Seven sentences; Home social split; Life behavior sequences; T0/T1/T2', 'Ruled', 'Applied as drawn; nothing here amends them'],
    ['Places C6, C7; Home&rsquo;s sequence form; one Chat aperture per page', 'Given', 'Reused; not re-proposed'],
    ['D1&ndash;D6 recommendations', 'Proposed', 'For the root owners and the founder'],
    ['C5: share things and invite each other again, between two people who both said yes; audiences still chosen per share; mute, disconnect, block and report distinct, none a prerequisite, no automatic report', 'Proposed', 'Pair circles are the first container candidate; a verified non-account principal is the guest proposal&rsquo;s open question'],
    ['The scoped source-use assumption on A1 (ledger &sect;8.3)', 'Fixture assumption', 'Drawn on no main-route frame; 02.6 is independent world context (the second kind of receiving)'],
    ['The optional Keep on the exact-original reader (08.2) and its source agreement', 'Proposed', 'Drawn as one plain door, worded with Life 07.7 / 07.8: a copy to reread until she takes it back. Share expiry and her taking it back are different conditions and only the first is survived; the agreement itself is not adopted'],
    ['03.5&rsquo;s prepared proposal', 'Selected, per the September 9 decision', 'One door prepares one addressed, editable message to Maya and ends in Send proposal, which sends words only. Dinner stays at seven; her answer is not recorded; Sam is neither asked again nor quoted; leaving it sends nothing. The owner-instructed Update &amp; send route is Plans&rsquo;, available on an explicit instruction and not a button beside this one'],
    ['Photographic assets: four originals', 'Gap, bounded and labelled', 'None is sourced. Corrected: the Print Room&rsquo;s authored illustration is not Maya&rsquo;s visit photograph either, and its plate now says so. Needed: Maya&rsquo;s Print Room side room (Thursday), Nora&rsquo;s pasta (Thursday 7:40 pm), Maya&rsquo;s table (Saturday 8:25 pm), Dana&rsquo;s rag&ugrave; (Sorrento, Wednesday). Ordinary, unpolished, attributed to the fixture author who took them; no stock or generated image may stand as a person&rsquo;s own evidence. Sourcing is its own scope and blocks nothing else here'],
    ['Comparison budget: 13 frames on 05 against a ceiling of 12 (D7-B)', 'Unresolved scope discrepancy', 'D7 was asked for by the second-pass alignment and its A side is reused from 08.2, so one frame was added; the ceiling was not amended'],
    ['Entity 04.08&rsquo;s automatic use receipt', 'Excluded pending a decision', 'Kept out of the selected route; the decision belongs to the Entity owner and the founder'],
    ['Frame budget: 41 storyboard slots against the 24-slot ceiling (boards 08, 09, 10); 16 comparison frames against 12 (05 D7-B, 10.5)', 'Unresolved scope discrepancy', 'Boards 08, 09 and 10 were each asked for by an assignment (September 8, 12 and 21) and kept for review; neither ceiling was amended. Either the ceilings move or frames fold (08.3 into 04.5&rsquo;s grammar; 08.4 into 02.2&rsquo;s; 10.6 into 08.3&rsquo;s); the founder decides'],
    ['Casual non-spatial placement (08.1&ndash;08.3): Home addressed region as arrival, Life &middot; People as the pull route', 'Proposed', 'A named proposal for the Home and Life owners; the alternative (Places &middot; From friends without a pin) is fair and unadopted'],
    ['Block, mute, disconnect, report', 'Proposed', 'Distinct choices, none a prerequisite for another; block directly available'],
    ['Dana&rsquo;s contributor path; Sam&rsquo;s later photo and its confirmation; the boat email send', 'Dependency', 'Drawn as intended; support unverified (capability map, seams 3, 4, 7)'],
]
COST = [
    ['Maya&rsquo;s photo and words; Dana&rsquo;s tip; Sam&rsquo;s nine; Nora&rsquo;s lines', 'Original material', '02.3, 02.4, 03.3, 03.4, 04.1&ndash;04.3', 'Zero generation; rendering only'],
    ['The Print Room listing, the gallery&rsquo;s notes, walking time, hours', 'Reusable world content', '02.4, 02.6, 03.5', 'Fetched once; the unverified register says when'],
    ['Who is in, what arrived, the dinner page, the record, the week', 'Ordinary state composition', '03.4, 04.4, every Home and Life frame', 'Deterministic; no model'],
    ['The cooking answer (&sect;8.1); the afternoon possibility (&sect;8.2); the private Ask answer (02.6)', 'Fresh AI work', '02.1, 03.5, 02.6', 'Three turns across the whole route; never per impression'],
]
DELTAS = [
    ['Home 42876b8c &middot; 02 / 11', 'A received photograph may lead a Continuity unit with the image itself (04.2); a connection request is one In-motion row (04.7). Neither creates an Addressed-to-you section on its own: the two-item rule stands', 'A photo the host never took; the request is addressed material', 'Home social split unchanged; two-item region condition preserved', 'Seam 1 receiving path; seam 6 container', 'Adapt'],
    ['Home 42876b8c &middot; 02', 'The one ask may be a person&rsquo;s proposal stated with its tradeoff and a direct action (03.5); the sequence form may carry a friend&rsquo;s authored suggestion as a stop with attribution', 'A practical choice may have a usable action; the &sect;8.2 possibility', '&sect;11.16 untouched (one crown); the one-social-ask budget is not a one-artifact budget', 'Seam 5 prepared alternative', 'Adapt'],
    ['All roots', 'Policy narration leaves the phones: no &ldquo;nothing was saved&rdquo; lines, no statements about what anyone felt; the few context labels that matter stay (who is asked, who sees this)', 'Safeguards disappear into understandable behavior', '&mdash;', '&mdash;', 'Adapt'],
    ['Places 516a3ea4 &middot; 04', 'Keep the share card and contextual Reply as drawn; add the listing&rsquo;s unverified register line and the &ldquo;from the gallery&rdquo; reading kept apart from her words (02.4); the sender&rsquo;s own page with Edit / Take it back and one reply (02.7)', 'Three registers; the sender&rsquo;s quiet return', 'C6 unchanged', 'Seam 1 author identity on the unit', 'Adapt'],
    ['Places 516a3ea4 &middot; 04', 'Do not add a use report to a share', 'R5&rsquo;s automatic &ldquo;used in&rdquo; is excluded', '&mdash;', '&mdash;', 'Keep'],
    ['Plans cd2e1f82 &middot; 04 C', 'The recipient preview names the scope in words (dinner only; the exact address only after a one-time code to the number the host typed, branch V); a link-holder answer is provisional until that confirmation; the guest page carries an optional &ldquo;anything she should know&rdquo; line under the same rule (03.1, 03.2, 03.4)', 'Guest value before adoption; response distinguished from confirmed recipient identity', 'Seven sentences unchanged', 'Seam 3 occasion-scoped invitation; recipient verification', 'Adapt'],
    ['Plans cd2e1f82 &middot; 05 D / 11', 'The adopted change reaches every person at the dinner, tailored: the guest&rsquo;s row restates his constraint (03.6) and his arrival view follows the adopted branch (03.7 variant); the arrival frame is a parameterized state on the guest page', 'Tailored disclosure, not exclusive disclosure; hospitality', 'Sentences 4 and 5 unchanged', 'Seam 5 per-recipient readback; seam 3 arrival update', 'Adapt / Replace the static resolved push'],
    ['Life e72a2fd2 &middot; 07 / 03b', 'The dinner record lists what each person added with a guest (Sam) attributed though he has no account; refind returns a friend&rsquo;s photograph with author and containment (04.4, 04.5)', 'Unequal participation is normal; retrieval of a shared photo', 'Life sequences unchanged', 'Seam 7 author and media refs; refind over sources', 'Adapt'],
    ['Life e72a2fd2 &middot; 07', 'Withdrawal wording as drawn; the withdrawn item&rsquo;s dependents named as gone, the independent items named as standing (04.9)', 'R3&rsquo;s wording, reused', 'Correction contract unchanged', 'Seam 7 dependency edges beyond the Source lane', 'Keep'],
    ['Chat (no project)', 'A &ldquo;contribution&rdquo; context chip that names who is asked and says the friend sees nothing (02.6); the host sentence with two recipient previews and one Send (03.1)', 'Two recipients, two frames', 'Chat entry unchanged; T0 as a gate', 'Seam 2 contribution seed type', 'Proposal'],
    ['Occasion (canonical owner)', 'The guest link page family under branch V: safe preview, answer, address after a one-time code, arrival, the photo later through the verified link, stay in touch when sought (03.2, 03.6, 03.7, 04.3, 04.6)', 'Guest value without adoption', 'A bounded guest is not a member; sensitive facts only after verification', 'Seam 3: extend canonical Occasion invitations; guest identity and delivery unresolved', 'Integration gap, not a build authorization'],
    ['Home 42876b8c &middot; quiet days', 'A quiet Home still carries concrete, current, usable world openings (04.2: Bach at the old church at four; 04.7: the noodle counter till ten) with context and destination; illustrative, not a rule of exactly one; listed information, attributed experience and current conditions kept apart in the copy', 'Quiet is low coercion, not low value', 'Posture rules unchanged', 'World-content supply and its confidence for quiet days (Home and Content owners); the copied baseline does not meet this on its own', 'Delta to the Home owner; dependency marked'],
    ['Home 42876b8c &middot; 10 (block state, as now drawn)', 'Home 10&rsquo;s block frame now reads &ldquo;quieter, not emptier; the count stands&rdquo;: attendance is the arrangement owner&rsquo;s fact (four), the blocked person is not shown and not removed, no banner, and it names the viewer-safe treatment as Social&rsquo;s to lead (provisional). Social&rsquo;s treatment, for the same recipient and branch: on the dinner page and in Home&rsquo;s occasion row the count is the arrangement&rsquo;s; the hidden person&rsquo;s row is simply absent for the viewer who hid them; nothing announces it; the host&rsquo;s page and everyone else&rsquo;s are unchanged; Fewer and Stop (08.5) are the same family and never touch attendance', 'Safe shared truth; hiding someone does not remove them', 'Attendance is Occasion truth; mute, hide, block, report are the viewer&rsquo;s', 'Seam 5 per-recipient readback', 'Reconciled with Home 10 as drawn; Home keeps the count, Social leads the viewer-safe rule; provisional until the arrangement owner rules'],
    ['Home 42876b8c &middot; placement, as an extension', 'September 5 already permits two homes for a casual share with no Place: a Status doorway on Home while featured, and Life &middot; People after. The delta is one step: the fuller original itself arrives once in Home&rsquo;s addressed region when the share&rsquo;s audience includes the recipient (Friends eligibility as the condition), under the two-item rule (08.1); nothing lands on the recipient&rsquo;s week. Either reading of the Home review, addressed material or the featured-Status doorway, is a small change from here', 'Casual receiving without forcing a location, and without a second social surface', 'The accepted social split and the four roots are unchanged; place-bound shares still open in Places', 'Friends audience (proposal)', 'Proposal to the Home owner; the alternative (Places &middot; From friends, no pin) stays fair'],
    ['Home 42876b8c / Life e72a2fd2 &middot; the origin stack', 'A Life-owned source opened from Home keeps its Home-origin stack: 08.2 renders with Home active and Back restores Home&rsquo;s scroll; it becomes a Life page only when the person deliberately crosses roots (08.3)', 'One object, one reader, no root whiplash', 'Home borrows Life&rsquo;s pass grammar (September 5); unchanged', 'None', 'Adopt as drawn; return to both owners'],
    ['Life e72a2fd2 &middot; the exact-original route and its one Keep', 'The reader offers one optional, plainly worded Keep (a private copy under the author&rsquo;s grant, not disclosed to her) beside Reply and the private Ask; continuing shared access is the default and needs no Keep; refinding infers nothing; 08.3 shows shared-with-you and kept as two rows (08.2, 08.3)', 'Enjoying and refinding cost nothing; retaining is a deliberate, legible act', 'Life&rsquo;s accessible-versus-deliberately-kept distinction, as asked', 'The retention agreement itself (proposed)', 'Return to the Life and Entity owners; agreement stays proposed'],
    ['Plans cd2e1f82 &middot; 07 / 11 &middot; the amendment', 'Social holds 03.5&rsquo;s assistance unselected and no longer draws two equivalent effects. What it asks Plans to preserve in whichever shape wins: preparing a message, the human reading and sending it, and the arrangement actually moving are three separate events; reducing addressing and retyping is not invented intimate meaning; leaving it is an ending, not a button; and a sent proposal is neither an adopted arrangement nor a response', 'Useful assistance without a second authority', 'The accepted seven-sentences rule is untouched by this project', 'The prepared-proposal comparison itself', 'Plans leads; Social selects nothing until it resolves'],
    ['Life e72a2fd2 &middot; 07.7 / 07.8 &middot; the wording', 'Adopt Life&rsquo;s wording verbatim across the shared route: opening keeps nothing; it stays findable while she shares it; a copy is yours to reread until she takes it back; a kept place is yours and keeping the place does not keep her words. Share expiry and the author taking it back are different conditions and only the first is survived by a copy', 'One vocabulary for one behaviour across two roots', 'None; this replaces Social&rsquo;s looser &ldquo;yours after her share ends&rdquo;', 'The source agreement (proposed)', 'Agreed with the Life owner; agreement stays proposed'],
    ['All roots &middot; photographic assets', 'Four frames carry the argument that a human original is the whole benefit and all four show labelled stand-ins. Ordinary, unpolished, rights-cleared photographs are needed for the pasta, the table and the rag&ugrave;; the Print Room has an authored plate already. Do not polish them into promotional imagery or present an invented photograph as a person&rsquo;s own', 'The value is the material, not the container', 'No change', 'Rights and sourcing, as its own scope', 'Flagged to the founder; not sourced here'],
    ['Entity dd48304b &middot; the revised original route', 'Received as the cross-project priority: an object opened from a friend&rsquo;s share must not discard the intent that brought the person there, and nothing may be generated on opening. Social&rsquo;s 02.4 is the receiving shape to preserve: her words, the listing and the gallery&rsquo;s own notes kept apart, a reading never made from her sentence, Reply and the private Ask as separate choices, and return to the same scroll position', 'The friend&rsquo;s perspective survives the destination', 'No generation on opening; no advice unrelated to why the person came', 'Entity&rsquo;s own destination alignment', 'Received; Entity leads its own revision'],
    ['Entity dd48304b &middot; 04.08 / 12.4', 'Inherit 12.4&rsquo;s three distinct effects (keep the place, keep her words, send onward) as the vocabulary for the reader&rsquo;s action set; do not inherit 04.08&rsquo;s automatic receipt (&ldquo;used in tonight &middot; she can see this use&rdquo;) into the selected shared route, and never let private exploration acquire a visibility consequence by copying a reference; human Reply stays in the action set beside useful / keep / send', 'A private look stays private; the sender learns nothing she was not told', 'Social&rsquo;s exclusion of use reporting is unchanged', 'A consequential decision on whether any use is ever reported', 'Kept out pending that decision; returned to the Entity owner'],
    ['Chat', 'A send to others crosses an audience boundary: the one clear Send carries it (02.2, 03.1, 03.3, 04.1); no private Keep receipt for an audience-changing contribution', 'T2 without redundant confirmation', 'Contribution contract treatments unchanged', 'Seam 1 authorized send', 'Adapt'],
]
WALK = [
    ['Maya receives something of Nora&rsquo;s that has no place, opens it, finds it again', '08.1 &rarr; 08.2 &rarr; 08.3', 'Works: it arrives once, opens to the exact source, lives under the person; no pin, no occasion', 'Where it arrives is a placement choice, not a settled rule', 'Proposed (07 root deltas); alternative named'],
    ['Sam, connected, receives one more thing and knows where he is and how to have fewer', '08.4 &rarr; 08.5', 'Works: his link says From Nora; what he already had is beside it; Fewer and Stop are his', 'A verified non-member principal is still a dependency', 'Guest proposal &sect;3 unchanged'],
    ['Nora wants help with something (02.1); a friend chooses whether a fragment is worth sharing (Maya, 02.2)', '02.1; 02.2 &rarr; 02.7', 'Works: the private answer keeps nothing; Maya shares from the object with no prelude and her return restores it', '&mdash;', 'Corrected after &sect;15: the two paths are independent'],
    ['Maya shares something ordinary and expects no proof of consumption', '02.3 &rarr; 02.7', 'Works: her page shows one reply, Edit, Take it back, nothing else', 'Her share&rsquo;s expiry (Sunday) coincides with the exhibition&rsquo;s end (Sunday) and could read as one date', 'Fixture note added to the ledger; no frame change'],
    ['Dana sends one helpful thing from elsewhere without joining or administering', '03.3 &rarr; 03.4', 'Works: her gesture, its scope, its arrival attributed', 'Her after-send readback is not drawn', 'Accepted: an authorized Send with owner readback once (T2), not a private Keep'],
    ['Sam understands the invitation, arrives comfortably, leaves on time', '03.2 &rarr; 03.4 (provisional, then confirmed) &rarr; 03.7, or 03.6 &rarr; 03.7 variant', 'Works: a provisional answer on the bare link; the code that unlocks the address confirms it; his nine in his words; each branch reaches its own arrival view', '&mdash;', 'Corrected after &sect;15 A and B'],
    ['Sam later wants the photo, not another social task or a forced friend upgrade', '04.3', 'Works under branch V: the photograph displays through his verified link as long as Maya leaves it; no separate Keep', 'His number was confirmed earlier for the address; the same principal sees the photo', 'Dependency stands (guest identity and delivery proposal)'],
    ['Two participants may want continued contact; either may prefer the bounded exchange', '04.6 &rarr; 04.7; 05 D6', 'Works on Nora&rsquo;s side; leaving it is complete on both', 'Sam&rsquo;s connected state after Nora says yes is not drawn, and a non-account guest cannot hold a pair circle', 'Recorded: C5 for a non-account guest needs the confirmed contact or an account at that boundary (C5 proposal)'],
    ['Acceptance: one experience with no AI, one with substantive added value', 'A; 03.5', 'A needs no model. The &sect;8.2 possibility is the added value; the two Chat answers are the only other generation on the route', '&mdash;', 'Met'],
]
def board07():
    comp = blk('THE RECOMMENDED COMPOSITION &middot; SEPTEMBER 9, LATER', N('<b>A.</b> An existing friend shares directly from the object with no prelude; a friend&rsquo;s share is received as her photo and her words with the place under it, beside a map, a line and someone elsewhere; opening it keeps her words, the listing and the gallery&rsquo;s notes apart; Reply is in context with the recipient at the send boundary; Ask is a Chat frame that names who is asked and answers from world help; the sender sees her share, one reply, Edit and Take it back, and nothing else. '
        '<b>B.</b> The host says one sentence and sees two previews; the guest gets a link with no app and answers with no reason; a friend elsewhere sends one thing to the dinner&rsquo;s people from an addressed line; the dinner is one page; a proposal arrives as one ask with its cost and a direct action, and seven stands unless the host adopts eight, in which case everyone at the dinner has the new time and the guest&rsquo;s arrival view follows the adopted branch; the guest gets an arrival frame on the day; the evening happens with the phones away. '
        '<b>C.</b> The guest&rsquo;s photograph is her gesture; it arrives once for the host and later for the guest through his link; the evening is one record with what each person added; one retrieval finds the photo; staying in touch is sought under the host&rsquo;s name, never appended, and enables exchanging eligible things and inviting without a link; another pasta evening comes back from the record in one line with fresh invitations; the boat couple get their photo from their own record, linked from Life People; a withdrawal removes only what depended on the note.'))
    changed = blk('HISTORY &middot; WHAT CHANGED AFTER THE &sect;14 REVISION (SUPERSEDED WHERE &sect;15 SAYS OTHERWISE)', N('The unfair pairs were redrawn: D4-B now carries the same arrival facts as A, and D5-B uses the same four inputs and permissions as A, so only presentation is compared. D2 is no longer &ldquo;reply only, adopted&rdquo;; both sides are fair and the decision is observed. D3 drops the three-signal and one-card-per-friend caps. D6 drops the photo-and-text cap and the post-photo prompt: Sam seeks the connection under Nora&rsquo;s name. 02.2 became an existing friend sharing from the object with no prelude; 02.3 gained a map; 03.5 gained direct actions; 04.2 and 04.7 lost their one-item Addressed-to-you sections and gained one concrete world opening each; 04.8 became another pasta evening that carries forward the place and a proposed start, not old constraints; the boat couple became their own record, inset beside 04.4; the guest lifecycle is one labelled branch (V) throughout; policy narration was removed from the phones and the remaining copy checked with annotations hidden.'))
    adopt = blk('SHARED PACKAGE CONSUMED &middot; VDL-STAGE1 0.4.1 FROM WORKBENCH C13AE951', tbl(['FRAME', 'SHARED COMPONENT', 'VARIANT', 'WHAT STAYED LOCAL'], ADOPT)
                + N('<b>Consumed files, vdl-stage1 0.4.1:</b> OriginalReader at etag 1789153753071940 (13,559 bytes); InviteCard and Notice byte-identical to 0.3 (etags 1789098056754095, 1789081717510486); vdl.css (sha256 7b6fa1d3&hellip;, unchanged since 0.3; its internal version string still reads 0.3) and the kernel copy of styles.css (sha256 a843ca5b&hellip;, identical to the published kernel file, stamp travel-app@e2e792913); media/print-room-illustration.svg and media/print-room-thumb.svg, Social 02.4&rsquo;s own drawings, by recorded sha256. The project&rsquo;s vdl-consumed.json lists them. Adoption is by copy at these versions, not live synchronization. Boards 02, 03 and 05 load both stylesheets. The originals are kept as <i>Before shared package</i> copies of boards 02, 03 and 05. '
                    '<b>Missing variants, reported rather than redrawn:</b> ' + '; '.join(MISSING) + '.'))
    coverage = blk('COVERAGE FOLLOW-THROUGH &middot; SEPTEMBER 10 &middot; EACH ITEM WITH A DISPOSITION, OWNER AND NEXT TRIGGER', tbl(['ITEM', 'FRAMES', 'DISPOSITION', 'OWNER', 'NEXT TRIGGER'], COVERAGE))
    selected = blk('SELECTED DIRECTION &middot; SEPTEMBER 9 DECISION, RECEIVED', N('<b>The two exemplars.</b> Original-first casual receiving (02) and the existing guest-hospitality and asymmetric-photograph sequence (03.7 &rarr; 03.8 &rarr; 04.1&ndash;04.3) are the selected social exemplars. Receiving and leaving is complete value; the afternoon is optional. No further payoff sequence and no mandatory gathering were invented. '
        '<b>The prepared-message door, as amended.</b> Sentence 6 now allows one door to open an addressed, editable message when acting on a recommendation means sending words to people already involved; the person sends, and it can be turned off. 03.5 takes the proposal route: one door, &ldquo;Ask Maya about joining at eight&hellip;&rdquo;, a prepared message to Maya reading <i>We&rsquo;ll start at seven. Would joining at eight work for you?</i>, ending in Send proposal. Effects, exactly: it sends words only; dinner does not move; Maya&rsquo;s answer is not recorded; Sam is not asked again and his departure time is not in the message; nobody is told about an unchanged dinner; leaving it sends nothing. The owner-instructed route (Plans&rsquo; preview and Update &amp; send) stays available when Nora actually instructs a change, and is not a second button beside this one. '
        '<b>D7&rsquo;s evidence, matched.</b> The comparison no longer implies Thursday&rsquo;s note pays for Saturday&rsquo;s afternoon. Its inputs are named: A1 on Thursday, B2b as a separate second contribution from Maya on Friday, and Nora&rsquo;s own &ldquo;home by six&rdquo;. Both sides get all three plus listed hours, the walk time, ordinary search and the link Maya sent; the thread is denied nothing. What remains is composition at the usable moment, and it costs Maya a second contribution. '
        '<b>Copy.</b> Sentences that explained what a line was not made from are gone; every line already carries its own source. Display remains neither retention nor permission to use material, and no private use is ever reported to the sender.'))
    sep9c = blk('SEPTEMBER 9 &middot; SECOND-PASS STRATEGY ALIGNMENT', N('<b>The assets, and the gap.</b> Every photographic plate is a labelled stand-in, so the frames argue that a friend&rsquo;s original is the whole benefit while showing nothing worth looking at. The four that matter now name what they are missing on the plate itself: the pasta (Nora&rsquo;s phone, Thursday 7:40 pm), the table (Maya&rsquo;s, Saturday 8:25 pm), the Print Room (the one authored plate that exists, Places&rsquo; own illustration) and Dana&rsquo;s rag&ugrave;. Ordinary rights-cleared photographs are still needed and are their own scope; this pass contacts nobody and imports no library. '
        '<b>The comparison that matters.</b> 05 D7 sets the exact-original reader against a capable ordinary message thread rather than a straw control, and the reading is honest: for one photograph to one friend the thread is sufficient and already installed. The difference is confined to three things: the author&rsquo;s control still means something afterwards, the material is found by person or phrase instead of by scrolling, and what she still shares stays distinct from what you copied. '
        '<b>Each person&rsquo;s work.</b> Board 03 carries the account: the same evening by message and link, and as drawn, per person, with what actually moved and what never moves. What moved is duplicate explanation, context recovery and coordination. What did not move is choosing, cooking and writing to a friend, and it should not. The fixture hands Vesper the address, the buzzer, Sam&rsquo;s number and last month&rsquo;s photograph already assembled; that is not work Vesper absorbed, and the note under the table says so. '
        '<b>Shared behaviour.</b> 03.5&rsquo;s two direct actions are deferred to Plans&rsquo; narrow amendment comparison so the two projects do not set independent defaults for one act; Nora keeps authorship and Send, and a sent proposal is not an adopted arrangement. The receiving wording is now Life 07.7 / 07.8&rsquo;s: opening keeps nothing, it stays findable while she shares it, and a copy is yours to reread until she takes it back, which is a different condition from the share expiring. '
        '<b>Evidence corrected.</b> 03.8 read as if Maya opened the door at 7:32 in the branch where she cannot arrive before eight; she now arrives at eight, and the table photograph is 8:25. 02.1 and the ledger &sect;8.1 no longer diagnose the split sauce from a photograph or guarantee Saturday&rsquo;s batch.'))
    sep9b = blk('SEPTEMBER 9 &middot; FRESH SIX-PROJECT REVIEW', N('<b>One exact-original route (08.2, 08.3).</b> The reader now offers one optional, plainly worded Keep (&ldquo;Keep this photograph &middot; a private copy, yours after her share ends&rdquo;) beside human Reply and the private Ask, which stay separate choices. Entity 12.4&rsquo;s three effects are kept apart and only two exist here: continuing shared access, which is the default and needs no Keep, and a deliberate private copy under her grant, which she is not told about; keeping a place is the third and there is no place in this material. Nothing is inferred from opening, and refinding needs no Keep. 08.3 shows the distinction as two rows rather than one: shared with you while she leaves it, and kept from Nora. The retention agreement itself stays proposed. '
        '<b>Placement, settled as an extension.</b> The September 5 amendment already gives a casual share with no Place two homes, a Status doorway on Home while featured and Life &middot; People after. The delta 08 asks for is one step from there: the fuller original itself arrives once in Home&rsquo;s addressed region when the audience includes the recipient (Friends eligibility as the condition). It is not a claim that nonspatial material had no home, no root is reopened, and nothing is forced onto a map. A Life-owned source opened from Home keeps its Home-origin stack: 08.2&rsquo;s tab bar stays Home and Back restores Home&rsquo;s scroll; 08.3 is the deliberate crossing. '
        '<b>Entity 04.08, excluded pending a decision.</b> The automatic receipt (&ldquo;used in tonight &middot; she can see this use&rdquo;) is kept out of the selected route: private exploration must not acquire a visibility consequence by being copied from a reference. Entity&rsquo;s useful / keep / send set does not replace human Reply, which remains in every original-reader action set here. No reaction, no sender consumption score. '
        '<b>04.8, the later benefit made concrete.</b> The draft now names what the authorized previous outcome supplies (the address and the buzzer, nothing to bring, the table photograph, Dana&rsquo;s dish, last time&rsquo;s seven as a proposal) and what it does not (anyone&rsquo;s availability, answered again). Old availability is never shown as current.'))
    sep9 = blk('SEPTEMBER 9 &middot; LOW-PRESSURE RECEIVING', N('<b>Corrected.</b> 08.1 no longer elevates Nora&rsquo;s opening onto Maya&rsquo;s week: no &ldquo;Saturday, pasta&rdquo; on the strip, no &ldquo;if it happens&rdquo; ending; the authored opening stays available and receiving can end with enjoyment and no response. 08.2 and 08.3 lost their doctrine lines (&ldquo;No place. Nothing here asks for one&rdquo;, &ldquo;Retrieval writes nothing&rdquo;); the original, its author, audience and lifetime carry the meaning, and Life&rsquo;s vocabulary is used: shared with you, while she leaves it, versus yours. '
        '<b>Reconciled, for the same recipient and branch.</b> Home 10 as now drawn keeps the count at four and names the viewer-safe treatment as Social&rsquo;s to lead; the rule is in the root deltas below. Plans 05 D4 now reads &ldquo;Moved to eight &middot; Sam hasn&rsquo;t answered&rdquo; with the receipt &ldquo;Updated to 8:00 &middot; sent to Maya and Sam&rdquo;; 03.6 and the 03.7 variant say the same thing from Sam&rsquo;s side and Nora&rsquo;s dinner page carries the same pending state. Life 04&rsquo;s masthead &ldquo;Yours, and what others shared with you&rdquo; and its note that a path back does not imply kept govern 08.3; Life&rsquo;s manifest also asks that Sam&rsquo;s guest record be composed as Life 07&rsquo;s dinner now is (the originals shared to him plus his own account, never Nora&rsquo;s private account), which 04.6 and 08.5 already follow. '
        '<b>Scope.</b> Board 08&rsquo;s five slots exceed the twenty-four-slot ceiling; recorded as an unresolved scope discrepancy in the status table, not claimed as compliance. <b>Still pending, unchanged:</b> guest identity and delivery, ongoing connection, source use, placement. No Friends audience or service is adopted here.'))
    sep8 = blk('SEPTEMBER 8 CONSOLIDATION &middot; CORRECTED AND CONTINUED', N('<b>Corrected.</b> 03.6 and the 03.7 variant now keep the dinner&rsquo;s start (eight) and Sam&rsquo;s accepted arrival apart: his row keeps seven-thirty and nine until he answers, the variant shows the arrival for each answer state, and Nora&rsquo;s dinner page carries Plans&rsquo; who-is-affected, who-has-answered treatment; nobody&rsquo;s silence becomes acceptance. 06&rsquo;s routes point only at each person&rsquo;s own views (Maya&rsquo;s proposal view is named as not drawn; her withdrawal is her Take it back on 02.7, with 04.9 as Nora&rsquo;s result) and the action table no longer says the adopted change reaches only Sam. 04.6 and D6-A name what Sam actually holds: Maya&rsquo;s photograph, for as long as she leaves it, and the dinner&rsquo;s shared facts; nothing Nora wrote for herself; her seeing his &ldquo;leave by nine&rdquo; in her own record is his supplied participation, not a leak. '
        '<b>Continued.</b> Board 08 adds five slots beyond the twenty-four: non-spatial receiving (08.1&ndash;08.3, from 05 D1-A through Life&rsquo;s exact-source reader to Life &middot; People) and where Sam returns after both chose connection (08.4&ndash;08.5). '
        '<b>Owner deltas.</b> Home 10&rsquo;s block state must not change attendance or count; casual non-spatial placement is a named proposal (rows below). <b>Not done, by assignment:</b> busy-social scale, extra one-friend variants, Dana receiving something through these people, acknowledgment experiments. Nothing here is user validation, a real send, an enabled feature or a verified guest principal.'))
    closed = blk('WHAT CHANGED AT THE &sect;15 CLOSE &middot; A, B, C', N('<b>A.</b> Both dinner branches now reach an arrival view that matches the arrangement in force: the unchanged-seven route ends at 03.7 (expected around seven-thirty), the adopted-eight route runs 03.5 (adopt) &rarr; 03.6 &rarr; the labelled 03.7 variant (expected around eight); the accepted answer to Maya&rsquo;s proposal reaches Nora, Maya and Sam, each tailored, and the shared dinner page updates for everyone; Dana&rsquo;s contribution is unchanged; nobody&rsquo;s silence becomes acceptance. '
        '<b>B.</b> A link-holder answer is provisional until the one-time code to the number Nora typed, the same step that unlocks the address (03.2 copy; 03.4 provisional inset); until then the host never sees a confirmed &ldquo;in&rdquo;; a decline or a private constraint follows the same rule; no second verification was added. '
        '<b>C.</b> Obsolete statements were removed or archived: the 04.8 BEFORE strip no longer carries Sam&rsquo;s old 7:30 and nine; 04.3 is branch V (no Keep confirmation); &ldquo;the address with his answer&rdquo; became the branch-V rule on the delta and the summary; this summary no longer says &ldquo;no button&rdquo; or nests the boat in the dinner; the walkthrough below no longer connects Nora&rsquo;s Ask to Maya&rsquo;s share, no longer calls Dana&rsquo;s send a private Keep, and reads 04.3 under branch V; the Life capability rows no longer generalize the legacy Refind reader; Bach and the noodles are illustrative openings, not a rule of one, and 04.7 no longer asserts &ldquo;no wait after nine&rdquo; from listed hours. The &sect;14 changelog beneath is kept as history.'))
    payoff = blk('ONE HUMAN PAYOFF, END TO END &middot; AND ITS EQUALLY VALID ENDING', N('<b>Casual sharing.</b> Maya, on the Print Room&rsquo;s own page, writes one line and chooses who sees it (02.2). No prelude, no occasion, no connection to accept. '
        '<b>Enjoyable receiving.</b> It reaches Nora among the other things her friends have left, beside a map, a line and someone elsewhere (02.3). Opening it keeps Maya&rsquo;s words, the listing and the gallery&rsquo;s own notes apart, so what Nora enjoys is Maya&rsquo;s perspective and not a summary of it (02.4). Nothing is asked. She may reply (02.5), ask privately without Maya knowing (02.6), or close it. '
        '<b>An offline possibility, optional.</b> On Saturday the afternoon is her only free stretch, and Maya&rsquo;s reason for going is what makes four o&rsquo;clock worth using: the side room empties after four, the shop shuts at five, twenty minutes home by 5:10, the pasta from six. It appears once, with the cost said plainly, and it can be left (03.5). If she goes, Maya is not told; if she does not, Maya is not told either. '
        '<b>The equally valid ending.</b> She enjoys the photograph on Thursday and does nothing else, ever. No reply, no Keep, no reciprocal photograph, no next gathering. Maya sees one reply if one comes and nothing otherwise (02.7). That ending is not a failure of the design, and 05 D7 says so on the board.'))
    work = blk('TOTAL WORK LEFT TO EACH PERSON &middot; ACROSS THE WHOLE EXPERIENCE', tbl(['PERSON', 'WHAT THEY MUST DO', 'WHAT THEY MAY DO', 'WHAT IS NEVER ASKED', 'IF THEY DO NOTHING'], WORKLEFT))
    dec = blk('THE SIX DECISIONS', tbl(['DECISION', 'RECOMMENDATION', 'COST', 'WHERE', 'OBSERVE, NOT ARGUE'], DECISIONS))
    st = blk('ACCEPTED VERSUS PROPOSED', tbl(['ITEM', 'STATUS', 'NOTE'], STATUS))
    cost = blk('SOURCE AND COST LEDGER', tbl(['MATERIAL', 'CLASS', 'FRAMES', 'COST'], COST))
    deps = blk('UNRESOLVED DEPENDENCIES &middot; FROM THE LEDGER AND THE CAPABILITY MAP', tbl(['DEPENDENCY', 'WHERE DRAWN', 'WHAT EXISTS TODAY', 'DECISION OWNER'], [
        ['A friends audience on a share', '02.2, 02.3', 'Named-recipient and Occasion audiences exist; a user-facing Friends selection resolved from the author&rsquo;s connections is an integration gap', 'Friends-audience proposal: one connection, deliberate per-share audiences; evaluate existing named-recipient authority before adding a kind'],
        ['A guest who is not a member (branch V)', '03.2, 03.6, 03.7, 04.3, 04.6', 'Canonical Occasion membership and invitations exist for accounts; legacy invite tokens, landing and delivery are reusable; no-account access per capability, recipient verification and later media delivery are unverified integration gaps', 'Guest proposal: verification at the first sensitive boundary vs an authorized bearer design'],
        ['A contributor path outside attendance (03.3)', '03.3', 'The canonical Occasion roster and contribution authority exist; a narrow contributor view without the address is an integration gap, not a missing foundation', 'Product: the contributor invitation as an addressed line'],
        ['A prepared alternative and per-recipient readback', '03.5, 03.6', 'Proposal-only preparation and shared Plan repair exist; carrying the result to each affected person&rsquo;s reader is unverified', 'Engineering, per the live-engine owner-path matrix'],
        ['The ongoing connection and its controls', '04.6, 04.7', 'Pair circles with request / accept / decline and a pair conversation exist; per-person mute, block across links and messages, and persisted report are not established', 'C5 proposal; mute / disconnect / block / report as distinct choices'],
        ['Refind a shared photo with its author', '04.5', 'The legacy Refind reader (blocks and booking offers) cannot return a photograph; Life&rsquo;s owner projections and shadow index work are separate paths whose author and media refs are unverified, not absent', 'Engineering, reconciled with the Life owner&rsquo;s intended index path'],
        ['Withdrawal repairing dependents beyond the Source lane', '04.9', 'Real for Source contributions; no dependency edges for the other producers', 'Engineering; claim only what the edges cover'],
    ]))
    deltas = blk('ROOT DELTAS &middot; source &rarr; change &rarr; reason &rarr; contract &rarr; dependency &rarr; disposition', tbl(['SOURCE ROOT &middot; BOARD', 'EXACT PROPOSED CHANGE', 'EXPERIENCE REASON', 'CONTRACT IMPACT', 'IMPLEMENTATION DEPENDENCY', 'KEEP / ADAPT / REPLACE'], DELTAS))
    walk = blk('CHECKPOINT 3 &middot; DESIGNER WALKTHROUGH, AS CRITIQUE &middot; NOT PARTICIPANT VALIDATION', tbl(['TASK', 'ROUTE', 'RESULT', 'FINDING', 'DISPOSITION'], WALK))
    inner = comp + adopt + coverage + selected + sep9c + sep9b + sep9 + sep8 + closed + changed + payoff + work + dec + two(st, cost, 0.5) + deps + deltas + walk
    return sheet(1820, hh('07'), f'VESPER &middot; SOCIAL EXPERIENCE &middot; 07 &middot; DECISIONS AND RETURN TO THE APP &middot; {STAMP}', '07 &middot; Decisions and return to the app',
                 'One recommended experience, six recommended choices with their costs, what is accepted versus proposed, the source and cost ledger, the unresolved dependencies from the ledger and the capability map, the exact per-root deltas, and the Checkpoint 3 walkthrough run as designer critique. Home, Places, Life and Plans owners can apply the deltas without importing the exploration. Nothing here amends canon; the handback doc carries the same content in the repository.', inner)

FILES = {'05 - The important alternatives': board05, '06 - Connected route': board06, '07 - Decisions and return to the app': board07}
if __name__ == '__main__':
    for n, f in FILES.items():
        h = f(); open(os.path.join(OUT, n + '.dc.html'), 'w').write(h); print('wrote', n, len(h))
