"""September 9 selection and correction (handoff §0, 2026-09-09 22:10): the asset gap stated exactly, D7 rebuilt around the human payoff, 03.5 held unselected pending Plans."""
MISS = []
def sub(path, pairs):
    s = open(path).read()
    for old, new in pairs:
        n = s.count(old)
        if n == 1: s = s.replace(old, new)
        elif new in s: pass
        else: MISS.append((path, old[:90]))
    open(path, 'w').write(s)

HP = '/private/tmp/claude-501/-Users-feihuyan-Documents-Claude-travel-workspace/122d6063-48c0-4124-ac7f-f94b3c62dc5a/scratchpad/hp'

# ───────────────────────────── the Print Room plate is a stand-in too ─────────────────────────────
sub(HP + '/gen_p2_common.py', [
    ("""def plate(kind, h=150, tag='ILLUSTRATION'):
    \"\"\"A media plate inside a card: bleeds to the card's edges; a small corner tag says it is an illustration.\"\"\"
    return f'<div style="height: {h}px; margin: -16px -16px 12px -16px; position: relative; overflow: hidden;">{illo(kind, h)}</div>'""",
     """def plate(kind, h=150, tag='ILLUSTRATION &middot; STANDS IN FOR A PHOTOGRAPH'):
    \"\"\"A media plate inside a card. The corner tag names what the drawing is standing in for; no drawing is a person's own photograph.\"\"\"
    return (f'<div style="height: {h}px; margin: -16px -16px 12px -16px; position: relative; overflow: hidden;">{illo(kind, h)}'
            f'<span style="position: absolute; right: 10px; bottom: 8px; {MONO} font-size: 9px; letter-spacing: 1px; color: rgba(244,238,221,0.9); background: rgba(27,23,20,0.55); padding: 2px 6px; border-radius: 4px;">{tag}</span></div>')"""),
])

# ───────────────────────────── gen_c3 · 03.5 held unselected; preparation is not adoption ─────────────────────────────
sub('gen_c3.py', [
    ("               + f'<div style=\"display: flex; align-items: center; gap: 12px; margin-top: 14px;\">{pill(\"Keep seven\", False)}{pill(\"Move to eight\", False)}</div>'\n               + f'<div style=\"font-size: 13px; line-height: 18px; color: {MUTE}; margin-top: 10px;\">Or leave it: seven stands.</div>')",
     "               + f'<div style=\"display: flex; align-items: center; gap: 12px; margin-top: 14px;\">{pill(\"Move to eight&hellip;\", False)}</div>'\n               + f'<div style=\"font-size: 13px; line-height: 18px; color: {MUTE}; margin-top: 10px;\">Prepares a message to Maya and Sam. You read it and send it.<br>Or leave it: seven stands.</div>')"),
    ("('SATURDAY 1:44 PM &middot; FULL SCROLL', 'THE CHANGE, AND THE AFTERNOON', 'Maya&rsquo;s eight with its cost and a direct action; the &sect;8.2 afternoon; the rest of Home intact',",
     "('SATURDAY 1:44 PM &middot; FULL SCROLL &middot; UNSELECTED, PENDING PLANS', 'THE CHANGE, AND THE AFTERNOON', 'Maya&rsquo;s eight with its cost; the &sect;8.2 afternoon; the rest of Home intact',"),
    ("'THE TWO DIRECT ACTIONS ARE DEFERRED TO PLANS&rsquo; NARROW AMENDMENT COMPARISON (07 / 11): SOCIAL DOES NOT SET A SECOND DEFAULT FOR THE SAME ACT &middot; AN EDITABLE LOGISTICAL PROPOSAL, NOT INVENTED MEANING &middot; A SENT PROPOSAL IS NOT AN ADOPTED ARRANGEMENT'",
     "'UNSELECTED, PENDING PLANS&rsquo; NARROW PREPARED-PROPOSAL COMPARISON (07 / 11) &middot; THREE DISTINCT THINGS, NOT TWO EQUIVALENT BUTTONS: PREPARING A MESSAGE, NORA READING AND SENDING IT, AND THE ARRANGEMENT ACTUALLY MOVING &middot; LEAVING IT IS NOT A BUTTON &middot; NOTHING HERE IS A SECOND DEFAULT FOR AN ACT PLANS OWNS'"),
    ("('THE CHANGE, TWO BRANCHES', N('03.5 is the recommended route: Maya&rsquo;s eight arrives as one ask with the tradeoff stated. Whether it carries two direct actions or Plans&rsquo; recommend-once-without-buttons rule is Plans&rsquo; narrow amendment comparison to lead (07 / 11); the frame is drawn with the actions and marked deferred, so the two projects do not set independent defaults for one act. Nora keeps authorship and Send, and a sent proposal is not an adopted arrangement;",
     "('THE CHANGE, TWO BRANCHES', N('03.5 is the recommended route and its assistance is <b>unselected</b> until Plans resolves the narrow prepared-proposal comparison (07 / 11). It no longer offers two equivalent buttons. Preparing a message, Nora reading and sending it, and the arrangement actually moving are three different things: &ldquo;Move to eight&hellip;&rdquo; only prepares, Nora sends, and leaving it is not a button at all;"),
])

# ───────────────────────────── gen_c5 · D7 rebuilt around the payoff ─────────────────────────────
sub('gen_c5.py', [
    ("LINE_D7 = 'Second try. Thinking of Saturday, if anyone&rsquo;s around.'", "LINE_D7 = 'The side room was my favorite. Go on a weekday, it was empty.'"),
    ("           f'{standin(170, \"THE PASTA &middot; ASSET NOT SOURCED\")}<div style=\"padding: 10px 14px; font-size: 15px; line-height: 21px;\">{LINE_D7}</div></div></div>')",
     "           f'{plate(\"room\", 170, tag=\"ILLUSTRATION &middot; STANDS IN FOR MAYA&rsquo;S PHOTOGRAPH\")}<div style=\"padding: 10px 14px; font-size: 15px; line-height: 21px;\">{LINE_D7}</div></div></div>')"),
    ("f'<span style=\"font-size: 16px; font-weight: 600;\">Nora</span><span class=\"fn\" style=\"margin-left: auto; color: {MUTE};\">MESSAGES</span></div>')",
     "f'<span style=\"font-size: 16px; font-weight: 600;\">Maya</span><span class=\"fn\" style=\"margin-left: auto; color: {MUTE};\">MESSAGES</span></div>')"),
    ("f'<span style=\"width: 30px; height: 30px; border-radius: 15px; background: {UMBER}; color: {CARD}; display: flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 700;\">N</span>'",
     "f'<span style=\"width: 30px; height: 30px; border-radius: 15px; background: {INK}; color: {CARD}; display: flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 700;\">M</span>'"),
    ("    pairs.append(pair('D7 &middot; THE ORDINARY ALTERNATIVE', 'Is a friend&rsquo;s photograph better received here than in a capable messaging app?',\n             'Honest reading: for one photograph to one friend, a good message thread is sufficient, instant, and already installed; this comparison is not won on receiving alone. The difference appears in three places and only there: the author&rsquo;s control still means something afterwards, because a copy exists only where she permitted one and taking it back actually removes what she shared; it is found later by the person or the phrase rather than by scrolling a thread; and what she still shares and what you copied stay legibly different. Observe this pair with a real pair of friends before claiming more; a thread that already works is the thing to beat.',\n             side('A &middot; THE EXACT-ORIGINAL READER &middot; REUSES 08.2', pasta_opened(), 'FINDABLE WHILE SHE SHARES IT &middot; ONE OPTIONAL COPY, UNTIL SHE TAKES IT BACK &middot; REPLY AND PRIVATE ASK SEPARATE &middot; FOUND LATER UNDER HER NAME (08.3)'),\n             side('B &middot; A CAPABLE MESSAGE THREAD', message_thread(), 'ARRIVES AT ONCE, COSTS NOTHING, EVERYONE HAS IT &middot; SAVE IMAGE IS UNILATERAL AND PERMANENT; TAKING IT BACK DOES NOTHING &middot; FOUND AGAIN BY SCROLLING &middot; NO DIFFERENCE BETWEEN WHAT SHE STILL SHARES AND WHAT YOU COPIED')))",
     "    pairs.append(pair('D7 &middot; THE ORDINARY ALTERNATIVE &middot; WHAT THE SHARE MAKES POSSIBLE', 'The same photograph and the same two people. What can follow from it here that cannot follow from a good message thread?',\n             'Honest reading: the thread delivers Maya&rsquo;s photograph and her line perfectly well, at once, to a person who already has the app. Receiving is not the difference, and neither is custody. The difference is what the share can turn into without becoming a task. On Saturday, Nora&rsquo;s only free stretch is the afternoon; the same words that arrived on Thursday are what makes four o&rsquo;clock worth using, and the possibility appears once, with its cost stated, and can be left (03.5). In the thread she would have to remember the name, look up the hours, and decide alone; nothing there knows about her afternoon. Vesper does not need to win every share: most end at &ldquo;enjoyed it&rdquo;, which is a complete ending on both sides. This is the case worth having, and it should be observed with two real friends before it is claimed.',\n             side('A &middot; HER SHARE, OPENED &middot; REUSES 02.4 &rarr; 03.5', opened(), 'HER WORDS, THE LISTING AND THE GALLERY&rsquo;S NOTES STAY APART &middot; REPLY IS OPTIONAL, NOTHING IS OWED &middot; ON SATURDAY HER OWN FREE STRETCH MAKES FOUR O&rsquo;CLOCK USABLE, WITH THE COST SAID ONCE (03.5) &middot; SHE GOES, OR SHE LEAVES IT, AND MAYA IS TOLD NEITHER'),\n             side('B &middot; A CAPABLE MESSAGE THREAD', message_thread(), 'ARRIVES AT ONCE, COSTS NOTHING, EVERYONE HAS IT &middot; REPLY OR NOT &middot; ON SATURDAY SHE MUST REMEMBER THE NAME, LOOK UP THE HOURS AND DECIDE ALONE &middot; THE THREAD DOES NOT KNOW SHE HAS AN AFTERNOON &middot; SAVE IMAGE IS UNILATERAL AND PERMANENT')))"),
    ("'Thirteen frames, one pair per decision plus D7&rsquo;s ordinary control (its A side reused from 08.2,",
     "'Thirteen frames, one pair per decision plus D7&rsquo;s ordinary control (its A side reused from 02.4,"),
    # 07 · the payoff, end to end
    ("    work = blk('TOTAL WORK LEFT TO EACH PERSON",
     "    payoff = blk('ONE HUMAN PAYOFF, END TO END &middot; AND ITS EQUALLY VALID ENDING', N('<b>Casual sharing.</b> Maya, on the Print Room&rsquo;s own page, writes one line and chooses who sees it (02.2). No prelude, no occasion, no connection to accept. '\n        '<b>Enjoyable receiving.</b> It reaches Nora among the other things her friends have left, beside a map, a line and someone elsewhere (02.3). Opening it keeps Maya&rsquo;s words, the listing and the gallery&rsquo;s own notes apart, so what Nora enjoys is Maya&rsquo;s perspective and not a summary of it (02.4). Nothing is asked. She may reply (02.5), ask privately without Maya knowing (02.6), or close it. '\n        '<b>An offline possibility, optional.</b> On Saturday the afternoon is her only free stretch, and Maya&rsquo;s reason for going is what makes four o&rsquo;clock worth using: the side room empties after four, the shop shuts at five, twenty minutes home by 5:10, the pasta from six. It appears once, with the cost said plainly, and it can be left (03.5). If she goes, Maya is not told; if she does not, Maya is not told either. '\n        '<b>The equally valid ending.</b> She enjoys the photograph on Thursday and does nothing else, ever. No reply, no Keep, no reciprocal photograph, no next gathering. Maya sees one reply if one comes and nothing otherwise (02.7). That ending is not a failure of the design, and 05 D7 says so on the board.'))\n    work = blk('TOTAL WORK LEFT TO EACH PERSON",
    ),
    ("    inner = comp + sep9c + sep9b + sep9 + sep8 + closed + changed + work + dec +", "    inner = comp + sep9c + sep9b + sep9 + sep8 + closed + changed + payoff + work + dec +"),
    ("    ['Photographic assets on every plate', 'Gap, labelled', 'One authored plate exists (the Print Room, from Places). The pasta, the table and the rag&ugrave; read &ldquo;asset not sourced&rdquo;; ordinary rights-cleared photographs are their own scope'],",
     "    ['Photographic assets: four originals', 'Gap, bounded and labelled', 'None is sourced. Corrected: the Print Room&rsquo;s authored illustration is not Maya&rsquo;s visit photograph either, and its plate now says so. Needed: Maya&rsquo;s Print Room side room (Thursday), Nora&rsquo;s pasta (Thursday 7:40 pm), Maya&rsquo;s table (Saturday 8:25 pm), Dana&rsquo;s rag&ugrave; (Sorrento, Wednesday). Ordinary, unpolished, attributed to the fixture author who took them; no stock or generated image may stand as a person&rsquo;s own evidence. Sourcing is its own scope and blocks nothing else here'],"),
    ("    ['03.5&rsquo;s two direct actions on a proposed change', 'Deferred to the Plans owner', 'Plans leads the narrow amendment comparison (07 / 11); Social does not set a second default for the same act. Drawn as-is and marked'],",
     "    ['03.5&rsquo;s assistance on a proposed change', 'Unselected, pending Plans', 'The two equivalent buttons are gone. One action prepares a message; Nora reads and sends it; the arrangement moves only then; leaving it is not a button. Plans owns the narrow prepared-proposal comparison (07 / 11) and Social selects nothing until it resolves'],"),
    ("    ['Plans cd2e1f82 &middot; 07 / 11 &middot; the amendment', 'Social&rsquo;s &ldquo;Keep seven / Move to eight&rdquo; and Plans&rsquo; recommend-once-without-buttons rule cannot both be defaults for one act. Plans leads the narrow amendment comparison; Social&rsquo;s 03.5 is drawn with the actions and marked deferred. The distinction to preserve either way: an editable logistical proposal that reduces addressing and retyping, with the human keeping authorship and Send, is not invented intimate meaning, and a sent proposal is not an adopted arrangement or a response', 'Useful assistance without a second authority', 'The accepted seven-sentences rule is untouched by this project', 'The amendment decision itself', 'Deferred to the Plans owner and the founder'],",
     "    ['Plans cd2e1f82 &middot; 07 / 11 &middot; the amendment', 'Social holds 03.5&rsquo;s assistance unselected and no longer draws two equivalent effects. What it asks Plans to preserve in whichever shape wins: preparing a message, the human reading and sending it, and the arrangement actually moving are three separate events; reducing addressing and retyping is not invented intimate meaning; leaving it is an ending, not a button; and a sent proposal is neither an adopted arrangement nor a response', 'Useful assistance without a second authority', 'The accepted seven-sentences rule is untouched by this project', 'The prepared-proposal comparison itself', 'Plans leads; Social selects nothing until it resolves'],"),
    ("    ['Entity dd48304b &middot; 04.08 / 12.4', 'Inherit 12.4&rsquo;s three distinct effects",
     "    ['Entity dd48304b &middot; the revised original route', 'Received as the cross-project priority: an object opened from a friend&rsquo;s share must not discard the intent that brought the person there, and nothing may be generated on opening. Social&rsquo;s 02.4 is the receiving shape to preserve: her words, the listing and the gallery&rsquo;s own notes kept apart, a reading never made from her sentence, Reply and the private Ask as separate choices, and return to the same scroll position', 'The friend&rsquo;s perspective survives the destination', 'No generation on opening; no advice unrelated to why the person came', 'Entity&rsquo;s own destination alignment', 'Received; Entity leads its own revision'],\n    ['Entity dd48304b &middot; 04.08 / 12.4', 'Inherit 12.4&rsquo;s three distinct effects"),
])

# ───────────────────────────── gen_se · stamp and statuses ─────────────────────────────
sub('gen_se.py', [
    ("STAMP = 'SEPTEMBER 9 &middot; SECOND-PASS STRATEGY ALIGNMENT &middot; 2026-09-09'", "STAMP = 'SEPTEMBER 9 &middot; SELECTION AND CORRECTION &middot; 2026-09-09'"),
    ("'SECOND PASS: &sect;8.1 revised, heat is one possible cause and no guarantee about Saturday; the asset gap named on the pasta'",
     "'SELECTION: the Print Room plates now say they stand in for Maya&rsquo;s photograph; 02.2&ndash;02.7 is the first half of the one human payoff'"),
    ("'SECOND PASS: each person&rsquo;s work accounted against a message-and-link workflow; 03.5&rsquo;s direct actions deferred to Plans; 03.8&rsquo;s timing reconciled with the unchanged-seven branch'",
     "'SELECTION: 03.5&rsquo;s assistance is UNSELECTED pending Plans, with one prepared action instead of two equivalent buttons; the work account stands'"),
    ("'SECOND PASS: D7 compares original-only receiving against a capable ordinary messaging app, not a straw control; 13 frames = UNRESOLVED SCOPE DISCREPANCY'",
     "'SELECTION: D7 rebuilt on the same material and people, around what the share makes possible rather than custody; 13 frames = UNRESOLVED SCOPE DISCREPANCY'"),
    ("'SECOND PASS: the work account, the deferred amendment, the agreed receiving wording, the asset status and both budget discrepancies'",
     "'SELECTION: the one human payoff end to end, the bounded asset gap, Plans&rsquo; unselected assistance, Entity&rsquo;s received route, both budget discrepancies'"),
])
print('patched; misses:', len(MISS)); [print('  MISS', p, o) for p, o in MISS]
