"""Second pass, part 2: the per-person work account on 03, D7 (the ordinary messaging control) on 05, and 07's second-pass record."""
MISS = []
def sub(path, pairs):
    s = open(path).read()
    for old, new in pairs:
        n = s.count(old)
        if n == 1: s = s.replace(old, new)
        elif new in s: pass
        else: MISS.append((path, old[:90]))
    open(path, 'w').write(s)

# ───────────────────────────── gen_c3 · the per-person work account ─────────────────────────────
sub('gen_c3.py', [
    ("def board03():",
     """WORK = [
    ['Nora &middot; the host', 'Writes the invitation twice, once with the address and once without; retypes the address, the buzzer and &ldquo;nothing to bring&rdquo; in each; answers &ldquo;where is it again?&rdquo; on the night; holds three answers across two threads in her head; forwards Dana&rsquo;s tip and photograph to two people; remembers Sam&rsquo;s nine herself when Maya asks for eight; types the whole thing again two weeks later', 'One sentence and one Send, with a preview per recipient (03.1); the answers and the contributions arrive on one page, attributed (03.4); Maya&rsquo;s ask carries Sam&rsquo;s constraint with it (03.5); two weeks later the draft already holds the address, the buzzer, the photograph and the dish (04.8)', 'Duplicate explanation, context recovery, and the bookkeeping of who said what', 'Choosing the food, cooking it, and saying the invitation in her own words. None of that moved, and none of it should'],
    ['Maya &middot; a friend', 'Sends the photograph in one thread; sends it again to the dinner thread if she wants it seen there; asks for eight where everyone else is reading', 'Shares once from the object itself (02.2); her suggestion lands under the dinner row as a suggestion (03.4); her ask reaches the owner as a decision, not a demand in front of the group (03.5)', 'Sending the same thing twice, and a private suggestion read publicly', 'Deciding to share at all, and what to say. Her photograph and her line are hers'],
    ['Sam &middot; a guest with no account', 'Gets a text; asks what time and where; asks again on the day; says he must leave by nine and says it again when the time changes; cannot see the evening', 'Opens a link and answers once; confirms his number when the address is needed (03.2, 03.4); the arrival view carries the door, the time and his nine (03.7)', 'The back-and-forth about when and where, and repeating his own constraint', 'Deciding whether to come, and saying when he has to go'],
    ['Dana &middot; elsewhere, not attending', 'Nora asks; Dana writes a paragraph and sends a photograph; Nora forwards both to two people and explains them again', 'One addressed line reaches her; she sends one thing to the dinner&rsquo;s people, attributed, without joining (03.3)', 'The forwarding and the re-explaining; her name stays on her contribution', 'Choosing to send something at all'],
    ['The honest total', 'A capable message thread does most of this, and everyone already has one', 'What it does not do: keep one page where three people&rsquo;s contributions arrive attributed; carry a constraint into a proposed change; give a person with no account an arrival view; make &ldquo;two weeks later&rdquo; cheap', 'Duplicate explanation, context recovery, coordination', 'Nothing here removes cooking, choosing, or writing to a friend'],
]
FIXTURE_NOTE = ('The fixture hands Vesper the address, the buzzer, Sam&rsquo;s number, Dana&rsquo;s dish and last month&rsquo;s photograph already assembled. '
                'Vesper did not learn any of them here. A real first evening would have to ask Nora for the address once, and a real guest link needs a delivery path that does not exist yet. '
                'The work removed above is duplicate explanation and recovery of context the person already gave; it is not work Vesper absorbed by knowing things it was handed.')

def board03():"""),
    ("            + '<div style=\"display: flex; gap: 46px; align-items: flex-start; margin-top: 26px;\">' + ''.join(cols2) + ''.join(notes) + '</div>')\n    return (HEAD + f'<div style=\"width: 2260px; min-height: {hh(\"03\")}px;",
     "            + '<div style=\"display: flex; gap: 46px; align-items: flex-start; margin-top: 26px;\">' + ''.join(cols2) + ''.join(notes) + '</div>'\n            + '<div style=\"height: 40px;\"></div>' + blk('WHAT EACH PERSON IS LEFT DOING &middot; THE SAME EVENING BY MESSAGE AND LINK, AND AS DRAWN', tbl(['PERSON', 'BY MESSAGE AND LINK', 'AS DRAWN', 'WHAT ACTUALLY MOVED', 'WHAT NEVER MOVES'], WORK) + N(FIXTURE_NOTE)))\n    return (HEAD + f'<div style=\"width: 2260px; min-height: {hh(\"03\")}px;"),
])

# ───────────────────────────── gen_c5 · D7, the ordinary alternative ─────────────────────────────
sub('gen_c5.py', [
    ("from gen_c4 import sam_choice", "from gen_c4 import sam_choice\nfrom gen_c6 import pasta_opened"),
    ("def board05():",
     """def message_thread():
    \"\"\"The control: the same photograph and line in a capable ordinary messaging app. Not a straw alternative.\"\"\"
    head_ = (f'<div style=\"display: flex; align-items: center; gap: 10px; padding: 24px 22px 14px 22px; border-bottom: 1px solid rgba(27,23,20,0.10);\">{BACK}'
             f'<span style=\"width: 30px; height: 30px; border-radius: 15px; background: {UMBER}; color: {CARD}; display: flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 700;\">N</span>'
             f'<span style=\"font-size: 16px; font-weight: 600;\">Nora</span><span class=\"fn\" style=\"margin-left: auto; color: {MUTE};\">MESSAGES</span></div>')
    bub = (f'<div style=\"display: flex; justify-content: flex-start; padding: 0 22px; margin-top: 16px;\"><div style=\"max-width: 280px; background: {CARD}; border-radius: 18px; overflow: hidden;\">'
           f'{standin(170, \"THE PASTA &middot; ASSET NOT SOURCED\")}<div style=\"padding: 10px 14px; font-size: 15px; line-height: 21px;\">{LINE_D7}</div></div></div>')
    react = (f'<div style=\"padding: 8px 22px 0 34px; display: flex; gap: 14px; align-items: center;\"><span class=\"fn\" style=\"color: {MUTE};\">DELIVERED 7:41 PM</span>'
             f'<span style=\"border: 1px solid rgba(27,23,20,0.16); border-radius: 999px; padding: 3px 10px; font-size: 12px;\">&hearts;</span>'
             f'<span style=\"border: 1px solid rgba(27,23,20,0.16); border-radius: 999px; padding: 3px 10px; font-size: 12px;\">Save image</span></div>')
    field = (f'<div style=\"padding: 22px;\"><div style=\"display: flex; align-items: center; gap: 10px; min-height: 44px; border: 1px solid rgba(27,23,20,0.14); border-radius: 22px; padding: 0 16px;\">'
             f'<span style=\"font-size: 15px; color: {GHOST}; flex: 1;\">Message</span></div></div>')
    return frame(head_ + bub + react + field + '<div style=\"height: 120px;\"></div>')

def board05():"""),
    ("    rows = ['<div style=\"display: flex; gap: 60px; align-items: flex-start;\">' + pairs[0] + pairs[1] + '</div>',",
     """    pairs.append(pair('D7 &middot; THE ORDINARY ALTERNATIVE', 'Is a friend&rsquo;s photograph better received here than in a capable messaging app?',
             'Honest reading: for one photograph to one friend, a good message thread is sufficient, instant, and already installed; this comparison is not won on receiving alone. The difference appears in three places and only there: the author&rsquo;s control still means something afterwards, because a copy exists only where she permitted one and taking it back actually removes what she shared; it is found later by the person or the phrase rather than by scrolling a thread; and what she still shares and what you copied stay legibly different. Observe this pair with a real pair of friends before claiming more; a thread that already works is the thing to beat.',
             side('A &middot; THE EXACT-ORIGINAL READER &middot; REUSES 08.2', pasta_opened(), 'FINDABLE WHILE SHE SHARES IT &middot; ONE OPTIONAL COPY, UNTIL SHE TAKES IT BACK &middot; REPLY AND PRIVATE ASK SEPARATE &middot; FOUND LATER UNDER HER NAME (08.3)'),
             side('B &middot; A CAPABLE MESSAGE THREAD', message_thread(), 'ARRIVES AT ONCE, COSTS NOTHING, EVERYONE HAS IT &middot; SAVE IMAGE IS UNILATERAL AND PERMANENT; TAKING IT BACK DOES NOTHING &middot; FOUND AGAIN BY SCROLLING &middot; NO DIFFERENCE BETWEEN WHAT SHE STILL SHARES AND WHAT YOU COPIED')))
    rows = ['<div style=\"display: flex; gap: 60px; align-items: flex-start;\">' + pairs[0] + pairs[1] + '</div>',"""),
    ("            '<div style=\"display: flex; gap: 60px; align-items: flex-start; margin-top: 46px; padding-top: 34px; border-top: 1px solid rgba(27,23,20,0.12);\">' + pairs[4] + pairs[5] + '</div>']",
     "            '<div style=\"display: flex; gap: 60px; align-items: flex-start; margin-top: 46px; padding-top: 34px; border-top: 1px solid rgba(27,23,20,0.12);\">' + pairs[4] + pairs[5] + '</div>',\n            '<div style=\"display: flex; gap: 60px; align-items: flex-start; margin-top: 46px; padding-top: 34px; border-top: 1px solid rgba(27,23,20,0.12);\">' + pairs[6] + '</div>']"),
    ("'Twelve frames, one pair per decision, revised per &sect;14:",
     "'Thirteen frames, one pair per decision plus D7&rsquo;s ordinary control (its A side reused from 08.2, so one frame is added against a ceiling of twelve; recorded, not resolved), revised per &sect;14:"),
    # 07 · the second-pass record
    ("    sep9b = blk('SEPTEMBER 9 &middot; FRESH SIX-PROJECT REVIEW',",
     "    sep9c = blk('SEPTEMBER 9 &middot; SECOND-PASS STRATEGY ALIGNMENT', N('<b>The assets, and the gap.</b> Every photographic plate is a labelled stand-in, so the frames argue that a friend&rsquo;s original is the whole benefit while showing nothing worth looking at. The four that matter now name what they are missing on the plate itself: the pasta (Nora&rsquo;s phone, Thursday 7:40 pm), the table (Maya&rsquo;s, Saturday 8:25 pm), the Print Room (the one authored plate that exists, Places&rsquo; own illustration) and Dana&rsquo;s rag&ugrave;. Ordinary rights-cleared photographs are still needed and are their own scope; this pass contacts nobody and imports no library. '\n        '<b>The comparison that matters.</b> 05 D7 sets the exact-original reader against a capable ordinary message thread rather than a straw control, and the reading is honest: for one photograph to one friend the thread is sufficient and already installed. The difference is confined to three things: the author&rsquo;s control still means something afterwards, the material is found by person or phrase instead of by scrolling, and what she still shares stays distinct from what you copied. '\n        '<b>Each person&rsquo;s work.</b> Board 03 carries the account: the same evening by message and link, and as drawn, per person, with what actually moved and what never moves. What moved is duplicate explanation, context recovery and coordination. What did not move is choosing, cooking and writing to a friend, and it should not. The fixture hands Vesper the address, the buzzer, Sam&rsquo;s number and last month&rsquo;s photograph already assembled; that is not work Vesper absorbed, and the note under the table says so. '\n        '<b>Shared behaviour.</b> 03.5&rsquo;s two direct actions are deferred to Plans&rsquo; narrow amendment comparison so the two projects do not set independent defaults for one act; Nora keeps authorship and Send, and a sent proposal is not an adopted arrangement. The receiving wording is now Life 07.7 / 07.8&rsquo;s: opening keeps nothing, it stays findable while she shares it, and a copy is yours to reread until she takes it back, which is a different condition from the share expiring. '\n        '<b>Evidence corrected.</b> 03.8 read as if Maya opened the door at 7:32 in the branch where she cannot arrive before eight; she now arrives at eight, and the table photograph is 8:25. 02.1 and the ledger &sect;8.1 no longer diagnose the split sauce from a photograph or guarantee Saturday&rsquo;s batch.'))\n    sep9b = blk('SEPTEMBER 9 &middot; FRESH SIX-PROJECT REVIEW',"),
    ("    inner = comp + sep9b + sep9 + sep8 + closed + changed + work + dec +", "    inner = comp + sep9c + sep9b + sep9 + sep8 + closed + changed + work + dec +"),
    ("    ['The optional Keep on the exact-original reader (08.2) and its retention agreement', 'Proposed', 'Drawn as one plain door; the grant behind it is not adopted and is not implemented here'],",
     "    ['The optional Keep on the exact-original reader (08.2) and its source agreement', 'Proposed', 'Drawn as one plain door, worded with Life 07.7 / 07.8: a copy to reread until she takes it back. Share expiry and her taking it back are different conditions and only the first is survived; the agreement itself is not adopted'],\n    ['03.5&rsquo;s two direct actions on a proposed change', 'Deferred to the Plans owner', 'Plans leads the narrow amendment comparison (07 / 11); Social does not set a second default for the same act. Drawn as-is and marked'],\n    ['Photographic assets on every plate', 'Gap, labelled', 'One authored plate exists (the Print Room, from Places). The pasta, the table and the rag&ugrave; read &ldquo;asset not sourced&rdquo;; ordinary rights-cleared photographs are their own scope'],\n    ['Comparison budget: 13 frames on 05 against a ceiling of 12 (D7-B)', 'Unresolved scope discrepancy', 'D7 was asked for by the second-pass alignment and its A side is reused from 08.2, so one frame was added; the ceiling was not amended'],"),
    ("    ['Entity dd48304b &middot; 04.08 / 12.4',",
     "    ['Plans cd2e1f82 &middot; 07 / 11 &middot; the amendment', 'Social&rsquo;s &ldquo;Keep seven / Move to eight&rdquo; and Plans&rsquo; recommend-once-without-buttons rule cannot both be defaults for one act. Plans leads the narrow amendment comparison; Social&rsquo;s 03.5 is drawn with the actions and marked deferred. The distinction to preserve either way: an editable logistical proposal that reduces addressing and retyping, with the human keeping authorship and Send, is not invented intimate meaning, and a sent proposal is not an adopted arrangement or a response', 'Useful assistance without a second authority', 'The accepted seven-sentences rule is untouched by this project', 'The amendment decision itself', 'Deferred to the Plans owner and the founder'],\n    ['Life e72a2fd2 &middot; 07.7 / 07.8 &middot; the wording', 'Adopt Life&rsquo;s wording verbatim across the shared route: opening keeps nothing; it stays findable while she shares it; a copy is yours to reread until she takes it back; a kept place is yours and keeping the place does not keep her words. Share expiry and the author taking it back are different conditions and only the first is survived by a copy', 'One vocabulary for one behaviour across two roots', 'None; this replaces Social&rsquo;s looser &ldquo;yours after her share ends&rdquo;', 'The source agreement (proposed)', 'Agreed with the Life owner; agreement stays proposed'],\n    ['All roots &middot; photographic assets', 'Four frames carry the argument that a human original is the whole benefit and all four show labelled stand-ins. Ordinary, unpolished, rights-cleared photographs are needed for the pasta, the table and the rag&ugrave;; the Print Room has an authored plate already. Do not polish them into promotional imagery or present an invented photograph as a person&rsquo;s own', 'The value is the material, not the container', 'No change', 'Rights and sourcing, as its own scope', 'Flagged to the founder; not sourced here'],\n    ['Entity dd48304b &middot; 04.08 / 12.4',"),
])

# ───────────────────────────── gen_c6 · D7 needs the line constant in gen_c5 ─────────────────────────────
sub('gen_c5.py', [
    ("def frame(inner, tag_text=''):", "LINE_D7 = 'Second try. Thinking of Saturday, if anyone&rsquo;s around.'\ndef frame(inner, tag_text=''):"),
])
print('patched; misses:', len(MISS)); [print('  MISS', p, o) for p, o in MISS]
