"""September 8 consolidation (handoff §0, 2026-09-08): corrections to 03.6 / 03.7 variant / 04.6 / 05 D6-A / 06 / 07 / 00; board 08 registered."""
MISS = []
def sub(path, pairs):
    s = open(path).read()
    for old, new in pairs:
        n = s.count(old)
        if n == 1: s = s.replace(old, new)
        elif new in s: pass
        else: MISS.append((path, old[:90]))
    open(path, 'w').write(s)

# ───────────────────────────── gen_c3 · the adopted branch keeps the arrangement and his participation distinct ─────────────────────────────
sub('gen_c3.py', [
    ("    inner += gut('<div>' + row('Same place &middot; <span style=\"color: #6E6862;\">come at eight, or seven-thirty as planned</span>', mark='solid', color=GOLD)\n                 + row('Your nine still stands', mark='hollow')\n                 + row('Maya and Nora have the new time &middot; <span style=\"color: #6E6862;\">the dinner page updated for everyone</span>', mark='hollow', last=True) + '</div>', top=16)",
     "    inner += gut('<div>' + row('Dinner now from eight &middot; <span style=\"color: #6E6862;\">same place</span>', mark='solid', color=GOLD)\n                 + row('Nora still has your seven-thirty and nine &middot; <span style=\"color: #6E6862;\">until you say otherwise</span>', mark='hollow')\n                 + row('Maya and Nora have the new time &middot; <span style=\"color: #6E6862;\">the dinner page updated for everyone</span>', mark='hollow', last=True) + '</div>', top=16)"),
    ("{pill(\"Fine\")}{pill(\"Can&rsquo;t do eight\", False)}</div><div style=\"font-size: 12.5px; line-height: 17px; color: {MUTE}; margin-top: 10px;\">If you don&rsquo;t answer, she won&rsquo;t assume yes.</div>",
     "{pill(\"Eight works\")}{pill(\"Can&rsquo;t do eight\", False)}</div><div style=\"font-size: 12.5px; line-height: 17px; color: {MUTE}; margin-top: 10px;\">If you don&rsquo;t answer, she won&rsquo;t assume yes; she keeps your seven-thirty and nine.</div>"),
    # the 03.7 variant: the dinner's start is eight; his expected arrival depends on what he answered
    ("            f'<div style=\"{SERIF} font-weight: 600; font-size: 16px; line-height: 21px;\">Dinner from eight. You&rsquo;re expected around eight.</div>'\n            f'<div style=\"font-size: 12.5px; line-height: 17px; color: {INK2};\">Court Street, 3F, the buzzer says N &middot; nothing to bring &middot; leaving by nine is fine; she knows it&rsquo;s an hour &middot; Dana&rsquo;s rag&ugrave; &middot; one line if late.</div>'\n            f'<div class=\"fn\" style=\"color: {ANCHOR};\">WHO HAS THE NEW TIME: NORA (OWNER), MAYA (PROPOSED IT), SAM (AFFECTED, ANSWER PENDING UNTIL HE SAYS); DANA&rsquo;S CONTRIBUTION UNCHANGED &middot; HIS SILENCE IS NOT ACCEPTANCE OF EIGHT</div></div>')",
     "            f'<div style=\"{SERIF} font-weight: 600; font-size: 16px; line-height: 21px;\">Dinner from eight.</div>'\n            f'<div style=\"display: flex; flex-direction: column; gap: 4px; font-size: 12.5px; line-height: 17px; color: {INK2};\"><div><span class=\"fn\" style=\"color: {ANCHOR};\">IF HE ANSWERED &ldquo;EIGHT WORKS&rdquo; &middot; </span>You&rsquo;re expected around eight. Leaving by nine is fine; she knows it&rsquo;s an hour.</div>'\n            f'<div><span class=\"fn\" style=\"color: {ANCHOR};\">IF HE HAS NOT ANSWERED &middot; </span>Nora has you at seven-thirty, leaving by nine. Come when you said; the door is the same.</div></div>'\n            f'<div style=\"font-size: 12.5px; line-height: 17px; color: {INK2};\">Court Street, 3F, the buzzer says N &middot; nothing to bring &middot; Dana&rsquo;s rag&ugrave; &middot; one line if late.</div>'\n            f'<div class=\"fn\" style=\"color: {ANCHOR};\">THE DINNER&rsquo;S START IS EIGHT; HIS ACCEPTED ARRIVAL IS ONLY WHAT HE SAID &middot; WHO HAS THE NEW TIME: NORA (OWNER), MAYA (PROPOSED IT), SAM (AFFECTED); DANA UNCHANGED &middot; HIS SILENCE IS NOT ACCEPTANCE OF EIGHT</div>'\n            f'<div class=\"fn\" style=\"color: {OX};\">NORA&rsquo;S DINNER PAGE, ADOPTED BRANCH: SAM &middot; IN &middot; SEVEN-THIRTY, LEAVES BY NINE &middot; NO ANSWER ON EIGHT (PLANS 05 D3: WHO IS AFFECTED, WHO HAS ANSWERED)</div></div>')"),
    ("('SATURDAY 2:05 PM &middot; ADOPTED BRANCH, SEPARATE', 'WHAT CHANGED, TAILORED TO HIM', 'Nora applied eight; his row says what it means for nine; everyone at the dinner has the new time', 'DRAWN ONLY FOR THE ADOPTED BRANCH &middot; HIS ACCEPTANCE IS NOT INVENTED &middot; SILENCE IS NOT ACCEPTANCE &middot; CONTINUES TO THE 03.7 VARIANT')",
     "('SATURDAY 2:05 PM &middot; ADOPTED BRANCH, SEPARATE', 'WHAT CHANGED, TAILORED TO HIM', 'Nora applied eight; his seven-thirty and nine stay his until he says; everyone at the dinner has the new time', 'DRAWN ONLY FOR THE ADOPTED BRANCH &middot; THE DINNER&rsquo;S START AND HIS ACCEPTED ARRIVAL STAY DISTINCT &middot; SILENCE IS NOT ACCEPTANCE &middot; CONTINUES TO THE 03.7 VARIANT')"),
    ("         ('Sam', 'His link', 'Read', 'What changed and what it means for nine', 'Tailored to him; Nora and Maya have the new time too', 'Occasion (guest view)', '&mdash;', 'Answer, or not; then the eight arrival')",
     "         ('Sam', 'His link', 'Read', 'What changed; what Nora still has from him', 'Tailored to him; Nora and Maya have the new time too', 'Occasion (guest view)', 'Nora: his answer, or his unchanged seven-thirty and nine', 'Answer, or not; then the arrival for what he said')"),
    ("Each branch reaches its own arrival view: seven-thirty on 03.7, eight on the 03.7 variant.",
     "Each branch reaches its own arrival view: seven-thirty on 03.7; on the 03.7 variant the dinner&rsquo;s start is eight while his expected arrival is only what he answered, and if he answered nothing Nora keeps his seven-thirty and nine (Plans&rsquo; pending-participation treatment, 05 D3)."),
])

# ───────────────────────────── gen_c4 · what Sam actually holds ─────────────────────────────
sub('gen_c4.py', [
    ("<div style=\"font-size: 14px; line-height: 20px; color: {INK2}; margin-top: 8px;\">Maya&rsquo;s photograph, and what Nora wrote.</div>', top=14)\n    inner += gut('<div>' + row('Nora &middot; <span style=\"color: #6E6862;\">your host</span>', mark='av:N', last=True) + '</div>' + door('Stay in touch'), top=18)",
     "<div style=\"font-size: 14px; line-height: 20px; color: {INK2}; margin-top: 8px;\">Maya&rsquo;s photograph of the table. Saturday Sep 19, from seven, at Nora&rsquo;s.</div>', top=14)\n    inner += gut('<div>' + row('Maya &middot; <span style=\"color: #6E6862;\">her photograph, to you and Nora, as long as she leaves it</span>', mark='av:M') + row('Nora &middot; <span style=\"color: #6E6862;\">your host</span>', mark='av:N', last=True) + '</div>' + door('Stay in touch'), top=18)"),
    ("('LATER &middot; HIS LINK &middot; SOUGHT, NOT PROMPTED', 'STAY IN TOUCH?', 'He looks for it under Nora&rsquo;s name; share things and invite each other again; leaving it is fine',",
     "('LATER &middot; HIS LINK &middot; SOUGHT, NOT PROMPTED', 'STAY IN TOUCH?', 'His record holds Maya&rsquo;s photograph and the dinner&rsquo;s shared facts, nothing Nora wrote for herself; he looks under her name; leaving it is fine',"),
    ("('LATER &middot; LIFE &middot; PEOPLE', 'THE EVENING AS ONE RECORD', 'What each person added, theirs; her account, hers alone', 'RECOGNITION, NOT MAINTENANCE &middot; THE RECORD HOLDS ITS OWN MATERIAL; THE BOAT COUPLE ARE A SEPARATE RECORD (INSET)')",
     "('LATER &middot; LIFE &middot; PEOPLE', 'THE EVENING AS ONE RECORD', 'What each person added, theirs; her account, hers alone', 'RECOGNITION, NOT MAINTENANCE &middot; SAM&rsquo;S &ldquo;LEAVE BY NINE&rdquo; HERE IS HIS SUPPLIED PARTICIPATION, NOT A LEAK &middot; THE BOAT COUPLE ARE A SEPARATE RECORD (INSET)')"),
    ("('ONE SOURCE, THREE VIEWS', N('04.1 is Maya&rsquo;s gesture; 04.2 and 04.3 are Nora&rsquo;s and Sam&rsquo;s receipts of the same photograph; 04.4 and 04.5 find it again. No frame invents a second copy or a feed.')),",
     "('ONE SOURCE, THREE VIEWS', N('04.1 is Maya&rsquo;s gesture; 04.2 and 04.3 are Nora&rsquo;s and Sam&rsquo;s receipts of the same photograph; 04.4 and 04.5 find it again. No frame invents a second copy or a feed. What Sam holds later (04.6) is named exactly: Maya&rsquo;s photograph, for as long as she leaves it, and the dinner&rsquo;s shared facts; Nora&rsquo;s account on 04.4 stays hers, and his own &ldquo;leave by nine&rdquo; appearing in her record is his supplied participation, not a leak. Where he returns after a connection is board 08.')),"),
])

# ───────────────────────────── gen_c5 · D6-A, routes, actions, branches, deltas, the September 8 block ─────────────────────────────
sub('gen_c5.py', [
    ("Maya&rsquo;s photograph, here as long as she leaves it, and what Nora wrote. The evening&rsquo;s details closed on Sunday.",
     "Maya&rsquo;s photograph of the table, here as long as she leaves it, and the dinner&rsquo;s shared facts: Saturday Sep 19, from seven, at Nora&rsquo;s. The evening&rsquo;s details closed on Sunday. Nothing Nora wrote for herself."),
    ("    'MAYA': [('02.7', 'Her share, later', 'PLACES'), ('03.4', 'Her suggestion lands', 'OCCASION'), ('04.1', 'The table photograph', 'OCCASION'), ('04.9', 'Takes the note back', 'LIFE')],",
     "    'MAYA': [('02.2', 'Share the Print Room', 'PLACES'), ('02.7', 'Her share, later', 'PLACES'), ('03.4 &middot; hers', 'The dinner page, her view: proposing eight (not drawn)', 'OCCASION'), ('04.1', 'The table photograph', 'OCCASION'), ('02.7', 'Take it back (her action; 04.9 is Nora&rsquo;s result)', 'PLACES'), ('08.1 &rarr; 08.3', 'Nora&rsquo;s pasta: receive, open, find again', 'HOME / LIFE')],"),
    ("    'SAM': [('03.2', 'The invitation', 'LINK'), ('03.6', 'Adopted branch, if any', 'LINK'), ('03.7', 'Arrival', 'LINK'), ('04.3', 'The photo, later', 'LINK'), ('04.6', 'Stay in touch, if sought', 'LINK')],",
     "    'SAM': [('03.2', 'The invitation', 'LINK'), ('03.6', 'Adopted branch, if any', 'LINK'), ('03.7', 'Arrival, for what he said', 'LINK'), ('04.3', 'The photo, later', 'LINK'), ('04.6', 'Stay in touch, if sought', 'LINK'), ('08.5', 'Where he returns', 'LINK')],"),
    ("    ['Accept a scoped change', '03.5 &rarr; 03.6 (branch)', 'Seven stands; or, adopted, the owner&rsquo;s revision reaches only Sam', 'Home unchanged except the one row'],",
     "    ['Accept a scoped change', '03.5 &rarr; 03.6 (branch) &rarr; 03.7 variant', 'Seven stands; or, adopted, the dinner&rsquo;s start is eight for Nora, Maya and Sam, each in their own view; Sam&rsquo;s seven-thirty and nine stay his until he answers', 'Home unchanged except the one row; his row shows what he has answered'],"),
    ("    ['Withdraw', '04.9', 'A2 and its derivatives gone; the rest as it was', 'No new contact'],",
     "    ['Withdraw', '02.7 (Maya&rsquo;s Take it back) &rarr; 04.9 (Nora&rsquo;s result)', 'A2 and its derivatives gone; the rest as it was', 'No new contact'],\n    ['Receive something without a place', '08.1 &rarr; 08.2 &rarr; 08.3', 'Nora&rsquo;s pasta and line arrive once on Home; the exact source opens; Life &middot; People holds it', 'Enjoy it and leave; Reply, or not'],\n    ['Share to a connected guest', '08.4 &rarr; 08.5', 'One thing to Maya and Sam; Sam by text to his verified number; his link says From Nora', 'Sent once; he can leave, ask for fewer, or stop'],"),
    ("        ['The RSVP', '03.2 &rarr; 03.4', 'Provisional on the bare link; confirmed by the code that unlocks the address; if never confirmed, the host never sees a confirmed &ldquo;in&rdquo;'],",
     "        ['The RSVP', '03.2 &rarr; 03.4', 'Provisional on the bare link; confirmed by the code that unlocks the address; if never confirmed, the host never sees a confirmed &ldquo;in&rdquo;'],\n        ['Participation versus arrangement', '03.6 &rarr; 03.7 variant', 'The dinner&rsquo;s start (eight) and Sam&rsquo;s accepted arrival are different facts; his row keeps seven-thirty and nine until he answers; hiding, muting or blocking a person never changes who is attending (Home 10 delta)'],"),
    ("                 'Linked frames, one route per participant, with an action &rarr; result &rarr; return map. The founder can follow Nora, Maya, Dana or Sam through boards 02&ndash;04 without reading another person&rsquo;s private context. Branches are labelled so accepted and unadopted states never coexist in one scenario.'",
     "                 'Linked frames, one route per participant, with an action &rarr; result &rarr; return map. The founder can follow Nora, Maya, Dana or Sam through boards 02&ndash;04 and 08 without reading another person&rsquo;s private context. Each route points only at that person&rsquo;s own views; a view not drawn is named as such. Branches are labelled so accepted and unadopted states never coexist in one scenario.'"),
    # D6 recommendation: attention controls never change attendance
    ("occasion-bounded contact stays valid and complete", "occasion-bounded contact stays valid and complete; hiding, muting or blocking a person never changes who attended or is attending"),
    # DELTAS: two new rows appended before the Chat row
    ("    ['Chat', 'A send to others crosses an audience boundary:", "    ['Home 42876b8c &middot; 10 (block state)', 'Blocking or hiding a participant must not change the gathering&rsquo;s count or attendance (10&rsquo;s block frame moves Alex&rsquo;s evening from four going to three with no attendance event); a viewer-relative count must not read as the gathering&rsquo;s size; keep shared truth and the viewer&rsquo;s own hiding separate', 'Safe shared truth; hiding someone does not remove them', 'Attendance is Occasion truth; mute, block, report are the viewer&rsquo;s', 'Seam 5 per-recipient readback', 'Delta to the Home owner; dependency marked'],\n    ['Home 42876b8c / Life e72a2fd2 &middot; casual non-spatial placement', 'A friend&rsquo;s original without a place arrives once in Home&rsquo;s addressed region when the share&rsquo;s audience includes you (08.1, two-item rule), opens to Life&rsquo;s exact-source reader (08.2), and is found again under the person (08.3); no pin, no feed, no social root; the spatial-social split stands for place-bound shares', 'Casual receiving without forcing a location', 'Accepted Home social split preserved; placement is a named proposal', 'Friends audience (proposal); seam 7 refind over a photo', 'Proposal to the Home and Life owners'],\n    ['Chat', 'A send to others crosses an audience boundary:"),
    # STATUS: one new row
    ("    ['Block, mute, disconnect, report', 'Proposed',", "    ['Casual non-spatial placement (08.1&ndash;08.3): Home addressed region as arrival, Life &middot; People as the pull route', 'Proposed', 'A named proposal for the Home and Life owners; the alternative (Places &middot; From friends without a pin) is fair and unadopted'],\n    ['Block, mute, disconnect, report', 'Proposed',"),
    # WALK: two rows for the continuations
    ("WALK = [", "WALK = [\n    ['Maya receives something of Nora&rsquo;s that has no place, opens it, finds it again', '08.1 &rarr; 08.2 &rarr; 08.3', 'Works: it arrives once, opens to the exact source, lives under the person; no pin, no occasion', 'Where it arrives is a placement choice, not a settled rule', 'Proposed (07 root deltas); alternative named'],\n    ['Sam, connected, receives one more thing and knows where he is and how to have fewer', '08.4 &rarr; 08.5', 'Works: his link says From Nora; what he already had is beside it; Fewer and Stop are his', 'A verified non-member principal is still a dependency', 'Guest proposal &sect;3 unchanged'],"),
    # the September 8 block on 07, before the §15 close
    ("    closed = blk('WHAT CHANGED AT THE &sect;15 CLOSE &middot; A, B, C',",
     "    sep8 = blk('SEPTEMBER 8 CONSOLIDATION &middot; CORRECTED AND CONTINUED', N('<b>Corrected.</b> 03.6 and the 03.7 variant now keep the dinner&rsquo;s start (eight) and Sam&rsquo;s accepted arrival apart: his row keeps seven-thirty and nine until he answers, the variant shows the arrival for each answer state, and Nora&rsquo;s dinner page carries Plans&rsquo; who-is-affected, who-has-answered treatment; nobody&rsquo;s silence becomes acceptance. 06&rsquo;s routes point only at each person&rsquo;s own views (Maya&rsquo;s proposal view is named as not drawn; her withdrawal is her Take it back on 02.7, with 04.9 as Nora&rsquo;s result) and the action table no longer says the adopted change reaches only Sam. 04.6 and D6-A name what Sam actually holds: Maya&rsquo;s photograph, for as long as she leaves it, and the dinner&rsquo;s shared facts; nothing Nora wrote for herself; her seeing his &ldquo;leave by nine&rdquo; in her own record is his supplied participation, not a leak. '\n        '<b>Continued.</b> Board 08 adds five slots beyond the twenty-four: non-spatial receiving (08.1&ndash;08.3, from 05 D1-A through Life&rsquo;s exact-source reader to Life &middot; People) and where Sam returns after both chose connection (08.4&ndash;08.5). '\n        '<b>Owner deltas.</b> Home 10&rsquo;s block state must not change attendance or count; casual non-spatial placement is a named proposal (rows below). <b>Not done, by assignment:</b> busy-social scale, extra one-friend variants, Dana receiving something through these people, acknowledgment experiments. Nothing here is user validation, a real send, an enabled feature or a verified guest principal.'))\n    closed = blk('WHAT CHANGED AT THE &sect;15 CLOSE &middot; A, B, C',"),
    ("    inner = comp + closed + changed + dec +", "    inner = comp + sep8 + closed + changed + dec +"),
    ("comp = blk('THE RECOMMENDED COMPOSITION &middot; CLOSED PER &sect;15',", "comp = blk('THE RECOMMENDED COMPOSITION &middot; SEPTEMBER 8',"),
])

# ───────────────────────────── gen_se · index, budget, stamp ─────────────────────────────
sub('gen_se.py', [
    ("STAMP = 'DESIGN ROUND CLOSED PER HANDOFF &sect;15 &middot; 2026-09-07'", "STAMP = 'SEPTEMBER 8 CONSOLIDATION &middot; CORRECTED AND CONTINUED &middot; 2026-09-09'"),
    ("    ['07 &middot; Decisions and return to the app',", "    ['08 &middot; Continuations', 'Five slots beyond the twenty-four: a friend&rsquo;s original without a place, received, opened and found again (08.1&ndash;08.3); where Sam returns after both chose connection (08.4&ndash;08.5); the placement proposal', 'NEW &middot; SEPTEMBER 8 ASSIGNMENT &middot; PROPOSED'],\n    ['07 &middot; Decisions and return to the app',"),
    ("If coverage still does not fit, the exact tradeoff is reported on board 01, not hidden.", "If coverage still does not fit, the exact tradeoff is reported on board 01, not hidden. September 8: five continuation slots on board 08, named by the consolidation assignment, drawn on existing families; no other frame was added."),
])
s = open('gen_se.py').read()
for a, b in [("'CLOSED &sect;15: both dinner branches reach their own arrival view; a link-holder answer is provisional until the address code'", "'SEPTEMBER 8: the dinner&rsquo;s start and Sam&rsquo;s accepted arrival kept distinct on 03.6 and the 03.7 variant; provisional RSVP unchanged'"),
             ("'CLOSED &sect;15: 04.3 under branch V; 04.8 carries forward place and start only; the boat is its own record; illustrative openings'", "'SEPTEMBER 8: 04.6 names what Sam holds (Maya&rsquo;s photograph, the dinner&rsquo;s shared facts); Nora&rsquo;s account stays hers'"),
             ("'CLOSED &sect;15: fair comparisons (same facts, same grants); D4 arrival facts restated per branch'", "'SEPTEMBER 8: D6-A names the shared original; D1-A is the sender state for board 08'"),
             ("'CLOSED &sect;15: the two arrival routes and the provisional RSVP in the branch table'", "'SEPTEMBER 8: routes point only at each person&rsquo;s own views; participation-versus-arrangement branch; board 08 linked'"),
             ("'CLOSED &sect;15: A, B, C recorded; obsolete statements archived as history'", "'SEPTEMBER 8: corrections, continuations and owner deltas recorded above the &sect;15 close'")]:
    if a in s: s = s.replace(a, b)
    else: MISS.append(('gen_se.py', a[:80]))
open('gen_se.py', 'w').write(s)

# ───────────────────────────── measure_c2 · board 08 ─────────────────────────────
sub('measure_c2.py', [
    ("'07 - Decisions and return to the app':1820}", "'07 - Decisions and return to the app':1820,'08 - Continuations':2260}"),
])
s = open('measure_c2.py').read().replace("('gen_c2.py','gen_c3.py','gen_c4.py','gen_c5.py')", "('gen_c2.py','gen_c3.py','gen_c4.py','gen_c5.py','gen_c6.py')")
open('measure_c2.py', 'w').write(s)
print('patched; misses:', len(MISS)); [print('  MISS', p, o) for p, o in MISS]
