"""September 9 selected direction and residual corrections (handoff §0, 2026-09-10 00:07): D7's evidence matched, 03.5's prepared proposal selected, redundant non-use narration removed."""
MISS = []
def sub(path, pairs):
    s = open(path).read()
    for old, new in pairs:
        n = s.count(old)
        if n == 1: s = s.replace(old, new)
        elif new in s: pass
        else: MISS.append((path, old[:90]))
    open(path, 'w').write(s)

# ───────────────────────────── gen_c2 · redundant non-use narration out ─────────────────────────────
sub('gen_c2.py', [
    ("""{src("The gallery&rsquo;s own notes &middot; not made from Maya&rsquo;s words")}""", """{src("The gallery&rsquo;s own notes")}"""),
    ("('THE PRINT ROOM, OPENED', 'THREE THINGS KEPT APART', 'Her words; the listing; the gallery&rsquo;s notes', 'ORIGINAL &middot; DATED WORLD INFORMATION IN THE UNVERIFIED REGISTER &middot; A READING NOT MADE FROM HER WORDS')",
     "('THE PRINT ROOM, OPENED', 'THREE THINGS KEPT APART', 'Her words; the listing; the gallery&rsquo;s notes', 'ORIGINAL FIRST &middot; DATED WORLD INFORMATION IN THE UNVERIFIED REGISTER &middot; EACH LINE CARRIES ITS OWN SOURCE, SO NO SENTENCE HAS TO SAY WHAT IT IS NOT &middot; DISPLAY IS NOT RETENTION AND NOT AI PERMISSION')"),
])

# ───────────────────────────── gen_se · A1′ row ─────────────────────────────
sub('gen_se.py', [
    ("'Her line; the listing in the unverified register; a reading marked not made from her words'", "'Her line; the listing in the unverified register; a reading attributed to the gallery'"),
    ("STAMP = 'SEPTEMBER 9 &middot; SELECTION AND CORRECTION &middot; 2026-09-09'", "STAMP = 'SELECTED DIRECTION &middot; RESIDUAL CORRECTIONS &middot; 2026-09-10'"),
    ("'SELECTION: the Print Room plates now say they stand in for Maya&rsquo;s photograph; 02.2&ndash;02.7 is the first half of the one human payoff'",
     "'SELECTED: original-first casual receiving is an exemplar; each line carries its own source, so the non-use narration is gone'"),
    ("'SELECTION: 03.5&rsquo;s assistance is UNSELECTED pending Plans, with one prepared action instead of two equivalent buttons; the work account stands'",
     "'SELECTED: 03.5 prepares one message to Maya and ends in Send proposal; dinner stays at seven; the guest-hospitality sequence 03.7&ndash;03.8 is an exemplar'"),
    ("'SELECTION: D7 rebuilt on the same material and people, around what the share makes possible rather than custody; 13 frames = UNRESOLVED SCOPE DISCREPANCY'",
     "'CORRECTED: D7&rsquo;s inputs matched, both sides given A1, B2b and Nora&rsquo;s own constraint; 13 frames = UNRESOLVED SCOPE DISCREPANCY'"),
    ("'SELECTION: the one human payoff end to end, the bounded asset gap, Plans&rsquo; unselected assistance, Entity&rsquo;s received route, both budget discrepancies'",
     "'SELECTED DIRECTION: the two exemplars, the prepared-message effects received from the decision, D7&rsquo;s matched inputs, the bounded asset gap, both budget discrepancies'"),
])

# ───────────────────────────── gen_c3 · 03.5, the selected proposal ─────────────────────────────
sub('gen_c3.py', [
    ("""    ask = card(f'<div class="kick" style="color: {GOLDD};">MAYA &middot; 1:40 PM</div>' + title('Maya asks: eight instead of seven?', 20, 25, 600)
               + f'<div style="{SERIF} font-size: 15px; line-height: 21px; color: {INK2}; margin-top: 8px;">Sam has said he has to leave by nine. Keeping seven keeps his dinner whole; Maya could come at eight and eat with you. Moving to eight gives Sam an hour.</div>'
               + f'<div style="display: flex; align-items: center; gap: 12px; margin-top: 14px;">{pill("Move to eight&hellip;", False)}</div>'
               + f'<div style="font-size: 13px; line-height: 18px; color: {MUTE}; margin-top: 10px;">Prepares a message to Maya and Sam. You read it and send it.<br>Or leave it: seven stands.</div>')""",
     """    draft = (f'<div style="margin-top: 14px; border: 1px dashed rgba(27,23,20,0.30); border-radius: 10px; padding: 12px 14px;">'
             f'<div class="kickm" style="margin-bottom: 6px;">PREPARED &middot; NOT SENT</div>'
             f'<div style="font-size: 13px; color: {MUTE}; margin-bottom: 6px;">To Maya</div>'
             f'<div style="{SERIF} font-size: 16px; line-height: 23px; color: {INK};">We&rsquo;ll start at seven. Would joining at eight work for you?</div>'
             f'<div style="display: flex; align-items: center; gap: 14px; margin-top: 12px;">{pill("Send proposal")}{door("Edit", MUTE)}</div>'
             f'<div style="font-size: 13px; line-height: 18px; color: {MUTE}; margin-top: 10px;">Sending asks Maya. It does not move dinner or answer for her.</div></div>')
    ask = card(f'<div class="kick" style="color: {GOLDD};">MAYA &middot; 1:40 PM</div>' + title('Maya asks: eight instead of seven?', 20, 25, 600)
               + f'<div style="{SERIF} font-size: 15px; line-height: 21px; color: {INK2}; margin-top: 8px;">Dinner starts at seven and the rest of the evening is unchanged. The useful question is whether joining at eight works for her.</div>'
               + f'<div style="display: flex; align-items: center; gap: 12px; margin-top: 14px;">{door("Ask Maya about joining at eight&hellip;")}</div>'
               + draft
               + f'<div style="font-size: 13px; line-height: 18px; color: {MUTE}; margin-top: 10px;">Leave it: nothing is sent and seven still stands.</div>')"""),
    ("('SATURDAY 1:44 PM &middot; FULL SCROLL &middot; UNSELECTED, PENDING PLANS', 'THE CHANGE, AND THE AFTERNOON', 'Maya&rsquo;s eight with its cost; the &sect;8.2 afternoon; the rest of Home intact',",
     "('SATURDAY 1:44 PM &middot; FULL SCROLL', 'THE PROPOSAL, AND THE AFTERNOON', 'One door prepares one message to Maya; dinner stays at seven; the &sect;8.2 afternoon; the rest of Home intact',"),
    ("'UNSELECTED, PENDING PLANS&rsquo; NARROW PREPARED-PROPOSAL COMPARISON (07 / 11) &middot; THREE DISTINCT THINGS, NOT TWO EQUIVALENT BUTTONS: PREPARING A MESSAGE, NORA READING AND SENDING IT, AND THE ARRANGEMENT ACTUALLY MOVING &middot; LEAVING IT IS NOT A BUTTON &middot; NOTHING HERE IS A SECOND DEFAULT FOR AN ACT PLANS OWNS'",
     "'SENTENCE 6 AS AMENDED (2026-09-09): ONE DOOR MAY OPEN AN ADDRESSED, EDITABLE MESSAGE; THE PERSON SENDS &middot; PREPARE &rarr; EDITABLE MESSAGE &rarr; SEND PROPOSAL, WHICH SENDS WORDS ONLY &middot; SAM&rsquo;S DEPARTURE IS NOT IN THE MESSAGE, HE IS NOT ASKED AGAIN, AND AN UNCHANGED DINNER IS ANNOUNCED TO NOBODY &middot; IF NORA INSTEAD INSTRUCTS A CHANGE, THAT IS PLANS&rsquo; D3 PREVIEW &rarr; UPDATE &amp; SEND, NOT AN EQUAL BUTTON BESIDE THIS ONE'"),
    ("('THE CHANGE, TWO BRANCHES', N('03.5 is the recommended route and its assistance is <b>unselected</b> until Plans resolves the narrow prepared-proposal comparison (07 / 11). It no longer offers two equivalent buttons. Preparing a message, Nora reading and sending it, and the arrangement actually moving are three different things: &ldquo;Move to eight&hellip;&rdquo; only prepares, Nora sends, and leaving it is not a button at all;",
     "('THE CHANGE, TWO BRANCHES', N('03.5 takes the amended sentence 6 (September 9): one door opens an addressed, editable message and the person sends it. The question it prepares is the useful one, since dinner still starts at seven and Sam&rsquo;s evening is unchanged: <i>We&rsquo;ll start at seven. Would joining at eight work for you?</i>, to Maya, ending in Send proposal. Sending asks her; it does not move dinner, record her answer, ask Sam again, or announce anything to anyone else, and his departure time is not in it. Leaving it sends nothing. If Nora instead instructs a change outright, that is Plans&rsquo; own preview and Update &amp; send, not a button beside this one;"),
])

# ───────────────────────────── gen_c5 · D7, matched evidence ─────────────────────────────
sub('gen_c5.py', [
    ("LINE_D7 = 'The side room was my favorite. Go on a weekday, it was empty.'",
     "LINE_D7 = 'The side room was my favorite. Go on a weekday, it was empty.'\nLINE_D7B = 'If you go before dinner, the side room empties after four and the shop shuts at five.'"),
    ("    field = (f'<div style=\"padding: 22px;\">",
     "    bub2 = (f'<div style=\"padding: 14px 22px 0 22px;\"><div class=\"kickm\" style=\"color: {MUTE};\">FRIDAY</div></div>'\n            f'<div style=\"display: flex; justify-content: flex-start; padding: 0 22px; margin-top: 8px;\"><div style=\"max-width: 280px; background: {CARD}; border-radius: 18px; padding: 10px 14px; font-size: 15px; line-height: 21px;\">{LINE_D7B}</div></div>'\n            f'<div style=\"padding: 6px 22px 0 34px;\"><span class=\"fn\" style=\"color: {MUTE};\">DELIVERED 6:12 PM</span></div>')\n    field = (f'<div style=\"padding: 22px;\">"),
    ("    return frame(head_ + bub + react + field + '<div style=\"height: 120px;\"></div>')",
     "    return frame(head_ + f'<div style=\"padding: 14px 22px 0 22px;\"><div class=\"kickm\" style=\"color: {MUTE};\">THURSDAY</div></div>' + bub + react + bub2 + field)"),
    ("'The same photograph and the same two people. What can follow from it here that cannot follow from a good message thread?',\n             'Honest reading: the thread delivers Maya&rsquo;s photograph and her line perfectly well, at once, to a person who already has the app. Receiving is not the difference, and neither is custody. The difference is what the share can turn into without becoming a task. On Saturday, Nora&rsquo;s only free stretch is the afternoon; the same words that arrived on Thursday are what makes four o&rsquo;clock worth using, and the possibility appears once, with its cost stated, and can be left (03.5). In the thread she would have to remember the name, look up the hours, and decide alone; nothing there knows about her afternoon. Vesper does not need to win every share: most end at &ldquo;enjoyed it&rdquo;, which is a complete ending on both sides. This is the case worth having, and it should be observed with two real friends before it is claimed.',",
     "'The same two people and, on both sides, the same three inputs. What can follow that a capable thread cannot do?',\n             'Matched evidence, stated exactly. The later case does not run on Thursday&rsquo;s note. It needs three things: A1, Maya&rsquo;s photograph and her weekday line, shared to friends on Thursday; B2b, a second and separate contribution from Maya on Friday, addressed to Nora as the evening&rsquo;s owner, saying the side room empties after four and the shop shuts at five; and a fact Nora supplied herself, that she has to be home by six to start the pasta. Both sides get all three, plus the gallery&rsquo;s listed hours, the walk time, ordinary search and the link Maya already sent. Vesper is credited with nothing the thread was denied and with no retyping the thread would not have to do. Honest reading: receiving is not the difference and neither is custody. What is left is that on Saturday the two contributions and her own constraint compose once, at the moment the afternoon is usable, with the cost said plainly and the option to leave it (03.5); in the thread she reads back two messages from two days, checks the hours herself, and works out whether four to 5:10 fits before six. That is a real difference and a small one, and it costs Maya a second contribution. Vesper does not need to win every share: most end at &ldquo;enjoyed it&rdquo;, complete on both sides.',"),
    ("side('A &middot; HER SHARE, OPENED &middot; REUSES 02.4 &rarr; 03.5', opened(), 'HER WORDS, THE LISTING AND THE GALLERY&rsquo;S NOTES STAY APART &middot; REPLY IS OPTIONAL, NOTHING IS OWED &middot; ON SATURDAY HER OWN FREE STRETCH MAKES FOUR O&rsquo;CLOCK USABLE, WITH THE COST SAID ONCE (03.5) &middot; SHE GOES, OR SHE LEAVES IT, AND MAYA IS TOLD NEITHER')",
     "side('A &middot; A1 RECEIVED &middot; REUSES 02.4; THE AFTERNOON IS 03.5', opened(), 'THURSDAY: A1, HER WORDS AND THE LISTING AND THE GALLERY&rsquo;S NOTES APART; REPLY OPTIONAL, NOTHING OWED &middot; FRIDAY: B2b ARRIVES SEPARATELY, A SECOND CONTRIBUTION FROM MAYA, NOT THIS ONE &middot; SATURDAY: B2b AND NORA&rsquo;S OWN &ldquo;HOME BY SIX&rdquo; COMPOSE THE AFTERNOON ONCE, WITH ITS COST (03.5) &middot; SHE GOES OR LEAVES IT, AND MAYA IS TOLD NEITHER')"),
    ("side('B &middot; A CAPABLE MESSAGE THREAD', message_thread(), 'ARRIVES AT ONCE, COSTS NOTHING, EVERYONE HAS IT &middot; REPLY OR NOT &middot; ON SATURDAY SHE MUST REMEMBER THE NAME, LOOK UP THE HOURS AND DECIDE ALONE &middot; THE THREAD DOES NOT KNOW SHE HAS AN AFTERNOON &middot; SAVE IMAGE IS UNILATERAL AND PERMANENT')",
     "side('B &middot; A CAPABLE MESSAGE THREAD &middot; THE SAME THREE INPUTS', message_thread(), 'BOTH OF MAYA&rsquo;S MESSAGES ARE HERE, THURSDAY AND FRIDAY &middot; ORDINARY SEARCH, THE LINK SHE SENT, THE ADDRESS ALREADY IN THE THREAD &middot; ARRIVES AT ONCE, COSTS NOTHING, EVERYONE HAS IT &middot; ON SATURDAY SHE READS BACK TWO DAYS, CHECKS THE HOURS AND FITS IT AGAINST SIX HERSELF &middot; NOTHING HERE KNOWS SHE HAS AN AFTERNOON')"),
    # 07 · the selected direction
    ("    sep9c = blk('SEPTEMBER 9 &middot; SECOND-PASS STRATEGY ALIGNMENT',",
     "    selected = blk('SELECTED DIRECTION &middot; SEPTEMBER 9 DECISION, RECEIVED', N('<b>The two exemplars.</b> Original-first casual receiving (02) and the existing guest-hospitality and asymmetric-photograph sequence (03.7 &rarr; 03.8 &rarr; 04.1&ndash;04.3) are the selected social exemplars. Receiving and leaving is complete value; the afternoon is optional. No further payoff sequence and no mandatory gathering were invented. '\n        '<b>The prepared-message door, as amended.</b> Sentence 6 now allows one door to open an addressed, editable message when acting on a recommendation means sending words to people already involved; the person sends, and it can be turned off. 03.5 takes the proposal route: one door, &ldquo;Ask Maya about joining at eight&hellip;&rdquo;, a prepared message to Maya reading <i>We&rsquo;ll start at seven. Would joining at eight work for you?</i>, ending in Send proposal. Effects, exactly: it sends words only; dinner does not move; Maya&rsquo;s answer is not recorded; Sam is not asked again and his departure time is not in the message; nobody is told about an unchanged dinner; leaving it sends nothing. The owner-instructed route (Plans&rsquo; preview and Update &amp; send) stays available when Nora actually instructs a change, and is not a second button beside this one. '\n        '<b>D7&rsquo;s evidence, matched.</b> The comparison no longer implies Thursday&rsquo;s note pays for Saturday&rsquo;s afternoon. Its inputs are named: A1 on Thursday, B2b as a separate second contribution from Maya on Friday, and Nora&rsquo;s own &ldquo;home by six&rdquo;. Both sides get all three plus listed hours, the walk time, ordinary search and the link Maya sent; the thread is denied nothing. What remains is composition at the usable moment, and it costs Maya a second contribution. '\n        '<b>Copy.</b> Sentences that explained what a line was not made from are gone; every line already carries its own source. Display remains neither retention nor permission to use material, and no private use is ever reported to the sender.'))\n    sep9c = blk('SEPTEMBER 9 &middot; SECOND-PASS STRATEGY ALIGNMENT',"),
    ("    inner = comp + sep9c + sep9b +", "    inner = comp + selected + sep9c + sep9b +"),
    ("    ['03.5&rsquo;s assistance on a proposed change', 'Unselected, pending Plans', 'The two equivalent buttons are gone. One action prepares a message; Nora reads and sends it; the arrangement moves only then; leaving it is not a button. Plans owns the narrow prepared-proposal comparison (07 / 11) and Social selects nothing until it resolves'],",
     "    ['03.5&rsquo;s prepared proposal', 'Selected, per the September 9 decision', 'One door prepares one addressed, editable message to Maya and ends in Send proposal, which sends words only. Dinner stays at seven; her answer is not recorded; Sam is neither asked again nor quoted; leaving it sends nothing. The owner-instructed Update &amp; send route is Plans&rsquo;, available on an explicit instruction and not a button beside this one'],"),
])
print('patched; misses:', len(MISS)); [print('  MISS', p, o) for p, o in MISS]
