"""Apply handoff §15 (post-revision reconciliation) to the generators."""
MISS = []
def sub(path, pairs):
    s = open(path).read()
    for old, new in pairs:
        n = s.count(old)
        if n == 1: s = s.replace(old, new)
        elif new in s: pass
        else: MISS.append((path, old[:90]))
    open(path, 'w').write(s)
def replace_func(path, name, new_src):
    s = open(path).read()
    i = s.index(f'\ndef {name}(')
    j = s.find('\n# ───', i + 1); k = s.find('\ndef ', i + 1)
    j = min(x for x in (j, k) if x != -1)
    s = s[:i] + '\n' + new_src.rstrip('\n') + '\n' + s[j:]
    open(path, 'w').write(s)

# ───────────────────────────── gen_c3 · link footer, guest branch V, 03.1 preview, 03.5 stamps ─────────────────────────────
sub('gen_c3.py', [
    ("<div style=\"padding: 18px 22px 22px 22px; border-top: 1px solid rgba(27,23,20,0.06);\"><div class=\"fn\" style=\"color: {GHOST};\">FROM NORA &middot; THIS LINK IS YOURS &middot; IT SHOWS YOU THIS AND NOTHING ELSE OF HERS</div></div></div>'",
     "<div style=\"padding: 14px 22px 18px 22px; border-top: 1px solid rgba(27,23,20,0.06);\"><div class=\"fn\" style=\"color: {GHOST};\">YOUR LINK &middot; FROM NORA</div></div></div>'"),
    ("['Saturday, dinner from seven; come at seven-thirty', 'Carroll Gardens &middot; the address comes with his answer', 'Nothing to bring', 'By text, to the number you typed'], 'HE SEES WHEN, WHERE, WHO &middot; NOTHING ELSE OF YOURS &middot; NO CONTACTS SCANNED')",
     "['Saturday, dinner from seven; come at seven-thirty', 'Carroll Gardens &middot; the exact address after he confirms this number', 'Nothing to bring', 'By text, to the number you typed'], 'HE SEES WHEN, WHERE, WHO &middot; NOTHING ELSE OF YOURS &middot; NO CONTACTS SCANNED')"),
    ("                 + row('Carroll Gardens, near Court Street &middot; <span style=\"color: #6E6862;\">the exact address comes with your answer</span>', mark='hollow')",
     "                 + row('Carroll Gardens, near Court Street &middot; <span style=\"color: #6E6862;\">the exact address after a one-time code to this number</span>', mark='hollow')"),
    ("<div style=\"font-size: 12.5px; line-height: 17px; color: {MUTE}; margin-top: 10px;\">Nora sees your answer and nothing else about you. No reason needed either way.</div>", "<div style=\"font-size: 12.5px; line-height: 17px; color: {MUTE}; margin-top: 10px;\">Nora sees your answer. No reason needed either way.</div>"),
    ("    inner = guestbar('SATURDAY 7:10 PM &middot; TONIGHT')", "    inner = guestbar('SATURDAY 7:10 PM &middot; TONIGHT &middot; VERIFIED')"),
    ("('COPY OF HOME 02 &middot; 09-05', 'BRANCH &middot; RECOMMENDED &middot; UNADOPTED', 'SEVEN SENTENCES: RECOMMEND ONCE, NO BUTTONS')", "('COPY OF HOME 02 &middot; 09-05', 'BRANCH &middot; RECOMMENDED &middot; UNADOPTED', 'RECOMMEND ONCE; A DIRECT ACTION; LEAVING IT IS THE UNADOPTED ENDING')"),
    ("('R7 C2 &middot; ADAPTED', 'DEPENDENCY &middot; A DINNER-SCOPED LINK; A GUEST WHO IS NOT A MEMBER', 'B2C AUTHORED')", "('R7 C2 &middot; ADAPTED', 'PROPOSED BRANCH V: VERIFIED AT THE FIRST SENSITIVE BOUNDARY (THE ADDRESS)', 'DEPENDENCY &middot; GUEST IDENTITY AND DELIVERY')"),
    ("('NEW &middot; NO SIBLING DRAWS THIS', 'D4 &middot; THE ARRIVAL FRAME', 'B2D ARRIVAL UPDATE IS THE ONE DOOR')", "('NEW &middot; NO SIBLING DRAWS THIS', 'D4 &middot; THE ARRIVAL FRAME &middot; BRANCH V: HIS NUMBER CONFIRMED, SO THE DOOR FACTS SHOW', 'B2D ARRIVAL UPDATE IS THE ONE DOOR')"),
    ("('FRIDAY &middot; A LINK, NO APP', 'GUEST VALUE BEFORE ADOPTION', 'The evening, who, when, where; I&rsquo;m in or can&rsquo;t', 'NO PROFILE &middot; NO REASON ASKED &middot; THE ADDRESS ARRIVES WITH HIS ANSWER &middot; HIS NINE IN HIS OWN WORDS')",
     "('FRIDAY &middot; A LINK, NO APP', 'GUEST VALUE BEFORE ADOPTION', 'The evening, who, when, the neighborhood; I&rsquo;m in or can&rsquo;t', 'NO PROFILE &middot; NO REASON ASKED &middot; THE EXACT ADDRESS ONLY AFTER A ONE-TIME CODE TO HIS NUMBER &middot; HIS NINE IN HIS OWN WORDS')"),
])

# ───────────────────────────── gen_c4 · 04.2, 04.3, 04.4 + boat inset, 04.6, 04.7, 04.8 ─────────────────────────────
replace_func('gen_c4.py', 'home_sunday', '''def home_sunday():
    inner = anchor_row('NEW YORK &middot; SUNDAY', '10:20 AM')
    inner += orientation('Clear and mild. Bach at the old church at four.', 'Maya sent a photograph from last night.')
    inner += sect('From last night') + gut(card(f'<div style="border-radius: 12px; overflow: hidden; margin-bottom: 10px;">{standin(210, "THE TABLE &middot; SATURDAY 7:50 PM &middot; STAND-IN")}</div>' + author_row('M', 'Maya', 'LAST NIGHT &middot; TO YOU AND SAM')
                                                  + f'<div style="{SERIF} font-size: 18px; line-height: 25px; color: {INK}; margin-top: 8px;">The hour your camera missed.</div>'
                                                  + f'<div style="display: flex; gap: 18px; align-items: center; margin-top: 6px;">{door("Write back")}</div>' + meta('HERS &middot; TO THE DINNER&rsquo;S PEOPLE &middot; ALSO IN LIFE, UNDER LAST NIGHT', 8)))
    inner += sect('Today') + gut(u2('Bach on the organ at the old church, four o&rsquo;clock', 'The Passacaglia and two chorale preludes, forty minutes, free. The back pews are the good ones for the sound.', meta_t='DOWNTOWN &middot; SUNDAY 4 PM &middot; LISTED, NOT CHECKED TODAY') + door('The old church'))
    inner += sect('In motion') + gut('<div>' + row('Dentist &middot; Tuesday 9:00', mark='dashed', last=True) + '</div>')
    inner += gut(door('Everything in Life') + f'<div style="display: flex; gap: 7px; flex-wrap: wrap; padding-top: 8px;">{chip("dining", "Last night, at yours", "", serif=True)}</div>' + meta('LIFE &middot; THE DINNER, WITH WHAT EACH PERSON ADDED', 8), top=32)
    inner += week_ending(WEEK_SUN, 'Bach at four. Tuesday, the dentist.')
    return phone(inner, 0)
''')
replace_func('gen_c4.py', 'sam_photo', '''def sam_photo():
    inner = guestbar('FROM MAYA &middot; THROUGH YOUR LINK &middot; SUNDAY')
    inner += gut(f'<div style="{SERIF} font-weight: 600; font-size: 24px; line-height: 30px; letter-spacing: -0.2px;">Maya sent a photograph from last night.</div>', top=14)
    inner += gut(f'<div style="border-radius: 12px; overflow: hidden;">{standin(230, "THE TABLE &middot; SATURDAY 7:50 PM &middot; STAND-IN")}</div><div style="{SERIF} font-size: 17px; line-height: 24px; color: {INK}; margin-top: 10px;">&ldquo;The hour your camera missed.&rdquo;</div><div class="fn" style="margin-top: 6px; color: {ANCHOR};">MAYA &middot; TO YOU AND NORA</div>', top=18)
    inner += gut('<div>' + row('Stays here for you as long as Maya leaves it', mark='solid', color=GOLD) + row('The evening&rsquo;s details closed on Sunday', mark='hollow', last=True) + '</div>', top=18)
    inner += gut(door('Write back to Maya') + src('One line to Maya.'), top=22)
    return linkframe(inner)
''')
replace_func('gen_c4.py', 'life_record', '''def life_record():
    inner = life_head('LIFE &middot; PEOPLE', 'LATER')
    inner += gut(f'<div style="{SERIF} font-weight: 600; font-size: 24px; line-height: 30px; letter-spacing: -0.2px;">Pasta trial night, at yours</div><div style="font-size: 14px; line-height: 20px; color: {MUTE}; margin-top: 6px;">Saturday Sep 19 &middot; with Maya and Sam &middot; you hosted</div>', top=14)
    inner += bar('WHAT EACH PERSON ADDED &middot; THEIRS') + gut('<div>' + arow('Maya &middot; the table photograph &middot; <span style="color: #6E6862;">the hour your camera missed</span>', avatars=['M'])
                                                              + arow('Dana &middot; the rag&ugrave;, from Sorrento &middot; <span style="color: #6E6862;">&ldquo;slower than feels right&rdquo;</span>', avatars=['D'])
                                                              + arow('Sam &middot; &ldquo;I&rsquo;ll need to leave by nine&rdquo; &middot; <span style="color: #6E6862;">and he did</span>', avatars=['S'], last=True) + '</div>')
    inner += bar('YOUR ACCOUNT &middot; ONLY YOU') + gut(f'<div style="{SERIF} font-size: 16px; line-height: 23px; color: {INK2};">The sauce held. Dana was right about the twenty minutes.</div>')
    inner += bar('WHERE IT LIVES') + gut('<div>' + entry('dining', 'Saturday, Sep 19', 'Time') + entry('note', 'Maya, Sam, Dana', 'People') + entry('photo', 'Two photographs', 'the contact sheet', last=True) + '</div>')
    return phone(inner, 0, active='Life')

def boat_inset():
    """A separate record, linked from Life People; not nested in the dinner. An inset within the budget, not a slot."""
    return (f'<div style="margin-top: 14px; border: 1px dashed rgba(27,23,20,0.28); border-radius: 8px; padding: 12px 14px; display: flex; flex-direction: column; gap: 6px;">'
            f'<div class="kickm">A SEPARATE RECORD &middot; LIFE &middot; PEOPLE &middot; LINKED, NOT NESTED</div>'
            f'<div style="{SERIF} font-weight: 600; font-size: 16px; line-height: 21px;">The couple from the boat</div>'
            f'<div style="font-size: 12.5px; line-height: 17px; color: {INK2};">Sorrento &rarr; Amalfi ferry, August &middot; met once. Holds the photo you promised and the address they wrote on the ferry receipt.</div>'
            f'<div style="display: flex; gap: 14px; align-items: center;">{door("Send the photo, once")}</div>'
            f'<div class="fn" style="color: {ANCHOR};">ITS OWN RECORD; SEARCH REACHES EITHER &middot; NO-PATH BRANCH: THE SAME RECORD WITHOUT THE DOOR</div></div>')
''')
replace_func('gen_c4.py', 'sam_choice', '''def sam_choice():
    """Sought, not prompted: on his link's record of the evening, Nora's line offers 'Stay in touch' when he looks for it. Branch V: his number is verified, so the request can be his."""
    inner = guestbar('SATURDAY, AT NORA&rsquo;S &middot; YOUR LINK')
    inner += gut(f'<div style="border-radius: 12px; overflow: hidden;">{standin(120, "THE TABLE &middot; STAND-IN")}</div><div style="font-size: 14px; line-height: 20px; color: {INK2}; margin-top: 8px;">Maya&rsquo;s photograph, and what Nora wrote.</div>', top=14)
    inner += gut('<div>' + row('Nora &middot; <span style="color: #6E6862;">your host</span>', mark='av:N', last=True) + '</div>' + door('Stay in touch'), top=18)
    inner += gut(f'<div style="background: {CARD}; border-radius: 18px 18px 0 0; box-shadow: 0 -8px 24px rgba(27,23,20,0.14); padding: 14px 22px 22px 22px;"><div style="width: 36px; height: 4px; border-radius: 2px; background: rgba(27,23,20,0.15); margin: 0 auto 14px auto;"></div>'
                 + title('Stay in touch with Nora?', 19, 24, 600) + f'<div style="font-size: 14px; line-height: 20px; color: {INK2}; margin-top: 8px;">If you both say yes, you can share things and invite each other again.</div>'
                 + f'<div style="display: flex; align-items: center; gap: 14px; margin-top: 16px;">{pill("Yes, if she does")}{pill("Leave it", False)}</div><div style="font-size: 12.5px; line-height: 17px; color: {MUTE}; margin-top: 10px;">Leaving it is fine.</div></div>', top=22)
    return linkframe(inner)
''')
replace_func('gen_c4.py', 'nora_choice', '''def nora_choice():
    inner = anchor_row('NEW YORK &middot; TUESDAY', '6:30 PM')
    inner += orientation('Clear evening. The noodle counter is open till ten.', 'One thing from Sam.')
    inner += sect('In motion') + gut('<div>' + arow('Sam &middot; would stay in touch, if you would &middot; <span style="color: #6E6862;">share things and invite each other again</span>', avatars=['S']) + row('Dentist &middot; done &middot; <span style="color: #6E6862;">next in six months</span>', mark='solid', color=GOLD, last=True) + '</div>' + f'<div style="display: flex; gap: 18px; align-items: center; padding-top: 10px;">{door("Yes")}{door("Leave it", MUTE)}</div>')
    inner += sect('Tonight') + gut(u2('Hand-pulled noodles at the counter till ten', 'Three blocks from Canal Hall; no wait after nine. $14&ndash;18.', meta_t='CANAL STREET &middot; DAILY 6&ndash;10 &middot; LISTED, NOT CHECKED TODAY') + door('The noodle counter'))
    inner += gut(door('Everything in Life') + meta('LIFE', 0), top=32)
    inner += week_ending([('TUE', dm('solid', INK), 'today', INK), ('WED', dm('hollow', ''), '', MUTE), ('THU', dm('hollow', ''), '', MUTE), ('FRI', dm('hollow', ''), '', MUTE), ('SAT', dm('hollow', ''), '', MUTE), ('SUN', dm('hollow', ''), '', MUTE), ('MON', dm('hollow', ''), '', MUTE)], 'Noodles tonight, if you like. A quiet week.')
    return phone(inner, 0)
''')
replace_func('gen_c4.py', 'another_evening', '''def another_evening():
    """The existing-relationship continuation: Vesper recovers what usefully carries forward (place, start time, the photo), not old personal constraints. New invitations, new answers."""
    inner = chat_head('TWO WEEKS LATER')
    inner += gut(ctx_chip('LAST TIME &middot; SEP 19 &middot; AT YOURS', dot=GOLD), top=26)
    inner += gut(bubble('dinner with maya and sam again? saturday the 3rd'), top=22)
    inner += gut(answer('Here&rsquo;s a draft for another pasta evening at yours on Saturday, October 3, with Maya and Sam. Last time you started at seven; keep that time?'), top=18)
    inner += gut(card(f'<div class="kick" style="color: {GOLDD};">DRAFT &middot; NOT SENT</div>' + title('Pasta evening at Nora&rsquo;s', 18, 23, 600)
                      + f'<div style="margin-top: 6px; display: flex; flex-direction: column; gap: 2px;"><div style="font-size: 14px; line-height: 20px; color: {INK2};">Saturday Oct 3 &middot; from seven, proposed</div><div style="font-size: 14px; line-height: 20px; color: {INK2};">Court Street, 3F &middot; nothing to bring</div><div style="font-size: 14px; line-height: 20px; color: {INK2};">Maya and Sam &middot; fresh invitations; their answers decide</div></div>'
                      + f'<div style="display: flex; gap: 18px; align-items: center; margin-top: 8px;">{door("The table, last time")}</div>' + meta('LAST TIME&rsquo;S PHOTO AND THE RAG&Ugrave;, ONE TAP AWAY &middot; NOBODY&rsquo;S OLD TIMING IS PREFILLED', 8)), top=16)
    inner += gut(f'<div style="display: flex; align-items: center; gap: 14px;">{pill("Send with seven")}{pill("Change something", False)}</div><div style="font-size: 12.5px; line-height: 17px; color: {MUTE}; margin-top: 10px;">Or leave it here.</div>', top=18)
    return phone(inner, 0, active='Chat')

def before_after():
    return (f'<div style="display: flex; gap: 12px; margin-top: 10px;">'
            f'<div style="flex: 1; border: 1px dashed rgba(27,23,20,0.25); border-radius: 8px; padding: 10px 12px;"><div class="kickm" style="margin-bottom: 4px;">BEFORE &middot; SAME CURRENT FACTS</div><div style="font-size: 12px; line-height: 16px; color: {INK2};">Nora types the new arrangement herself (&ldquo;sat oct 3, 7, at mine, court st 3f, maya + sam, nothing to bring&rdquo;), then searches Life for the table photo to mention it.</div></div>'
            f'<div style="flex: 1; border: 1px solid rgba(27,23,20,0.10); background: {CARD}; border-radius: 8px; padding: 10px 12px;"><div class="kickm" style="margin-bottom: 4px;">AFTER &middot; SAME CURRENT FACTS</div><div style="font-size: 12px; line-height: 16px; color: {INK2};">One line; the draft carries the place and the proposed start; the photo is one tap away. Sam&rsquo;s old 7:30 and nine stay history, not defaults.</div></div></div>')
''')
sub('gen_c4.py', [
    ("        ('04.4', 'NORA', 'LIFE', life_record(), ('LATER &middot; LIFE &middot; PEOPLE', 'THE EVENING AS ONE RECORD', 'What each person added, theirs; her account, hers alone', 'RECOGNITION, NOT MAINTENANCE &middot; NOTHING NARRATES WHAT ANYONE FELT &middot; THREE DOORS TO ONE OBJECT'),",
     "        ('04.4', 'NORA', 'LIFE', life_record(), ('LATER &middot; LIFE &middot; PEOPLE', 'THE EVENING AS ONE RECORD', 'What each person added, theirs; her account, hers alone', 'RECOGNITION, NOT MAINTENANCE &middot; THE RECORD HOLDS ITS OWN MATERIAL; THE BOAT COUPLE ARE A SEPARATE RECORD (INSET)'),"),
    ("        ('04.3', 'SAM', 'LINK', sam_photo(), ('SUNDAY &middot; HIS LINK', 'THE SAME PHOTOGRAPH, LATER', 'Looking needs nothing; keeping may need a confirmation', 'THE PROPOSED VERIFICATION AT THE BOUNDARY, NOT BEFORE &middot; NO ACCOUNT, NO PROFILE &middot; NOT GRANTED BY THE EXPIRED INVITATION'),\n         ('Sam', 'His link, later', 'Open', 'The same photograph', 'Maya&rsquo;s grant to the dinner&rsquo;s people', 'Contribution (guest view)', '&mdash;', 'Receive without contributing'), ('DEPENDENCY &middot; IDENTITY OR DELIVERY FOR A NON-MEMBER', 'DESIGN OWNS WHAT HE RECEIVES; ENGINEERING MAPS SUPPORT', 'FIXTURE')),",
     "        ('04.3', 'SAM', 'LINK', sam_photo(), ('SUNDAY &middot; HIS LINK &middot; VERIFIED', 'THE SAME PHOTOGRAPH, LATER', 'Displayed through his verified link as long as Maya leaves it', 'BRANCH V: HIS NUMBER WAS CONFIRMED FOR THE ADDRESS; THE SAME PRINCIPAL SEES THE PHOTO &middot; THE EVENING&rsquo;S DETAILS CLOSED SUNDAY &middot; NO ACCOUNT'),\n         ('Sam', 'His link, later', 'Open', 'The same photograph', 'Maya&rsquo;s delivery to the dinner&rsquo;s people; until she takes it back', 'Contribution (guest view)', '&mdash;', 'Receive without contributing'), ('DEPENDENCY &middot; LATER MEDIA DELIVERY TO A VERIFIED NON-MEMBER', 'GUEST PROPOSAL &sect;3', 'FIXTURE')),"),
    ("        ('04.6', 'SAM', 'LINK', sam_choice(), ('LATER &middot; HIS LINK &middot; SOUGHT, NOT PROMPTED', 'STAY IN TOUCH?', 'He looks for it under Nora&rsquo;s name; the capability is named; leaving it is fine', 'C5 &middot; NEVER APPENDED AFTER A PHOTO &middot; SEPARATE FROM RSVP, THE PHOTO AND ANY ACCOUNT'),",
     "        ('04.6', 'SAM', 'LINK', sam_choice(), ('LATER &middot; HIS LINK &middot; SOUGHT, NOT PROMPTED', 'STAY IN TOUCH?', 'He looks for it under Nora&rsquo;s name; share things and invite each other again; leaving it is fine', 'C5 &middot; NEVER APPENDED AFTER A PHOTO &middot; BRANCH V: HIS VERIFIED NUMBER IS THE PRINCIPAL &middot; SEPARATE FROM RSVP AND THE PHOTO'),"),
    ("('PROPOSED &middot; C5: ELIGIBLE THINGS BETWEEN TWO PEOPLE + INVITING WITHOUT A LINK', 'DEPENDENCY &middot; A NON-ACCOUNT GUEST NEEDS A VERIFIED PRINCIPAL', 'FIXTURE')", "('PROPOSED &middot; C5: SHARE THINGS AND INVITE EACH OTHER AGAIN', 'DEPENDENCY &middot; THE VERIFIED CONTACT AS PRINCIPAL (GUEST PROPOSAL)', 'FIXTURE')"),
    ("        ('04.7', 'NORA', 'HOME', nora_choice(), ('TUESDAY 6:30 PM', 'HER SIDE OF THE SAME CHOICE', 'One row in motion; yes, or leave it; the rest of Home intact', 'ONE ITEM, SO NO ADDRESSED-TO-YOU SECTION &middot; ACCEPT ENABLES THE NAMED CAPABILITY ONLY &middot; IGNORED, DECLINED, ACCEPTED ARE ALL COMPLETE'),",
     "        ('04.7', 'NORA', 'HOME', nora_choice(), ('TUESDAY 6:30 PM', 'HER SIDE OF THE SAME CHOICE', 'One row in motion; yes, or leave it; a concrete evening opening', 'ONE ITEM, SO NO ADDRESSED-TO-YOU SECTION &middot; A QUIET EVENING STILL CARRIES ONE USABLE WORLD OPENING (HOME-OWNER DELTA)'),"),
    ("        ('04.2', 'NORA', 'HOME', home_sunday(), ('SUNDAY 10:20 AM', 'IT ARRIVES ONCE, AS THE IMAGE', 'From last night; the rest of Home is a quiet Sunday', 'ONE ITEM, SO NO ADDRESSED-TO-YOU SECTION (TWO-ITEM RULE) &middot; A VIEW OF ONE SOURCE &middot; ALSO IN LIFE'),",
     "        ('04.2', 'NORA', 'HOME', home_sunday(), ('SUNDAY 10:20 AM', 'IT ARRIVES ONCE, AS THE IMAGE', 'From last night; a quiet Sunday with one concrete opening', 'ONE ITEM, SO NO ADDRESSED-TO-YOU SECTION &middot; BACH AT FOUR IS THE WORLD OPENING A QUIET DAY STILL MERITS (HOME-OWNER DELTA) &middot; ALSO IN LIFE'),"),
    ("        ('04.8', 'NORA', 'CHAT', another_evening(), ('TWO WEEKS LATER', 'ANOTHER PASTA EVENING', 'The last one&rsquo;s shape, reused with consent; fresh invitations', 'AUTHORIZED PRIOR MATERIAL REDUCES REPEATED EXPLANATION &middot; NEW OCCASION, NEW CHOICES &middot; NOTHING INHERITED'),\n         ('Nora', 'Chat', 'Say it', 'The last dinner&rsquo;s shape offered back; one Send', 'Maya and Sam get fresh invitations', 'Occasion (new)', 'Two fresh invitations', 'Send; or change something'), ('R8 F2 &middot; REACTIVATION BY REFERENCE', 'BEFORE / AFTER SPECIMEN BELOW', 'THE BOAT COUPLE ARE NOW A ROW ON 04.4')),",
     "        ('04.8', 'NORA', 'CHAT', another_evening(), ('TWO WEEKS LATER', 'ANOTHER PASTA EVENING', 'A draft with the place and a proposed start; the photo one tap away; fresh invitations', 'WHAT USEFULLY CARRIES FORWARD, NOT OLD STATE &middot; SAM&rsquo;S OLD TIMING STAYS HISTORY &middot; THEIR ANSWERS DECIDE &middot; SHE MAY LEAVE THE DRAFT'),\n         ('Nora', 'Chat', 'Say it', 'A private draft: place, proposed seven, the people named; the photo reachable', 'Maya and Sam get fresh invitations; nothing prefilled from their side', 'Occasion (new, on Send)', 'Two fresh invitations', 'Send with seven; change something; or leave it'), ('R8 F2 &middot; REACTIVATION BY REFERENCE', 'BEFORE / AFTER, SAME CURRENT FACTS', 'DRAFT = PRIVATE PREPARATION UNDER ASK; NO PLAN PERSISTS UNTIL SEND')),"),
    ("    cols2 = [colu(ph, cap(n, role, root, *c), under(r, s) + (before_after() if n == '04.8' else '')) for n, role, root, ph, c, r, s in P2]",
     "    cols2 = [colu(ph, cap(n, role, root, *c), under(r, s) + (before_after() if n == '04.8' else '')) for n, role, root, ph, c, r, s in P2]\n    cols1 = [c if not c.startswith('<div style=\"width: 393px; flex: none; display: flex; flex-direction: column;\">' + cap('04.4', 'NORA', 'LIFE', *P1[3][4])) else c.replace('</div>', boat_inset() + '</div>', 1)[::-1].replace('>vid/<'[::-1], '', 0)[::-1] for c in cols1]"),
    ("        ('ANOTHER EVENING', N('04.8 restores the existing-relationship continuation: the last dinner&rsquo;s shape comes back from Nora&rsquo;s own record with one line, Maya and Sam get fresh invitations, nothing is inherited. The before/after strip shows the retyping it removes. The boat couple are a compact row on 04.4.')),",
     "        ('ANOTHER EVENING', N('04.8 recovers what usefully carries forward: the place, a proposed start, the people to invite, and the photo one tap away. Sam&rsquo;s old arrival and departure stay history, not defaults; his and Maya&rsquo;s fresh answers decide. The draft is private preparation until Send; Nora may leave it. Both sides of the before/after use the same current facts. The boat couple are their own record, linked from Life People as an inset beside 04.4, not nested in the dinner.')),"),
    ("('COPY OF R3&rsquo;S GRAMMAR', 'LIFE SEQUENCES &middot; RULED', 'FIXTURE')", "('COPY OF R3&rsquo;S GRAMMAR', 'LIFE SEQUENCES &middot; RULED', 'THE BOAT INSET IS NOT A SLOT')"),
])

# ───────────────────────────── gen_c5 · D6 copy, connection/capability tables, routes ─────────────────────────────
sub('gen_c5.py', [
    ("    inner += sect('In motion') + gut('<div>' + arow('Sam &middot; <span style=\"color: #6E6862;\">connected &middot; things between you; inviting without a link</span>', avatars=['S'], last=True) + '</div>' + meta('WHAT ACCEPTING ENABLED, AND ALL IT ENABLED', 8))",
     "    inner += sect('In motion') + gut('<div>' + arow('Sam &middot; <span style=\"color: #6E6862;\">in touch &middot; share things and invite each other again</span>', avatars=['S'], last=True) + '</div>')"),
    ("    inner += gut(f'<div style=\"{SERIF} font-weight: 600; font-size: 22px; line-height: 28px;\">Saturday, at Nora&rsquo;s</div><div style=\"font-size: 14px; line-height: 20px; color: {INK2}; margin-top: 8px;\">Maya&rsquo;s photograph, and what Nora wrote. This link keeps them; it will not bring anything new.</div>', top=14)",
     "    inner += gut(f'<div style=\"{SERIF} font-weight: 600; font-size: 22px; line-height: 28px;\">Saturday, at Nora&rsquo;s</div><div style=\"font-size: 14px; line-height: 20px; color: {INK2}; margin-top: 8px;\">Maya&rsquo;s photograph, here as long as she leaves it, and what Nora wrote. The evening&rsquo;s details closed on Sunday.</div>', top=14)"),
    ("    inner += gut(src('A complete ending. Nothing is appended to solicit a connection; he can seek one under Nora&rsquo;s name if he wants to.'), top=14)", "    inner += gut(src('A complete ending.'), top=14)"),
    ("    ['C5 default capability: a photo or a line between two people; inviting without a new link; nothing else', 'Proposed', 'Needs the contract; the pair circle is the likely container (capability map, seam 6)'],",
     "    ['C5: share things and invite each other again, between two people who both said yes; audiences still chosen per share; mute, disconnect, block and report distinct, none a prerequisite, no automatic report', 'Proposed', 'Pair circles are the first container candidate; a verified non-account principal is the guest proposal&rsquo;s open question'],"),
    ("        ['A guest who is not a trip member', '03.2, 03.6, 03.7, 04.3, 04.6', 'No guest identity primitive; invite scope is trip-wide; the public view carries no address', 'Guest identity and delivery policy'],\n        ['A contributor path outside membership (03.3)', '03.3', 'Roles are organizer / member only; no occasion roster; no address redaction', 'Product: the contributor invitation as an addressed line'],\n        ['Prepare an alternative without applying; per-recipient readback', '03.5, 03.6', 'Owner gate and open-until-resolved are real; readback is one static sentence; &ldquo;must leave by nine&rdquo; cannot be stored', 'Engineering, within the seven sentences'],\n        ['The ongoing-connection capability', '04.6, 04.7', 'Pair circles with request / accept / decline exist; no per-person mute; no block; follows are public and one-way', 'Contract: C5 default; mute vs disconnect vs block'],",
     "        ['A guest who is not a member (branch V)', '03.2, 03.6, 03.7, 04.3, 04.6', 'Canonical Occasion membership and invitations exist for accounts; legacy invite tokens, landing and delivery are reusable; no-account access per capability, recipient verification and later media delivery are unverified integration gaps', 'Guest proposal: verification at the first sensitive boundary vs an authorized bearer design'],\n        ['A contributor path outside attendance (03.3)', '03.3', 'The canonical Occasion roster and contribution authority exist; a narrow contributor view without the address is an integration gap, not a missing foundation', 'Product: the contributor invitation as an addressed line'],\n        ['A prepared alternative and per-recipient readback', '03.5, 03.6', 'Proposal-only preparation and shared Plan repair exist; carrying the result to each affected person&rsquo;s reader is unverified', 'Engineering, per the live-engine owner-path matrix'],\n        ['The ongoing connection and its controls', '04.6, 04.7', 'Pair circles with request / accept / decline and a pair conversation exist; per-person mute, block across links and messages, and persisted report are not established', 'C5 proposal; mute / disconnect / block / report as distinct choices'],"),
    ("        ['A friends audience on a share', '02.2, 02.3', 'None; &ldquo;friends&rdquo; is only a Discover feed label; no audience column on the share', 'Contract: an authored roster, never a follow graph'],",
     "        ['A friends audience on a share', '02.2, 02.3', 'Named-recipient and Occasion audiences exist; a user-facing Friends selection resolved from the author&rsquo;s connections is an integration gap', 'Friends-audience proposal: one connection, deliberate per-share audiences; evaluate existing named-recipient authority before adding a kind'],"),
    ("    ['Occasion (canonical owner)', 'The guest link page family: invitation, adopted change, arrival, the photo later, stay in touch when sought (03.2, 03.6, 03.7, 04.3, 04.6)', 'Guest value without adoption', 'A bounded guest is not a member; sensitive facts after a verified boundary', 'Seam 3: extend canonical Occasion invitations; guest identity and delivery unresolved', 'Integration gap, not a build authorization'],",
     "    ['Occasion (canonical owner)', 'The guest link page family under branch V: safe preview, answer, address after a one-time code, arrival, the photo later through the verified link, stay in touch when sought (03.2, 03.6, 03.7, 04.3, 04.6)', 'Guest value without adoption', 'A bounded guest is not a member; sensitive facts only after verification', 'Seam 3: extend canonical Occasion invitations; guest identity and delivery unresolved', 'Integration gap, not a build authorization'],\n    ['Home 42876b8c &middot; quiet days', 'A quiet Home still carries one concrete, current, usable world opening (04.2: Bach at the old church at four; 04.7: the noodle counter till ten) with its context and destination; not a contribution prompt, not a generic discover door', 'Quiet is low coercion, not low value', 'Posture rules unchanged', 'World-content supply for quiet days (Home owner); the copied baseline does not meet this on its own', 'Delta to the Home owner; dependency marked'],"),
    ("    ['Send selected material', '02.2', 'A photo and a line to friends; a KEPT receipt with Undo (Home form)', 'Back to Chat'],", "    ['Share from the object', '02.2', 'Maya&rsquo;s photo and line reach her chosen audience; owner readback once', 'Return restores the place page'],"),
    ("    'NORA': [('02.1', 'Ask about the sauce', 'CHAT'), ('02.2', 'Share the photo', 'SHARE'), ('02.3', 'From friends', 'PLACES'),", "    'NORA': [('02.1', 'Ask about the sauce', 'CHAT'), ('02.3', 'From friends', 'PLACES'),"),
    ("    'MAYA': [('02.7', 'Her share, later', 'PLACES'),", "    'MAYA': [('02.2', 'Share the Print Room', 'PLACES'), ('02.7', 'Her share, later', 'PLACES'),"),
    ("    ['Contribute the photograph', '04.1 &rarr; 04.2 / 04.3', 'Nora and Sam receive the image once', 'Life holds it under the dinner'],", "    ['Contribute the photograph', '04.1 &rarr; 04.2 / 04.3', 'Nora and Sam receive the image once; the authorized Send crosses the audience boundary with owner readback', 'Life holds it under the dinner'],"),
    ("    ['Send the promised photo', '04.4', 'One email through the address they gave', 'The record stands either way'],", "    ['Send the promised photo', '04.4 inset (its own record)', 'One email through the address they gave', 'The record stands either way'],"),
    ("        ['The boat couple', '04.4 (a row)', 'Email leads; the no-path branch is the same row without the door'],", "        ['The boat couple', 'A separate record, inset beside 04.4', 'Email leads; the no-path branch is the same record without the door'],\n        ['Guest identity', '03.2 &rarr; 03.7 &rarr; 04.3 &rarr; 04.6', 'Branch V throughout: verified at the address boundary; the same principal sees the photo and may seek the connection'],"),
    ("02.2 became an existing friend sharing from the object with no prelude; 02.3 gained a map; 03.5 gained direct actions; 04.2 and 04.7 lost their one-item Addressed-to-you sections; 04.8 became another pasta evening and the boat couple a row on 04.4; policy narration left every phone.'))",
     "02.2 became an existing friend sharing from the object with no prelude; 02.3 gained a map; 03.5 gained direct actions; 04.2 and 04.7 lost their one-item Addressed-to-you sections and gained one concrete world opening each; 04.8 became another pasta evening that carries forward the place and a proposed start, not old constraints; the boat couple became their own record, inset beside 04.4; the guest lifecycle is one labelled branch (V) throughout; policy narration was removed from the phones and the remaining copy checked with annotations hidden.'))"),
])
sub('gen_c5.py', [
    ("    ['D6 &middot; Continuity', 'One understandable optional connection, sought not solicited, with per-share audience; occasion-bounded contact stays valid; eligible things, not only photos and text', 'People who want more must seek it; nothing widens by itself', '05 pair 6; 04.6, 04.7', 'How often either side seeks it; whether leaving it feels complete'],",
     "    ['D6 &middot; Continuity', 'One understandable optional connection, sought not solicited: share things and invite each other again; audiences still chosen per share; occasion-bounded contact stays valid and complete', 'People who want more must seek it; nothing widens by itself', '05 pair 6; 04.6, 04.7', 'How often either side seeks it; whether leaving it feels complete'],"),
])

# ───────────────────────────── gen_c2 · 04.1 stamp lives in c4; 02.x nothing else ─────────────────────────────
sub('gen_c4.py', [
    ("('FIXTURE', 'C1 &middot; AFFECTED-PERSON RIGHTS APPLY', 'T1 &middot; RECEIPT WITH UNDO NOT SHOWN')", "('FIXTURE', 'C1 &middot; AFFECTED-PERSON RIGHTS APPLY', 'T2 &middot; THE ONE CLEAR SEND &middot; OWNER READBACK ONCE')"),
])

# ───────────────────────────── gen_se · board 01 actors and allocation ─────────────────────────────
sub('gen_se.py', [
    ("    ['A0&prime;', 'Nora', 'The answered photo, or any eligible photo directly', 'Share', 'The smallest audience treatment: WHO, then Send', 'Friends; the draft carries no question, answer, address or invitation', 'Contribution', 'Friends see a photo and a line', 'Sent once; or kept to herself'],",
     "    ['A0&prime;', 'Maya', 'The Print Room&rsquo;s place page', 'Share', 'Her picture and her words reach the people she chose', 'Friends, through Sunday; a send crosses an audience boundary (T2)', 'Contribution', 'Friends see a photo and a line in their scope', 'Sent once; return restores the place page'],"),
    ("            ('02.2', 'NORA', 'CHAT', 'Share the photo: WHO, her one line, no question or answer in the draft; or share directly from any eligible photo', 'Sent to friends, once.'),",
     "            ('02.2', 'MAYA', 'PLACES', 'Maya shares the Print Room directly from its page: one line, who, Send; no prelude', 'Sent to friends, once.', 'R1'),"),
    ("            ('02.3', 'NORA', 'PLACES', 'From friends, full scroll: Maya&rsquo;s Print Room photo; Dana&rsquo;s Sorrento doorway; the wider field', 'Enjoy it and leave.', 'R1 / R12'),",
     "            ('02.3', 'NORA', 'PLACES', 'From friends, full scroll: Maya&rsquo;s photo; Priya&rsquo;s three-stop map; the pigeons; Dana elsewhere; Red Hook anyway', 'Enjoy it and leave.', 'R1 / R12'),"),
    ("            ('04.8', 'NORA', 'LIFE', 'The boat couple: the promised photo through the supplied email; branch b, no path', 'One send; no friend upgrade.'),",
     "            ('04.8', 'NORA', 'CHAT', 'Two weeks later: a draft for another evening with the place and a proposed start; the photo one tap away; fresh invitations', 'Send with seven, or leave it.', 'R8 F2'),"),
    ("            ('04.6', 'SAM', 'LINK', 'After the photo: remain occasion-bound, or offer to stay connected; the exact capability named; ignoring is comfortable', 'Bound, or connected.'),",
     "            ('04.6', 'SAM', 'LINK', 'Sought under Nora&rsquo;s name on his link: share things and invite each other again; leaving it is fine', 'Bound, or connected.'),"),
    ("            ('04.4', 'NORA', 'LIFE', 'People &middot; the dinner: what each person added, theirs; her account, hers alone', 'Recognition, not maintenance.', 'R3'),",
     "            ('04.4', 'NORA', 'LIFE', 'People &middot; the dinner: what each person added, theirs; her account. The boat couple are a separate record, inset', 'Recognition, not maintenance.', 'R3'),"),
    ("    alloc = blk('THE ALLOCATION &middot; 24 SLOTS &middot; AND THE TRADEOFF', N('15 Nora &middot; 2 Maya &middot; 5 Sam &middot; 1 Dana &middot; 1 offline note. To make room: the second host preview and the Send readback fold into 03.1 and a line on Home; Maya&rsquo;s unadopted-proposal view becomes the branch label on 03.5; the B0 &ldquo;thinking of Saturday&rdquo; share moves to board 05 as D1; &ldquo;another pasta evening&rdquo; is not drawn (its precedent is R8&rsquo;s reactivation by reference) and is noted on 07. If the founder wants it back, the candidate to give up is 02.4, the Print Room opened.'))",
     "    alloc = blk('THE ALLOCATION &middot; 24 SLOTS &middot; REVISED PER &sect;14 AND &sect;15', N('14 Nora &middot; 3 Maya &middot; 5 Sam &middot; 1 Dana &middot; 1 offline note. 02.2 is Maya&rsquo;s share from the object (no prelude); 04.8 is another pasta evening; the boat couple are a separate record inset beside 04.4, not a slot; B0 lives on board 05 as D1. The second host preview and the Send readback fold into 03.1 and a line on Home; Maya&rsquo;s unadopted-proposal view is the branch label on 03.5.'))"),
    ("    ['C3', 'The promised ferry photo', 'Nora', 'The boat couple, by the supplied path', 'One send', 'Email leads; no-path is the valid alternative. An external-contact edge case, not the continuity decision'],",
     "    ['C3', 'The promised ferry photo', 'Nora', 'The boat couple, by the supplied path', 'One send', 'Email leads; no-path is the valid alternative. Its own record in Life People, linked, never nested in the dinner'],\n    ['C3&prime;', 'Another pasta evening: &ldquo;dinner with maya and sam again? saturday the 3rd&rdquo;', 'Nora', 'Maya and Sam, by fresh invitations', 'The new occasion, on Send', 'A private draft carries the place and a proposed start; old personal timings stay history; their fresh answers decide; she may leave the draft'],"),
    ("    ['C5', 'Optional ongoing connection', 'Nora and Sam, each choosing', 'Only the named future contact or sharing capability; the exact default is a recommendation', 'Revocable', 'Request/accept is separate from invitation, RSVP, account creation and private remembrance. Remaining occasion-bound is complete. Ignored or declined is comfortable'],",
     "    ['C5', 'Optional ongoing connection, sought by Sam under Nora&rsquo;s name (never appended after a photo)', 'Nora and Sam, each choosing', 'Share things and invite each other again; audiences still chosen per share', 'Revocable', 'Separate from invitation, RSVP and the photo. Branch V: Sam&rsquo;s verified number is the principal. Remaining occasion-bound is complete; leaving it is fine'],"),
    ("    ['C1', 'The table photograph', 'Maya', 'The dinner&rsquo;s agreed audience, subject to affected-person rights', 'Persists under Maya&rsquo;s grant', 'Maya&rsquo;s deliberate contribution and Sam&rsquo;s later receiving view are both drawn. Identity or delivery may be required: DEPENDENCY, outside the phone; never granted by an expired invitation'],",
     "    ['C1', 'The table photograph', 'Maya', 'The dinner&rsquo;s agreed audience, subject to affected-person rights', 'Displayed through Sam&rsquo;s verified link as long as Maya leaves it; the evening&rsquo;s details close Sunday', 'Branch V: Sam confirmed his number for the address; the same principal sees the photo. A send to others is a T2 boundary carried by the one Send. DEPENDENCY outside the phone'],"),
    ("    ['B1', '&ldquo;Pasta trial night at mine Saturday at seven. Invite Maya and Sam. Sam can come at seven-thirty; nothing to bring.&rdquo;', 'Nora', 'Maya (full); Sam (dinner only, a link); address only in each recipient&rsquo;s view', 'The evening', 'When, where, who; nothing else of Nora&rsquo;s. Sam gains nothing of the friends audience'],",
     "    ['B1', '&ldquo;Pasta trial night at mine Saturday at seven. Invite Maya and Sam. Sam can come at seven-thirty; nothing to bring.&rdquo;', 'Nora', 'Maya (full); Sam (dinner only, a link by text to a number Nora typed); the exact address in Maya&rsquo;s view at once and in Sam&rsquo;s only after a one-time code to that number (branch V)', 'The evening', 'When, where, who; nothing else of Nora&rsquo;s. Sam gains nothing of the friends audience'],"),
])
print('patched; misses:', len(MISS)); [print('  MISS', p, o) for p, o in MISS]
