"""September 9 low-pressure receiving (handoff §0, 2026-09-09): 08.1 timeline elevation removed; 08.2/08.3 reader copy cleaned; Home/Life/Plans reconciled; budget overrun recorded as an unresolved scope discrepancy."""
MISS = []
def sub(path, pairs):
    s = open(path).read()
    for old, new in pairs:
        n = s.count(old)
        if n == 1: s = s.replace(old, new)
        elif new in s: pass
        else: MISS.append((path, old[:90]))
    open(path, 'w').write(s)

# ───────────────────────────── gen_c6 · board 08 ─────────────────────────────
sub('gen_c6.py', [
    # 08.1: the opening is not the recipient's agenda
    ("WEEK_THU = [('THU', dm('solid', INK), 'today', INK), ('FRI', dm('hollow', ''), '', MUTE), ('SAT', dm('solid', GOLD), 'pasta', INK), ('SUN', dm('hollow', ''), '', MUTE), ('MON', dm('hollow', ''), '', MUTE), ('TUE', dm('hollow', ''), '', MUTE), ('WED', dm('hollow', ''), '', MUTE)]",
     "WEEK_THU = [('THU', dm('solid', INK), 'today', INK), ('FRI', dm('hollow', ''), '', MUTE), ('SAT', dm('hollow', ''), '', MUTE), ('SUN', dm('hollow', ''), '', MUTE), ('MON', dm('hollow', ''), '', MUTE), ('TUE', dm('hollow', ''), 'dentist', MUTE), ('WED', dm('hollow', ''), '', MUTE)]"),
    ("    inner += week_ending(WEEK_THU, 'Saturday, pasta at Nora&rsquo;s, if it happens.')", "    inner += week_ending(WEEK_THU, 'A quiet week. Tuesday, the dentist.')"),
    ("('THURSDAY 8:12 PM', 'IT ARRIVES ONCE, WITHOUT A PLACE', 'Nora&rsquo;s pasta and a line, to friends; no map, no pin, no occasion', 'REUSES 05 D1-A AS THE SENDER STATE &middot; ONE ITEM, SO NO SECTION &middot; PLACEMENT IS A NAMED PROPOSAL (RIGHT)')",
     "('THURSDAY 8:12 PM', 'IT ARRIVES ONCE, WITHOUT A PLACE', 'Nora&rsquo;s pasta and a line, to friends; no map, no pin, no occasion; her week unchanged', 'REUSES 05 D1-A AS THE SENDER STATE &middot; ONE ITEM, SO NO SECTION &middot; AN OPENING IS NOT THE RECIPIENT&rsquo;S AGENDA: NOTHING ON HER WEEK &middot; PLACEMENT IS A NAMED PROPOSAL (RIGHT)')"),
    # 08.2: the reader lets the original, author, audience and lifetime speak
    ("    inner += sect('Where it lives') + gut('<div>' + entry('note', 'Nora', 'People') + entry('dining', 'Thursday, Sep 17', 'Time', last=True) + '</div>' + src('No place. Nothing here asks for one.'))",
     "    inner += sect('Where it lives') + gut('<div>' + entry('note', 'Nora', 'People') + entry('dining', 'Thursday, Sep 17', 'Time', last=True) + '</div>' + src('Hers &middot; to friends &middot; through Sunday'))"),
    ("('THE PASTA, OPENED', 'THE EXACT SOURCE', 'Her photograph, her line, who, until when; Reply; Ask is private', 'LIFE&rsquo;S EXACT-SOURCE READER (R4 GRAMMAR) &middot; NO MAP POSITION INVENTED &middot; RETURN RESTORES HOME&rsquo;S SCROLL')",
     "('THE PASTA, OPENED', 'THE EXACT SOURCE', 'Her photograph, her line, who, until when; Reply; Ask is private', 'LIFE&rsquo;S EXACT-SOURCE READER (R4 GRAMMAR) &middot; NO MAP POSITION INVENTED &middot; AVAILABLE WHILE SHE LEAVES IT, NOT KEPT BY OPENING &middot; RETURN RESTORES HOME&rsquo;S SCROLL')"),
    # 08.3: shared-with-you versus yours (Life's vocabulary); no doctrine line
    ("    inner += bar('FROM NORA &middot; HERS') + gut('<div>' + entry('photo', 'The pasta, second try', 'Thursday &middot; to friends &middot; through Sunday') + entry('dining', 'Pasta trial night, at hers', 'Saturday Sep 19 &middot; you added the table', last=True) + '</div>')\n    inner += bar('FROM YOU &middot; YOURS') + gut('<div>' + entry('photo', 'The Print Room', 'Thursday &middot; to friends') + entry('photo', 'The table', 'Saturday &middot; to Nora and Sam', last=True) + '</div>')\n    inner += bar('HELD IN COMMON') + gut('<div>' + entry('note', 'Two evenings', 'this year', last=True) + '</div>')\n    inner += gut(door('Everything from Nora') + src('Retrieval writes nothing.'), top=22)",
     "    inner += bar('SHARED WITH YOU &middot; NORA&rsquo;S, WHILE SHE LEAVES IT') + gut('<div>' + entry('photo', 'The pasta, second try', 'Thursday &middot; to friends &middot; through Sunday') + entry('dining', 'Pasta trial night, at hers', 'Saturday Sep 19 &middot; the dinner you were at', last=True) + '</div>')\n    inner += bar('YOURS') + gut('<div>' + entry('photo', 'The Print Room', 'Thursday &middot; to friends') + entry('photo', 'The table', 'Saturday &middot; to Nora and Sam', last=True) + '</div>')\n    inner += bar('HELD IN COMMON') + gut('<div>' + entry('note', 'Two evenings', 'this year', last=True) + '</div>')\n    inner += gut(door('Everything from Nora'), top=22)"),
    ("('LATER &middot; LIFE &middot; PEOPLE', 'THE PULL ROUTE', 'Everything from Nora, hers; everything to Nora, Maya&rsquo;s; the dinner beside the line', 'COPY OF R3&rsquo;S GRAMMAR &middot; RETRIEVAL WRITES NOTHING &middot; NO SOCIAL TAB, NO FEED')",
     "('LATER &middot; LIFE &middot; PEOPLE', 'THE PULL ROUTE', 'Shared with you, while Nora leaves it; yours; held in common', 'COPY OF R3&rsquo;S GRAMMAR &middot; LIFE 04&rsquo;S &ldquo;YOURS, AND WHAT OTHERS SHARED WITH YOU&rdquo; &middot; A PATH BACK DOES NOT MEAN KEPT &middot; NO SOCIAL TAB, NO FEED')"),
    ("         ('Maya', 'Life &middot; People &middot; Nora', 'Open', 'What Nora shared with her; what she shared with Nora', 'Attributed; each still its author&rsquo;s', 'Life', '&mdash;', 'Open, or leave'), ('LIFE SEQUENCES &middot; RULED', 'REFIND OVER A PHOTO IS A DEPENDENCY (SEAM 7)', 'FIXTURE')),",
     "         ('Maya', 'Life &middot; People &middot; Nora', 'Open', 'What Nora shared with her, while it lasts; what she shared with Nora', 'Attributed; each still its author&rsquo;s; nothing kept by refinding', 'Life', '&mdash;', 'Open, or leave'), ('LIFE SEQUENCES &middot; RULED', 'REFIND OVER A PHOTO IS A DEPENDENCY (SEAM 7)', 'FIXTURE')),"),
    # notes: placement counterpoint from the Home review; budget discrepancy
    ("        ('WHAT THIS DOES NOT DECIDE', N('The Friends audience remains the friends-audience proposal; this board assumes it as a fixture. The accepted spatial-social split stands: place-bound shares still open in Places. A change to accepted placement is this named proposal for the Home and Life owners, not a silent broadening.')),",
     "        ('WHAT THIS DOES NOT DECIDE', N('The Friends audience remains the friends-audience proposal; this board assumes it as a fixture. The accepted spatial-social split stands: place-bound shares still open in Places. A change to accepted placement is this named proposal for the Home and Life owners, not a silent broadening. The Home review (September 8, &ldquo;with people&rdquo; kinds) keeps the addressed region for contributions addressed to the person and relocates casual status to Places by default; whether a friends-audience original counts as addressed material or casual status is the open point, and Home decides it.')),"),
    ("'Two continuations the September 8 assignment named as missing from the selected experience: a friend&rsquo;s original that has no place, received, opened and found again; and where a guest returns after both people chose to stay in touch. Five slots beyond the twenty-four, drawn on existing families; the placement is a named proposal, not a new destination.'",
     "'Two continuations the September 8 assignment named as missing from the selected experience: a friend&rsquo;s original that has no place, received, opened and found again; and where a guest returns after both people chose to stay in touch. Five slots beyond the twenty-four-slot ceiling, drawn on existing families and recorded on 00 and 07 as an unresolved scope discrepancy, not compliance; the placement is a named proposal, not a new destination.'"),
    ("        ('SOMETHING WITHOUT A PLACE', N('08.1 to 08.3 take board 05&rsquo;s D1-A (Nora&rsquo;s pasta and a line, to friends, no guest count) from its sender state to a recipient: it arrives once, opens to the exact source, and is found again under the person. No occasion, no pin, no reply owed.')),",
     "        ('SOMETHING WITHOUT A PLACE', N('08.1 to 08.3 take board 05&rsquo;s D1-A (Nora&rsquo;s pasta and a line, to friends, no guest count) from its sender state to a recipient: it arrives once, opens to the exact source, and is found again under the person. No occasion, no pin, no reply owed. Nora&rsquo;s &ldquo;thinking of Saturday&rdquo; is her opening, not Maya&rsquo;s agenda: Maya&rsquo;s week does not change until she does something, and enjoying it with no response is a complete ending.')),"),
])

# ───────────────────────────── gen_c5 · board 07: September 9 block, deltas, status ─────────────────────────────
sub('gen_c5.py', [
    ("    ['Home 42876b8c &middot; 10 (block state)', 'Blocking or hiding a participant must not change the gathering&rsquo;s count or attendance (10&rsquo;s block frame moves Alex&rsquo;s evening from four going to three with no attendance event); a viewer-relative count must not read as the gathering&rsquo;s size; keep shared truth and the viewer&rsquo;s own hiding separate', 'Safe shared truth; hiding someone does not remove them', 'Attendance is Occasion truth; mute, block, report are the viewer&rsquo;s', 'Seam 5 per-recipient readback', 'Delta to the Home owner; dependency marked'],",
     "    ['Home 42876b8c &middot; 10 (block state, as now drawn)', 'Home 10&rsquo;s block frame now reads &ldquo;quieter, not emptier; the count stands&rdquo;: attendance is the arrangement owner&rsquo;s fact (four), the blocked person is not shown and not removed, no banner, and it names the viewer-safe treatment as Social&rsquo;s to lead (provisional). Social&rsquo;s treatment, for the same recipient and branch: on the dinner page and in Home&rsquo;s occasion row the count is the arrangement&rsquo;s; the hidden person&rsquo;s row is simply absent for the viewer who hid them; nothing announces it; the host&rsquo;s page and everyone else&rsquo;s are unchanged; Fewer and Stop (08.5) are the same family and never touch attendance', 'Safe shared truth; hiding someone does not remove them', 'Attendance is Occasion truth; mute, hide, block, report are the viewer&rsquo;s', 'Seam 5 per-recipient readback', 'Reconciled with Home 10 as drawn; Home keeps the count, Social leads the viewer-safe rule; provisional until the arrangement owner rules'],"),
    ("    ['Home 42876b8c / Life e72a2fd2 &middot; casual non-spatial placement', 'A friend&rsquo;s original without a place arrives once in Home&rsquo;s addressed region when the share&rsquo;s audience includes you (08.1, two-item rule), opens to Life&rsquo;s exact-source reader (08.2), and is found again under the person (08.3); no pin, no feed, no social root; the spatial-social split stands for place-bound shares', 'Casual receiving without forcing a location', 'Accepted Home social split preserved; placement is a named proposal', 'Friends audience (proposal); seam 7 refind over a photo', 'Proposal to the Home and Life owners'],",
     "    ['Home 42876b8c / Life e72a2fd2 &middot; casual non-spatial placement', 'A friend&rsquo;s original without a place arrives once in Home&rsquo;s addressed region when the share&rsquo;s audience includes you (08.1, two-item rule), opens to Life&rsquo;s exact-source reader (08.2), and is found again under the person (08.3) as &ldquo;shared with you, while she leaves it&rdquo;, distinct from &ldquo;yours&rdquo;; no pin, no feed, no social root; nothing on the recipient&rsquo;s week; the spatial-social split stands for place-bound shares. Counterpoint from the Home review: the addressed region is for contributions addressed to the person and casual status relocates to Places; whether a friends-audience original is addressed material or casual status is Home&rsquo;s to decide', 'Casual receiving without forcing a location', 'Accepted Home social split preserved; placement is a named proposal', 'Friends audience (proposal); seam 7 refind over a photo; Life 04&rsquo;s shared-with-you masthead', 'Proposal to the Home and Life owners; the alternative (Places &middot; From friends, no pin) stays fair'],"),
    ("    ['Casual non-spatial placement (08.1&ndash;08.3): Home addressed region as arrival, Life &middot; People as the pull route', 'Proposed',",
     "    ['Frame budget: 29 storyboard slots against the 24-slot ceiling (board 08)', 'Unresolved scope discrepancy', 'The five continuation slots were asked for by the September 8 assignment and kept for this review; the ceiling was not amended. Either the ceiling moves or two frames fold (08.3 into 04.5&rsquo;s grammar; 08.4 into 02.2&rsquo;s); the founder decides'],\n    ['Casual non-spatial placement (08.1&ndash;08.3): Home addressed region as arrival, Life &middot; People as the pull route', 'Proposed',"),
    ("    sep8 = blk('SEPTEMBER 8 CONSOLIDATION &middot; CORRECTED AND CONTINUED',",
     "    sep9 = blk('SEPTEMBER 9 &middot; LOW-PRESSURE RECEIVING', N('<b>Corrected.</b> 08.1 no longer elevates Nora&rsquo;s opening onto Maya&rsquo;s week: no &ldquo;Saturday, pasta&rdquo; on the strip, no &ldquo;if it happens&rdquo; ending; the authored opening stays available and receiving can end with enjoyment and no response. 08.2 and 08.3 lost their doctrine lines (&ldquo;No place. Nothing here asks for one&rdquo;, &ldquo;Retrieval writes nothing&rdquo;); the original, its author, audience and lifetime carry the meaning, and Life&rsquo;s vocabulary is used: shared with you, while she leaves it, versus yours. '\n        '<b>Reconciled, for the same recipient and branch.</b> Home 10 as now drawn keeps the count at four and names the viewer-safe treatment as Social&rsquo;s to lead; the rule is in the root deltas below. Plans 05 D4 now reads &ldquo;Moved to eight &middot; Sam hasn&rsquo;t answered&rdquo; with the receipt &ldquo;Updated to 8:00 &middot; sent to Maya and Sam&rdquo;; 03.6 and the 03.7 variant say the same thing from Sam&rsquo;s side and Nora&rsquo;s dinner page carries the same pending state. Life 04&rsquo;s masthead &ldquo;Yours, and what others shared with you&rdquo; and its note that a path back does not imply kept govern 08.3; Life&rsquo;s manifest also asks that Sam&rsquo;s guest record be composed as Life 07&rsquo;s dinner now is (the originals shared to him plus his own account, never Nora&rsquo;s private account), which 04.6 and 08.5 already follow. '\n        '<b>Scope.</b> Board 08&rsquo;s five slots exceed the twenty-four-slot ceiling; recorded as an unresolved scope discrepancy in the status table, not claimed as compliance. <b>Still pending, unchanged:</b> guest identity and delivery, ongoing connection, source use, placement. No Friends audience or service is adopted here.'))\n    sep8 = blk('SEPTEMBER 8 CONSOLIDATION &middot; CORRECTED AND CONTINUED',"),
    ("    inner = comp + sep8 + closed +", "    inner = comp + sep9 + sep8 + closed +"),
    ("comp = blk('THE RECOMMENDED COMPOSITION &middot; SEPTEMBER 8',", "comp = blk('THE RECOMMENDED COMPOSITION &middot; SEPTEMBER 9',"),
])

# ───────────────────────────── gen_se · index, budget, stamp ─────────────────────────────
sub('gen_se.py', [
    ("STAMP = 'SEPTEMBER 8 CONSOLIDATION &middot; CORRECTED AND CONTINUED &middot; 2026-09-09'", "STAMP = 'SEPTEMBER 9 &middot; LOW-PRESSURE RECEIVING &middot; 2026-09-09'"),
    ("'NEW &middot; SEPTEMBER 8 ASSIGNMENT &middot; PROPOSED'", "'SEPTEMBER 9: opening not elevated onto the recipient&rsquo;s week; reader copy cleaned; five slots over the ceiling = UNRESOLVED SCOPE DISCREPANCY'"),
    ("September 8: five continuation slots on board 08, named by the consolidation assignment, drawn on existing families; no other frame was added.",
     "September 8 added board 08&rsquo;s five continuation slots at the assignment&rsquo;s request, so the route now holds 29 against a ceiling of 24. This is recorded as an unresolved scope discrepancy, not compliance: the ceiling was not amended, and the founder decides whether it moves or two frames fold."),
    ("'SEPTEMBER 8: corrections, continuations and owner deltas recorded above the &sect;15 close'", "'SEPTEMBER 9: reconciliation deltas for Home 10, Plans D4 and Life 04/07; the scope discrepancy in the status table'"),
])
print('patched; misses:', len(MISS)); [print('  MISS', p, o) for p, o in MISS]
