"""September 9 fresh six-project review (handoff §0, 2026-09-09 02:07): one exact-original route with an optional plain Keep; the placement extension settled against the September 5 amendment; Entity 04.08's automatic receipt excluded; 04.8's later benefit made concrete; work-left-per-person recorded."""
MISS = []
def sub(path, pairs):
    s = open(path).read()
    for old, new in pairs:
        n = s.count(old)
        if n == 1: s = s.replace(old, new)
        elif new in s: pass
        else: MISS.append((path, old[:90]))
    open(path, 'w').write(s)

# ───────────────────────────── gen_c6 · 08.2 the exact-original route; 08.3 kept vs accessible ─────────────────────────────
sub('gen_c6.py', [
    # 1 · the optional plain-language Keep, in the person's words; Reply and Ask stay separate
    ("    inner += sect('Where it lives') + gut('<div>' + entry('note', 'Nora', 'People') + entry('dining', 'Thursday, Sep 17', 'Time', last=True) + '</div>' + src('Hers &middot; to friends &middot; through Sunday'))\n    inner += gut(door('Ask about this') + src('Asks Vesper, not Nora'), top=16)\n    return phone2(inner)",
     "    inner += gut(f'<div style=\"display: flex; gap: 22px; align-items: center;\">{door(\"Keep this photograph\")}</div>' + src('A private copy, yours after her share ends.'), top=16)\n    inner += sect('Where it lives') + gut('<div>' + entry('note', 'Nora', 'People') + entry('dining', 'Thursday, Sep 17', 'Time', last=True) + '</div>' + src('Hers &middot; to friends &middot; through Sunday'))\n    inner += gut(door('Ask about this') + src('Asks Vesper, not Nora'), top=16)\n    return phone2(inner, active='Home')"),
    ("('THE PASTA, OPENED', 'THE EXACT SOURCE', 'Her photograph, her line, who, until when; Reply; Ask is private', 'LIFE&rsquo;S EXACT-SOURCE READER (R4 GRAMMAR) &middot; NO MAP POSITION INVENTED &middot; AVAILABLE WHILE SHE LEAVES IT, NOT KEPT BY OPENING &middot; RETURN RESTORES HOME&rsquo;S SCROLL')",
     "('THE PASTA, OPENED', 'THE EXACT SOURCE, AND THE ONE OPTIONAL KEEP', 'Her photograph, her line, who, until when; Reply to her; Ask privately; keep a copy if you want one', 'LIFE&rsquo;S EXACT-SOURCE READER (R4 GRAMMAR) &middot; THREE DISTINCT EFFECTS (ENTITY 12.4): CONTINUING SHARED ACCESS IS THE DEFAULT AND NEEDS NO KEEP; KEEP THIS PHOTOGRAPH IS A PRIVATE COPY UNDER HER GRANT, SHE IS NOT TOLD; KEEPING A PLACE IS A DIFFERENT ACT AND THERE IS NO PLACE HERE &middot; OPENING, REFINDING AND ENJOYING REQUIRE NO KEEP, AND NONE IS INFERRED FROM OPENING &middot; HOME-ORIGIN STACK PRESERVED: THE TAB BAR STAYS HOME, BACK RESTORES HOME&rsquo;S SCROLL &middot; RETENTION AGREEMENT PROPOSED, NOT ADOPTED')"),
    ("         ('Maya', 'The share', 'Open', 'Her line and the photograph, exactly', 'Same; Reply reaches Nora only', 'Life (original) / Contribution', 'Nora, if she replies', 'Back to Home, same scroll'), ('COPY OF R4&rsquo;S GRAMMAR', '02.5 / 02.6 TREATMENT REUSED', 'FIXTURE')),",
     "         ('Maya', 'The share', 'Open', 'Her line and the photograph, exactly; optionally a private copy', 'Same; Reply reaches Nora only; a Keep is not disclosed to her', 'Life (original) / Contribution', 'Nora, if she replies', 'Back to Home, same scroll'), ('COPY OF R4&rsquo;S GRAMMAR', '02.5 / 02.6 TREATMENT REUSED &middot; ENTITY 12.4&rsquo;S THREE EFFECTS, NOT ITS AUTOMATIC RECEIPT', 'KEEP CONTINUATION PROPOSED')),"),
    # 2 · 08.3 distinguishes deliberately kept from still-accessible
    ("    inner += bar('YOURS') + gut('<div>' + entry('photo', 'The Print Room', 'Thursday &middot; to friends') + entry('photo', 'The table', 'Saturday &middot; to Nora and Sam', last=True) + '</div>')",
     "    inner += bar('KEPT FROM NORA &middot; YOURS AFTER HER SHARE ENDS') + gut('<div>' + entry('photo', 'The pasta, second try', 'you kept this one, Thursday', last=True) + '</div>')\n    inner += bar('YOURS') + gut('<div>' + entry('photo', 'The Print Room', 'Thursday &middot; to friends') + entry('photo', 'The table', 'Saturday &middot; to Nora and Sam', last=True) + '</div>')"),
    ("('LATER &middot; LIFE &middot; PEOPLE', 'THE PULL ROUTE', 'Shared with you, while Nora leaves it; yours; held in common', 'COPY OF R3&rsquo;S GRAMMAR &middot; LIFE 04&rsquo;S &ldquo;YOURS, AND WHAT OTHERS SHARED WITH YOU&rdquo; &middot; A PATH BACK DOES NOT MEAN KEPT &middot; NO SOCIAL TAB, NO FEED')",
     "('LATER &middot; LIFE &middot; PEOPLE', 'THE PULL ROUTE, AND THE ONE DISTINCTION', 'Shared with you while Nora leaves it; the one you kept; yours; held in common', 'COPY OF R3&rsquo;S GRAMMAR &middot; LIFE 04&rsquo;S &ldquo;YOURS, AND WHAT OTHERS SHARED WITH YOU&rdquo; &middot; STILL ACCESSIBLE THROUGH HER SHARE AND DELIBERATELY KEPT ARE TWO ROWS, NOT ONE &middot; A PATH BACK DOES NOT MEAN KEPT &middot; NO SOCIAL TAB, NO FEED')"),
    # 3 · placement, settled against the September 5 amendment
    ("        ('THE DESTINATION', N('A friend&rsquo;s original that has no place arrives once in Home&rsquo;s addressed region when the share&rsquo;s audience includes you, under the same two-item rule 04.2 uses; it is not a new feed and not a social root. Opening it is Life&rsquo;s exact-source reader with Reply and a private Ask. The alternative, Places &middot; From friends without a pin, is fair for a person who lives in Places, but it asks a photograph of pasta to stand near a map.')),",
     "        ('THE EXTENSION, EXACTLY', N('The September 5 amendment already gives a casual share with no Place two homes: a Status doorway on Home while featured, and Life &middot; People after. 08 extends that permitted treatment in one step: the fuller original itself arrives once in Home&rsquo;s addressed region when the share&rsquo;s audience includes you (Friends eligibility as the arrival condition), under the same two-item rule 04.2 uses. That is the whole delta. It is not evidence that nonspatial social material had no home, not a new feed, not a social root, and no root is reopened. Place-bound shares still open in Places, and nothing is forced onto a map.')),\n        ('THE ORIGIN STACK', N('08.2 is a Life-owned source opened from Home, so it keeps its Home-origin stack: the tab bar stays on Home and Back restores Home&rsquo;s scroll. It becomes a Life page only if the person deliberately crosses roots, which 08.3 is. The alternative, Places &middot; From friends without a pin, is fair for a person who lives in Places, but it asks a photograph of pasta to stand near a map.')),"),
    ("        ('WHAT THIS DOES NOT DECIDE', N('The Friends audience remains the friends-audience proposal; this board assumes it as a fixture. The accepted spatial-social split stands: place-bound shares still open in Places. A change to accepted placement is this named proposal for the Home and Life owners, not a silent broadening. The Home review (September 8, &ldquo;with people&rdquo; kinds) keeps the addressed region for contributions addressed to the person and relocates casual status to Places by default; whether a friends-audience original counts as addressed material or casual status is the open point, and Home decides it.')),",
     "        ('WHAT THIS DOES NOT DECIDE', N('The Friends audience remains the friends-audience proposal; this board assumes it as a fixture. The retention agreement behind &ldquo;Keep this photograph&rdquo; is proposed, not adopted, and no grant is implemented here. The Home review (September 8, &ldquo;with people&rdquo; kinds) keeps the addressed region for contributions addressed to the person and relocates casual status to Places by default; whether a friends-audience original arrives as addressed material or as the featured-Status doorway is Home&rsquo;s call, and the delta above is written so either answer is a small change.')),\n        ('WHAT IS NOT INHERITED', N('Entity 04.08&rsquo;s automatic receipt (&ldquo;used in tonight &middot; she can see this use&rdquo;) stays out of this route: private use does not acquire a visibility consequence by being copied from a reference, and no reaction or sender consumption score exists anywhere here. Entity 12.4&rsquo;s three named effects are inherited; its useful / keep / send set does not replace human Reply, which stays in the action set beside the private Ask.')),"),
    ("'Two continuations the September 8 assignment named as missing from the selected experience: a friend&rsquo;s original that has no place, received, opened and found again; and where a guest returns after both people chose to stay in touch. Five slots beyond the twenty-four-slot ceiling, drawn on existing families and recorded on 00 and 07 as an unresolved scope discrepancy, not compliance; the placement is a named proposal, not a new destination.'",
     "'Two continuations the September 8 assignment named as missing from the selected experience: a friend&rsquo;s original that has no place, received, opened, optionally kept, and found again; and where a guest returns after both people chose to stay in touch. One exact-original route across Home and Life, with continuing shared access, a deliberate Keep and keeping a place kept apart. Five slots beyond the twenty-four-slot ceiling, drawn on existing families and recorded on 00 and 07 as an unresolved scope discrepancy, not compliance; the placement extends the September 5 Status-doorway permission and remains a named proposal.'"),
    ("        ('SOMETHING WITHOUT A PLACE', N('08.1 to 08.3 take board 05&rsquo;s D1-A (Nora&rsquo;s pasta and a line, to friends, no guest count) from its sender state to a recipient: it arrives once, opens to the exact source, and is found again under the person. No occasion, no pin, no reply owed. Nora&rsquo;s &ldquo;thinking of Saturday&rdquo; is her opening, not Maya&rsquo;s agenda: Maya&rsquo;s week does not change until she does something, and enjoying it with no response is a complete ending.')),",
     "        ('SOMETHING WITHOUT A PLACE', N('08.1 to 08.3 take board 05&rsquo;s D1-A (Nora&rsquo;s pasta and a line, to friends, no guest count) from its sender state to a recipient: it arrives once, opens to the exact source, and is found again under the person. No occasion, no pin, no reply owed. Nora&rsquo;s &ldquo;thinking of Saturday&rdquo; is her opening, not Maya&rsquo;s agenda: Maya&rsquo;s week does not change until she does something, and enjoying it with no response is a complete ending. The photograph itself is the benefit; no interpretation of it is produced or required before she can enjoy it.')),"),
])

# ───────────────────────────── gen_c4 · 04.8, one later benefit made concrete ─────────────────────────────
sub('gen_c4.py', [
    ("+ f'<div style=\"display: flex; gap: 18px; align-items: center; margin-top: 8px;\">{door(\"The table, last time\")}</div>' + meta('LAST TIME&rsquo;S PHOTO AND THE RAG&Ugrave;, ONE TAP AWAY &middot; NOBODY&rsquo;S OLD TIMING IS PREFILLED', 8)), top=16)",
     "+ f'<div style=\"display: flex; gap: 18px; align-items: center; margin-top: 8px;\">{door(\"The table, last time\")}</div>'\n                      + f'<div style=\"margin-top: 8px; padding-top: 8px; border-top: 1px solid rgba(27,23,20,0.08); font-size: 13px; line-height: 19px; color: {INK2};\">From last time: the address and the buzzer, that nothing is brought, the photograph, and Dana&rsquo;s rag&ugrave;.<br>Not from last time: who can come and when. Maya and Sam answer again.</div>'), top=16)"),
    ("<div style=\"font-size: 12px; line-height: 16px; color: {INK2};\">One line; the draft carries the place and the proposed start; the photo is one tap away.</div>",
     "<div style=\"font-size: 12px; line-height: 16px; color: {INK2};\">One line. The draft recovers the address, the buzzer, nothing-to-bring, the photograph and Dana&rsquo;s dish, and proposes last time&rsquo;s seven. Availability is the one thing it does not carry forward.</div>"),
    ("('TWO WEEKS LATER', 'ANOTHER PASTA EVENING', 'The last one&rsquo;s shape, reused with consent; fresh invitations', 'AUTHORIZED PRIOR MATERIAL REDUCES REPEATED EXPLANATION &middot; NEW OCCASION, NEW CHOICES &middot; NOTHING INHERITED')",
     "('TWO WEEKS LATER', 'ANOTHER PASTA EVENING', 'What last time supplies, named: the address, the buzzer, nothing to bring, the photograph, the dish; and what it does not: anyone&rsquo;s availability', 'AUTHORIZED PRIOR MATERIAL REDUCES REPEATED EXPLANATION &middot; OLD AVAILABILITY IS NEVER TREATED AS CURRENT &middot; ONE COMPARISON, NOT A MEMORY LOOP ASKED OF EVERY SHARE')"),
    ("('ANOTHER EVENING', N('04.8 restores the existing-relationship continuation: the last dinner&rsquo;s shape comes back from Nora&rsquo;s own record with one line, Maya and Sam get fresh invitations, nothing is inherited. The before/after strip shows the retyping it removes. The boat couple are a compact row on 04.4.')),",
     "('ANOTHER EVENING', N('04.8 restores the existing-relationship continuation, and now says exactly what the previous outcome supplies: the address and the buzzer, that nothing is brought, the table photograph and Dana&rsquo;s dish, plus last time&rsquo;s seven as a proposal. It equally says what it does not supply: anyone&rsquo;s availability, which Maya and Sam answer again. The before/after strip shows the retyping and the search it removes. This is one comparison; no share is asked to become a memory loop.')),"),
])

# ───────────────────────────── gen_c5 · board 07: the September 9 review, deltas, work left ─────────────────────────────
sub('gen_c5.py', [
    ("    sep9 = blk('SEPTEMBER 9 &middot; LOW-PRESSURE RECEIVING',",
     "    sep9b = blk('SEPTEMBER 9 &middot; FRESH SIX-PROJECT REVIEW', N('<b>One exact-original route (08.2, 08.3).</b> The reader now offers one optional, plainly worded Keep (&ldquo;Keep this photograph &middot; a private copy, yours after her share ends&rdquo;) beside human Reply and the private Ask, which stay separate choices. Entity 12.4&rsquo;s three effects are kept apart and only two exist here: continuing shared access, which is the default and needs no Keep, and a deliberate private copy under her grant, which she is not told about; keeping a place is the third and there is no place in this material. Nothing is inferred from opening, and refinding needs no Keep. 08.3 shows the distinction as two rows rather than one: shared with you while she leaves it, and kept from Nora. The retention agreement itself stays proposed. '\n        '<b>Placement, settled as an extension.</b> The September 5 amendment already gives a casual share with no Place two homes, a Status doorway on Home while featured and Life &middot; People after. The delta 08 asks for is one step from there: the fuller original itself arrives once in Home&rsquo;s addressed region when the audience includes the recipient (Friends eligibility as the condition). It is not a claim that nonspatial material had no home, no root is reopened, and nothing is forced onto a map. A Life-owned source opened from Home keeps its Home-origin stack: 08.2&rsquo;s tab bar stays Home and Back restores Home&rsquo;s scroll; 08.3 is the deliberate crossing. '\n        '<b>Entity 04.08, excluded pending a decision.</b> The automatic receipt (&ldquo;used in tonight &middot; she can see this use&rdquo;) is kept out of the selected route: private exploration must not acquire a visibility consequence by being copied from a reference. Entity&rsquo;s useful / keep / send set does not replace human Reply, which remains in every original-reader action set here. No reaction, no sender consumption score. '\n        '<b>04.8, the later benefit made concrete.</b> The draft now names what the authorized previous outcome supplies (the address and the buzzer, nothing to bring, the table photograph, Dana&rsquo;s dish, last time&rsquo;s seven as a proposal) and what it does not (anyone&rsquo;s availability, answered again). Old availability is never shown as current.'))\n    sep9 = blk('SEPTEMBER 9 &middot; LOW-PRESSURE RECEIVING',"),
    ("    inner = comp + sep9 + sep8 + closed +", "    inner = comp + sep9b + sep9 + sep8 + closed +"),
    ("comp = blk('THE RECOMMENDED COMPOSITION &middot; SEPTEMBER 9',", "comp = blk('THE RECOMMENDED COMPOSITION &middot; SEPTEMBER 9, LATER',"),
    # root deltas: Life keep-continuation, Entity exclusion, Home placement extension restated
    ("    ['Home 42876b8c / Life e72a2fd2 &middot; casual non-spatial placement', 'A friend&rsquo;s original without a place arrives once in Home&rsquo;s addressed region when the share&rsquo;s audience includes you (08.1, two-item rule), opens to Life&rsquo;s exact-source reader (08.2), and is found again under the person (08.3) as &ldquo;shared with you, while she leaves it&rdquo;, distinct from &ldquo;yours&rdquo;; no pin, no feed, no social root; nothing on the recipient&rsquo;s week; the spatial-social split stands for place-bound shares. Counterpoint from the Home review: the addressed region is for contributions addressed to the person and casual status relocates to Places; whether a friends-audience original is addressed material or casual status is Home&rsquo;s to decide', 'Casual receiving without forcing a location', 'Accepted Home social split preserved; placement is a named proposal', 'Friends audience (proposal); seam 7 refind over a photo; Life 04&rsquo;s shared-with-you masthead', 'Proposal to the Home and Life owners; the alternative (Places &middot; From friends, no pin) stays fair'],",
     "    ['Home 42876b8c &middot; placement, as an extension', 'September 5 already permits two homes for a casual share with no Place: a Status doorway on Home while featured, and Life &middot; People after. The delta is one step: the fuller original itself arrives once in Home&rsquo;s addressed region when the share&rsquo;s audience includes the recipient (Friends eligibility as the condition), under the two-item rule (08.1); nothing lands on the recipient&rsquo;s week. Either reading of the Home review, addressed material or the featured-Status doorway, is a small change from here', 'Casual receiving without forcing a location, and without a second social surface', 'The accepted social split and the four roots are unchanged; place-bound shares still open in Places', 'Friends audience (proposal)', 'Proposal to the Home owner; the alternative (Places &middot; From friends, no pin) stays fair'],\n    ['Home 42876b8c / Life e72a2fd2 &middot; the origin stack', 'A Life-owned source opened from Home keeps its Home-origin stack: 08.2 renders with Home active and Back restores Home&rsquo;s scroll; it becomes a Life page only when the person deliberately crosses roots (08.3)', 'One object, one reader, no root whiplash', 'Home borrows Life&rsquo;s pass grammar (September 5); unchanged', 'None', 'Adopt as drawn; return to both owners'],\n    ['Life e72a2fd2 &middot; the exact-original route and its one Keep', 'The reader offers one optional, plainly worded Keep (a private copy under the author&rsquo;s grant, not disclosed to her) beside Reply and the private Ask; continuing shared access is the default and needs no Keep; refinding infers nothing; 08.3 shows shared-with-you and kept as two rows (08.2, 08.3)', 'Enjoying and refinding cost nothing; retaining is a deliberate, legible act', 'Life&rsquo;s accessible-versus-deliberately-kept distinction, as asked', 'The retention agreement itself (proposed)', 'Return to the Life and Entity owners; agreement stays proposed'],\n    ['Entity dd48304b &middot; 04.08 / 12.4', 'Inherit 12.4&rsquo;s three distinct effects (keep the place, keep her words, send onward) as the vocabulary for the reader&rsquo;s action set; do not inherit 04.08&rsquo;s automatic receipt (&ldquo;used in tonight &middot; she can see this use&rdquo;) into the selected shared route, and never let private exploration acquire a visibility consequence by copying a reference; human Reply stays in the action set beside useful / keep / send', 'A private look stays private; the sender learns nothing she was not told', 'Social&rsquo;s exclusion of use reporting is unchanged', 'A consequential decision on whether any use is ever reported', 'Kept out pending that decision; returned to the Entity owner'],"),
    ("    ['Frame budget: 29 storyboard slots against the 24-slot ceiling (board 08)', 'Unresolved scope discrepancy',",
     "    ['The optional Keep on the exact-original reader (08.2) and its retention agreement', 'Proposed', 'Drawn as one plain door; the grant behind it is not adopted and is not implemented here'],\n    ['Entity 04.08&rsquo;s automatic use receipt', 'Excluded pending a decision', 'Kept out of the selected route; the decision belongs to the Entity owner and the founder'],\n    ['Frame budget: 29 storyboard slots against the 24-slot ceiling (board 08)', 'Unresolved scope discrepancy',"),
    # the work-left accounting
    ("    dec = blk('THE SIX DECISIONS',",
     "    work = blk('TOTAL WORK LEFT TO EACH PERSON &middot; ACROSS THE WHOLE EXPERIENCE', tbl(['PERSON', 'WHAT THEY MUST DO', 'WHAT THEY MAY DO', 'WHAT IS NEVER ASKED', 'IF THEY DO NOTHING'], WORKLEFT))\n    dec = blk('THE SIX DECISIONS',"),
    ("    inner = comp + sep9b + sep9 + sep8 + closed + changed + dec +", "    inner = comp + sep9b + sep9 + sep8 + closed + changed + work + dec +"),
    ("DECISIONS = [",
     """WORKLEFT = [
    ['Nora &middot; host, 14 slots', 'One sentence to host (03.1); one Send. On the day, nothing', 'Reply to Maya; ask privately; adopt or leave Maya&rsquo;s eight; answer Sam&rsquo;s connection request; send the boat photo; start another evening from one line (04.8)', 'No guest list to build, no address to retype, no thanks to collect, no recap to write, no reflection prompt', 'Seven stands, the dinner happens, the record still forms from what people did'],
    ['Maya &middot; friend, 3 slots', 'Nothing. She is a friend, not an operator', 'Share from an object with one line (02.2); propose eight once (03.5); contribute the photograph (04.1); take her note back (02.7, 04.9); receive Nora&rsquo;s pasta and keep it or not (08.1&ndash;08.3)', 'No acknowledgment owed, no read receipt, no reciprocal photo, no audience management after the fact', 'She keeps her photograph and her words; nobody is told she was quiet'],
    ['Dana &middot; elsewhere, 1 slot', 'Nothing. She is not attending', 'Send one thing to the dinner&rsquo;s people from an addressed line (03.3)', 'No membership, no address, no answers to give, no thank-you expected', 'Nothing happens and nothing is missing; her tip simply is not there'],
    ['Sam &middot; guest with no account, 5 slots', 'Open a link; answer once; confirm his number when the address is needed (03.2, 03.4)', 'Say his constraint in his own words; answer the changed time; look at the photograph later; seek a connection under Nora&rsquo;s name (04.6); ask for fewer or stop (08.5)', 'No app, no profile, no account, no reason for declining, no upgrade to a friendship to receive anything', 'He is a link-holder who never confirmed: the host sees no confirmed attendance, and nothing else happens'],
    ['The couple from the boat &middot; 1 note', 'Nothing at all', '&mdash;', 'They are never contacted by the product; only Nora&rsquo;s one promised email exists, through the address they gave', 'The record stands either way'],
]
DECISIONS = ["""),
])

# ───────────────────────────── gen_se · stamp, statuses, the asset recommendation ─────────────────────────────
sub('gen_se.py', [
    ("STAMP = 'SEPTEMBER 9 &middot; LOW-PRESSURE RECEIVING &middot; 2026-09-09'", "STAMP = 'SEPTEMBER 9 &middot; FRESH SIX-PROJECT REVIEW &middot; 2026-09-09'"),
    ("'SEPTEMBER 9: opening not elevated onto the recipient&rsquo;s week; reader copy cleaned; five slots over the ceiling = UNRESOLVED SCOPE DISCREPANCY'",
     "'SEPTEMBER 9, LATER: one exact-original route with an optional plain Keep; placement settled as an extension of the September 5 Status-doorway permission; five slots over the ceiling = UNRESOLVED SCOPE DISCREPANCY'"),
    ("'SEPTEMBER 9: reconciliation deltas for Home 10, Plans D4 and Life 04/07; the scope discrepancy in the status table'",
     "'SEPTEMBER 9, LATER: the exact-original route, the placement extension, Entity 04.08 excluded, 04.8 made concrete, and the work each person is left with'"),
    ("'SEPTEMBER 9: 04.6 names what Sam holds (Maya&rsquo;s photograph, the dinner&rsquo;s shared facts); Nora&rsquo;s account stays hers'",
     "'SEPTEMBER 9, LATER: 04.8 names what the previous evening supplies and what it does not; 04.6 names what Sam holds'"),
])
print('patched; misses:', len(MISS)); [print('  MISS', p, o) for p, o in MISS]
