"""09 · Revision log: the outside-phone change log the review asks for, item by item against §8, plus the seven review
criteria as a design-review self-assessment (not user testing)."""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from kit import *
from gen_generous import N
from gen_merge import tbl, blk
from gen_p2_common import *

def board():
    items = blk('WHAT CHANGED, AGAINST &sect;8', tbl(['&sect;', 'THE CRITIQUE', 'THE REVISION', 'WHERE'], [
        ['8.2 P0', 'Internal explanations inside phones', 'Removed from every phone: no measurement talk, no result-set announcements, no supply economics, no instructions about reading, no restoration notes. Material uncertainty stays in the person&rsquo;s words, once. A source line only where it matters to the decision', 'All boards; 01 guidance'],
        ['8.3 P0', 'Complete-on-view is not compelling', 'The world packet expanded to twelve things (food, music, outdoor, low-cost social, indoor, a spatial discovery). Three lead candidates compared on one packet; the recommended lead is a discovery a flat map hides, made usable by a free Saturday thing. The exhibition is one unit, not the identity of Places', '02'],
        ['8.4 P0', 'World abundance confused with personal history', 'World supply held constant: a newcomer and a mature account see the same twelve things; maturity changes selection and judgment. Thin supply kept. The fourth cell annotated', '07'],
        ['8.5 P1', 'Quotas, ceremonial endings, rejected inventory on display', 'No counts, no &ldquo;the collection ends here&rdquo;; &ldquo;Explore&rdquo; instead of &ldquo;Widen&rdquo;; further exploration within the same intent. A Saturday-evening question returns evening options only; exclusions appear when asked, selected or relied on. 08 C5 corrected', '02, 03, 07, 08'],
        ['8.6 P1', 'Control states drawn, not interactions', 'The control model: header (city, search, map), one question line (a pill with &times;, one context chip), a three-row sheet. One sequence: an ordinary constraint, a combined and empty scope, a chosen context, clearing; map and city preserved as stated. Proposed versus supported stated', '03; 01 B'],
        ['8.7 P0', 'Social receiving felt like an inspection', 'Illustrative pictures and naturally authored notes; eighteen contributions from six people grouped by where; the share opened with an immediate reply; a locally empty scope keeping the intent; quiet withdrawal with two treatments, one of them a repair. The &ldquo;nothing else is recomposed&rdquo; claim corrected', '04'],
        ['8.8 P0', 'An incoherent event and dinner', 'The hour is one recording heard whole, 7&ndash;9; dinner is 8:15. The answer names the overlap and what leaving early costs, offers three real ways including doing less, and asks one question. Chat, one send, back. One genuine change (last orders at 9) with what got worse, what stands and the one decision. One lens inside the phone; three compared outside', '06'],
        ['8.9 P1', 'Weak hierarchy; tiny metadata; content on 05', 'Supporting text 14/19 and meta 11 inside Places phones (flagged as a token proposal); dates and prices in readable sans; illustrations on leads and shares; a first-viewport marker beside the phone; long-names and 1.3&times; tests; 05 leads with one usable orientation sentence and five things to do, distance and time kept apart, Dana&rsquo;s note unglossed', '01, 02, 05'],
        ['8.10 P1', 'Engineering and cost handoff overstated', 'Result-set identity verified in code (scope + query; time and social source missing; map return to scope); labels corrected (social renderer exists as a sentence strip; the receiving view does not); dated event reclassified as a visual treatment with representation to verify; supply classes carry refresh responsibilities; the seat rule read as no duplicate promotion, not hidden content; changes reclassified by category', '01, 07, 08'],
        ['8.11', 'Order and acceptance', '02 and 07 first, then 04, then 06, then 03 and 05, then 01, 08, 00. The map-led versus content-led comparison is scheduled after this pass and stays a hypothesis', '00']]))
    pass2 = blk('THE FOCUSED JUDGMENT PASS, AGAINST &sect;9', tbl(['&sect;', 'THE CRITIQUE', 'THE REVISION', 'WHERE'], [
        ['9.2', 'Prefer the film-led candidate; understanding should support the possibility', 'The film leads 02 (and 07&rsquo;s newcomer and thin phones); the pier, its direction and sunset are folded into the card as what to expect and where to be beforehand; the discovery is kept as a comparison', '02, 07'],
        ['9.3', '&ldquo;With Maya&rdquo; overrode the time; it only reordered her places', 'Rebuilt around one authorized reason (a share the person kept to do together) inside Saturday evening: the pier at sunset, a place to talk, the same lawn after, the hour explained for two; the Print Room, which closes at six, is under &ldquo;Another time&rdquo; with the tradeoff said', '03 phone 7'],
        ['9.4', 'Historical venue context was discarded as not occurrence-specific', 'The combined state shows the hour&rsquo;s own facts with Sam&rsquo;s seat note beside them, labelled as about the hall and not this Saturday; a truly empty case (Sunday evening) is drawn beside it', '03 phones 6 and 2b'],
        ['9.5', 'Maturity produced a six-hour schedule', 'The mature phone leads with the same film; the pier is an option beforehand, the saved bakery a separate afternoon with its honest closing time; no stops are appointed', '07 phone 2'],
        ['9.6', 'Expired options listed as unaffected; &ldquo;that table is off&rdquo; implied a mutation; seating asserted', 'Every option re-read at 5:50 (low water over, the library was Friday); &ldquo;won&rsquo;t work for 9:30 now&rdquo;; agreement and adoption kept apart (the dinner still says 8:15 and stands); seating for three not confirmed, said so', '06 phone 4'],
        ['9.7', 'Friends read as local guides; Priya&rsquo;s line looked like a comment', 'Ordinary moments added (a two-word picture, a first loop, the pigeons, a return after ten years, two experiences of one recital); Priya&rsquo;s line labelled as her own separate visit, on the card and in the share view', '04'],
        ['9.8', 'From friends hidden inside the query controls; a vague search hint', 'A row with four faces and a count under the lead on the ordinary opening; the minimum path (open, tap, back at the same position) drawn; the hint is now &ldquo;A place, a time, a kind of evening&rdquo;', '02, 04, 07; 01 B'],
        ['9.9', 'Reconcile 00, 01, 08, 09 and the response doc', 'Done; the response doc marks its first-pass sections historical and points to the current recommendations', '00, 01, 08, this board']]))
    pass4 = blk('ADVANCE TO VISUAL AND INTERACTION COMPARISON, AGAINST &sect;11', tbl(['&sect;', 'THE CRITIQUE', 'THE REVISION', 'WHERE'], [
        ['11.3.1', '&ldquo;Move dinner there&rdquo; did not say where', 'The caf&eacute; is shown selected and the action reads &ldquo;Move dinner to the caf&eacute;, and tell Maya and Alex&rdquo;; not a booking, not a seating claim', '06 frame 5; 11 B6'],
        ['11.3.2', 'The return line described an earlier stage', 'After the update the line reads &ldquo;Dinner moved to 9:30, with Maya and Alex&rdquo;; &ldquo;asked&rdquo; only while a proposal is pending', '06 frame 4; 11 B5'],
        ['11.3.3', '&ldquo;Seats left tonight&rdquo; on a Friday view of a Saturday event', 'Anchored to the occurrence: &ldquo;Seats left for this Saturday haven&rsquo;t been confirmed&rdquo;, in the shared unit and the 03 lead', '02, 03, 06, 07, 10, 11'],
        ['11.4', 'Content-led versus map-led on the same evidence', 'Board 10: rich and sparse, same inventory, entry and media, first viewport marked, the toggle; observations recorded from the rendered frames; content-led recommended for the ordinary opening, map-led when orientation is the job; stated as observation, not validation', '10'],
        ['11.4', 'Two complete paths, shown and navigable', 'Board 11: ordered frames for Path A (opening, friends, share, reply, return) and Path B (possibility, question, update, change, exact action, readback). P1: the same frames tappable, hash-addressable; a static state switch', '11, P1'],
        ['11.5', 'Reconcile the index, decisions, log and response', 'Done; the current checkpoint is on 00 and in the response doc&rsquo;s &sect;10', '00, 08, this board']]))
    criteria = blk('THE SEVEN REVIEW CRITERIA &middot; A DESIGN-REVIEW SELF-ASSESSMENT, NOT USER TESTING', tbl(['', 'CRITERION', 'WHERE TO LOOK', 'HONEST STATE'], [
        ['1', 'Without annotations, can I tell what interests me and what I could do next?', '02 phones 1&ndash;3 with the notes column covered', 'Yes for B (the film) and A; C reads as an exhibition page'],
        ['2', 'Can I enjoy the visit without asking, saving, documenting, replying or planning?', '02, 04 sparse, 05', 'Yes; every phone ends without a demand'],
        ['3', 'Does more world supply produce more useful possibility even for a new account?', '07 phones 1 and 3', 'Yes; the newcomer&rsquo;s page is the full packet'],
        ['4', 'Can I alter time, place or social context without losing my exploration?', '03 row 2; 05 return; 06 back', 'Drawn; the identity to support time and social context is a gap'],
        ['5', 'Do friends feel like people sharing, rather than records with policy labels?', '04', 'Closer, and no longer only guides; fixture illustrations stand in for real pictures'],
        ['6', 'Does practical help preserve what makes the outing worthwhile?', '06 phone 1 and the change', 'Yes; the answer names the cost of leaving early, and the change invents no cancellation, availability or agreement'],
        ['7', 'Are the remaining cautions useful to the current decision rather than explanations of our architecture?', 'Every phone', 'Yes; one uncertainty per unit, in plain words']]))
    tokens = blk('THE ONE PROPOSED TOKEN CHANGE', N('Inside Places phones, supporting text is 14/19 (was 13/18 and 12.5/17) and the mono meta line is 11px (was 10). Kicks stay 10/700. This is applied by a finisher on every revised phone and is not in the shared kit; if adopted it should be adopted for all roots or explicitly scoped to Places.'))
    inner = (head(f'{STAMP} &middot; 09 &middot; REVISION LOG &middot; 09-07', '09 &middot; What the two critiques changed', 'The outside-phone change log, item by item against &sect;8 and then &sect;9; the seven review criteria as a self-assessment, which does not establish acceptance; the one proposed token change.')
             + '<div style="display: flex; flex-direction: column; gap: 34px;">' + items + pass2 + criteria + tokens + '</div>')
    return HEAD + f'<div style="width: 1560px; min-height: {hh("09", 2600)}px; background: #F4F0E7; box-sizing: border-box; padding: 30px 32px 36px 32px; {SANS} color: {INK}; display: flex; flex-direction: column;">' + inner + f'<div class="fn" style="margin-top: 30px; line-height: 16px;">{FOOT}</div></div>' + TAIL

if __name__ == '__main__':
    html = board(); open(os.path.join(OUT, '09 - Revision Log.dc.html'), 'w').write(html); print('wrote 09', len(html))
