"""00 · revised: index and status after the §8 revision; stale setup instructions removed."""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from kit import *
from gen_generous import N
from gen_merge import tbl, blk
from gen_p2_common import *

def board():
    assignment = blk('THE ASSIGNMENT', N('<b>Home brings forward what matters in my life. Places lets me explore what the world could offer &mdash; from here, somewhere else, or through my people.</b> One complete Places experience: world discovery, personal relevance, human perspectives, practical help. Social is part of it, not its purpose. Source: <b>docs/working/places-complete-experience-design-handoff-2026-09-07.md</b>; the September 7 critiques in its &sect;8&ndash;&sect;11 govern the current state. <b>Current checkpoint (&sect;11.5):</b> product direction carried forward; content and interaction specification corrected; the comparison and the two paths are on 10, 11 and P1 for the rendered visual review; visual design and implementation readiness remain to be established.'))
    boards = blk('BOARDS &middot; STATUS', tbl(['BOARD', 'WHAT IT SHOWS NOW', 'STATUS'], [
        ['01 - Design System', 'The kit as tested: composition guidance, the control model, units with illustrations, states, corrected code labels, the token proposal', 'Revised 09-07 (&sect;8, &sect;9)'],
        ['02 - A - The Ordinary Opening', 'A newcomer in an abundant city: the film leads with the pier folded in; two other candidates kept as comparisons; From friends as a row with faces; the opened detail; thin supply; long names; 1.3&times; text', 'Revised 09-07 (&sect;8, &sect;9.2, 9.8)'],
        ['03 - B - Something Saturday Evening', 'The question line, chip and sheet; evening options only; the map form; an ordinary constraint; friends context with a venue note labelled as such, and a truly empty case; &ldquo;with Maya&rdquo; as a shared possibility inside the evening; clearing', 'Revised 09-07 (&sect;8, &sect;9.3, 9.4)'],
        ['04 - C - Through My People', 'Twenty-odd contributions from six people, not only advice, grouped by where; another friend&rsquo;s separate visit labelled as such; the share opened with a reply; an empty scope; quiet withdrawal and a repair; the minimum path in and back', 'Revised 09-07 (&sect;8, &sect;9.7, 9.8)'],
        ['05 - D - Sorrento Before Arrival', 'The cliff, once; five worthwhile things; Dana unglossed; Capri opened; back to Sorrento', 'Revised 09-07 (&sect;8.9) &middot; follow-through'],
        ['06 - E - Taking It Forward', 'A coherent event and dinner; an honest answer; one prepared message, sent on tap, read back; one genuine change with every option re-read at the current time and no invented cancellation or agreement; one lens inside the phone', 'Revised 09-07 (&sect;8, &sect;9.6)'],
        ['07 - Abundance and Context', 'World supply held constant across a new and a mature account; maturity as judgment, not a schedule; thin supply kept; further exploration; supply classes with refresh', 'Revised 09-07 (&sect;8, &sect;9.2, 9.5)'],
        ['08 - Decisions, Reclassified', 'Recommendations with evidence; changes by category; implementation status verified; the seat rule as two expressions; dependencies', 'Revised 09-07 (&sect;8, &sect;9)'],
        ['09 - Revision Log', 'The change log against &sect;8, &sect;9, &sect;10 and &sect;11; the seven review criteria as a self-assessment; the token proposal', 'Current through &sect;11'],
        ['10 - Content-led vs Map-led', 'The same twelve things, entry and media, rich and sparse; the first viewport marked; the toggle; what each expression delivers, observed on rendered frames; a recommendation stated as an observation', 'Added 09-07 (&sect;11.4) &middot; CURRENT CHECKPOINT'],
        ['11 - Two Paths', 'Path A: opening, From friends, a share, a reply, return. Path B: possibility, question, dinner moved by its organizer, the change, the exact action, readback. Ordered rendered frames; interaction untested', 'Added 09-07 (&sect;11.4)'],
        ['P1 - Prototype - Two Paths', 'The same frames, one phone, tappable: doors and controls switch frames; the hash carries the frame. A static state switch, not an app', 'Added 09-07 (&sect;11.4) &middot; TAPS UNTESTED ON A DEVICE'],
        ['RA1, RA6, RA15, RS3, RH1, RE2', 'Six reference boards kept from the sibling projects; precedent, not adoption', 'Reference']]))
    fixture = blk('THE FIXTURE WORLD', N('The shared world (Maya, Alex, Theo, Dana; the bakery, the pier, the greenmarket) plus the venues the brief introduced (the Harbor Print Room and <i>Rooms Remade</i>, Canal Hall) and the venues the revision added (the film on the lawn, the noodle counter, the branch library, the old church, the caf&eacute; with the long table, the waterfront loop, two new friends, Priya and Sam). Sorrento uses its own synthetic packet. Every picture is an illustration and says so. No live availability is claimed anywhere.'))
    criteria = blk('HOW TO READ THE BOARDS &middot; THE REVIEW CRITERIA FROM &sect;8.11', N('Cover the notes columns and ask, for each phone: can I tell what interests me and what I could do next; can I enjoy the visit without asking, saving, documenting, replying or planning; does more world supply help a new account; can I change time, place or social context without losing my exploration; do friends feel like people sharing; does practical help protect the outing; are the remaining cautions useful to the decision. 09 records a self-assessment against each; it is not user testing.'))
    outside = blk('WHAT LIVES OUTSIDE THIS PROJECT', N('The brief and its &sect;8 critique: <b>docs/working/places-complete-experience-design-handoff-2026-09-07.md</b>. The response: <b>places-complete-experience-design-response-2026-09-07.md</b>. The anatomy: <b>places-consumer-experience-anatomy-2026-08-29.md</b>. The result-set contract: <b>places-result-set-context-contract-2026-09-05.md</b>. Code: <b>travel-app/components/places</b>, <b>travel-agent/backend/places/result_set.py</b>. Nothing here is a canon amendment or an implementation authorization.'))
    inner = (head(f'{STAMP} &middot; 00 &middot; INDEX &middot; REVISED 09-07', 'Vesper &mdash; Places', 'A focused investigation: one complete Places experience across five situations, revised after the September 7 first-export critique (&sect;8) and the focused judgment pass (&sect;9). 01 is the kit as tested; 02&ndash;06 are the situations; 07 the abundance comparison; 08 the decisions, reclassified; 09 the revision log; 10 the content-led versus map-led comparison; 11 and P1 the two paths, as frames and as a tappable prototype. Everything on every phone is a fixture, and nothing inside a phone explains the architecture.')
             + '<div style="display: flex; flex-direction: column; gap: 34px;">' + assignment + boards + fixture + criteria + outside + '</div>')
    return HEAD + f'<div style="width: 1560px; min-height: {hh("00", 1600)}px; background: #F4F0E7; box-sizing: border-box; padding: 30px 32px 36px 32px; {SANS} color: {INK}; display: flex; flex-direction: column;">' + inner + f'<div class="fn" style="margin-top: 30px; line-height: 16px;">{FOOT}</div></div>' + TAIL

if __name__ == '__main__':
    html = board(); open(os.path.join(OUT, '00 - Index.dc.html'), 'w').write(html); print('wrote 00 v2', len(html))
