#!/usr/bin/env python3
"""Verify Travel App/utils/api/http.ts only calls endpoints that exist in
docs/openapi.json (the backend's contract).

Catches drift in either direction:
  * DRIFT (FAIL): http.ts fetches a URL that the backend does not expose.
    This is a real bug — the frontend will get a 404 at runtime.
  * UNUSED (INFO): backend exposes a URL the frontend never calls.
    Often intentional (admin, internal, deprecated). Listed for review.

The check operates at the (METHOD, normalized-path) level. Path
parameters are normalized to ``{*}`` so ``/trips/{trip_id}`` matches
``/trips/${tripId}`` regardless of name differences.

Exit code 0 = pass; non-zero = drift.

Usage::

    python3 scripts/api-coverage-check.py
    python3 scripts/api-coverage-check.py --list-unused  # show backend-only paths

Allowlist: edit ``_INTENTIONAL_BACKEND_ONLY`` below for endpoints the
app legitimately doesn't surface (admin tools, scripts, etc.). Each entry
is matched against the normalized ``METHOD path`` string.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parent.parent
OPENAPI_SNAPSHOT = WORKSPACE_ROOT / "docs" / "openapi.json"
HTTP_TS = WORKSPACE_ROOT / "Travel App" / "utils" / "api" / "http.ts"

HTTP_METHODS = {"get", "post", "put", "patch", "delete"}

# Backend-exposed endpoints the app intentionally doesn't call. Each
# entry is the normalized ``METHOD path`` (path with ``{*}`` placeholders).
# Add an entry here ONLY when you've consciously decided the frontend
# should not surface this operation (admin tooling, dev-only routes,
# scripts).
_INTENTIONAL_BACKEND_ONLY: set[str] = {
    # Admin operator routes — accessed via tooling / dashboards, not the app.
    # Generated by listing /admin/* paths during the initial audit.
}


def _strip_ts_substitutions(s: str) -> str:
    """Replace each ``${...}`` template substitution with ``{*}``.

    Hand-rolled (not regex) because TS template substitutions can nest:
    ``/feed${qs ? `?${qs}` : ''}`` contains an outer ``${...}`` whose
    body contains another ``${...}``. A naive ``\\$\\{[^}]+\\}`` regex
    stops at the first ``}`` and corrupts the rest of the URL.
    """
    out: list[str] = []
    i = 0
    while i < len(s):
        if s[i : i + 2] == "${":
            depth = 1
            j = i + 2
            while j < len(s) and depth > 0:
                if s[j] == "{":
                    depth += 1
                elif s[j] == "}":
                    depth -= 1
                j += 1
            out.append("{*}")
            i = j
        else:
            out.append(s[i])
            i += 1
    return "".join(out)


def _normalize_path(p: str) -> str:
    """Reduce a path to a name-free, query-free, comparable form.

    ``/trips/{trip_id}/users/{user_id}`` → ``/trips/{*}/users/{*}``
    ``/trips/${tripId}/users/${userId}`` → ``/trips/{*}/users/{*}``
    ``/feed${qs ? `?${qs}` : ''}``       → ``/feed``
    ``/nearby?${qs}``                    → ``/nearby``
    """
    # 1. Replace TS template substitutions (handles nesting).
    p = _strip_ts_substitutions(p)
    # 2. Strip query string + fragment.
    p = p.split("?", 1)[0].split("#", 1)[0]
    # 3. Normalize OpenAPI-style {name} placeholders to {*}.
    p = re.sub(r"\{[^}]+\}", "{*}", p)
    # 4. Strip trailing {*} that's stuck to a path segment (a query-string
    # artifact like ``/feed{*}`` from ``/feed${qs ? ... : ''}``). A pure
    # ``{*}`` segment is a real path parameter and is left alone.
    parts = p.split("/")
    parts = [
        s[: -len("{*}")] if s.endswith("{*}") and s != "{*}" else s for s in parts
    ]
    return "/".join(parts)


def load_openapi_endpoints(snapshot: Path) -> set[tuple[str, str]]:
    """Return ``{(METHOD, normalized_path)}`` from the OpenAPI snapshot."""
    spec = json.loads(snapshot.read_text())
    out: set[tuple[str, str]] = set()
    for path, methods in spec.get("paths", {}).items():
        if not isinstance(methods, dict):
            continue
        for method, _ in methods.items():
            if method.lower() in HTTP_METHODS:
                out.add((method.upper(), _normalize_path(path)))
    return out


# Match ``_request<...>(URL, { ... method: 'X' ... })`` and
# ``_uploadFile<...>(URL, ...)``. URL can be a backtick template literal,
# a single-quoted string, or a double-quoted string. We capture the URL
# (without quotes) and (optionally) the second-arg block so a separate
# scan can pull the method.
_REQUEST_CALL = re.compile(
    r"""
    \b (?: _request | _uploadFile )            # the dispatch helpers
    \s* < [^>]* >                              # generic type arg
    \s* \(                                     # opening paren
    \s*
    (?:                                        # URL — one of three string forms
          ` ([^`]+) `                          #   backtick template (group 1)
        | ' ([^']+) '                          #   single-quoted (group 2)
        | " ([^"]+) "                          #   double-quoted (group 3)
    )
    (?:                                        # optional init-options arg
        \s* , \s*
        ( \{ .*? \} )                          # second-arg object literal (group 4)
    )?
    """,
    re.VERBOSE | re.DOTALL,
)

_METHOD_IN_INIT = re.compile(r"\bmethod\s*:\s*['\"]([A-Z]+)['\"]")


def load_http_endpoints(http_src: Path) -> set[tuple[str, str]]:
    """Return ``{(METHOD, normalized_path)}`` extracted from http.ts.

    ``_uploadFile`` defaults to POST; ``_request`` defaults to GET when
    no ``method:`` key appears in the init-options object.
    """
    src = http_src.read_text()
    out: set[tuple[str, str]] = set()

    for m in _REQUEST_CALL.finditer(src):
        url = m.group(1) or m.group(2) or m.group(3)
        init = m.group(4) or ""
        is_upload = src[m.start() : m.start() + 12].startswith("_uploadFile")

        method_match = _METHOD_IN_INIT.search(init)
        if method_match:
            method = method_match.group(1).upper()
        elif is_upload:
            method = "POST"
        else:
            method = "GET"

        out.add((method, _normalize_path(url)))

    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--list-unused",
        action="store_true",
        help="Print backend-only endpoints (informational).",
    )
    args = parser.parse_args()

    if not OPENAPI_SNAPSHOT.exists():
        print(f"ERROR: OpenAPI snapshot missing at {OPENAPI_SNAPSHOT}", file=sys.stderr)
        return 2
    if not HTTP_TS.exists():
        print(f"ERROR: http.ts missing at {HTTP_TS}", file=sys.stderr)
        return 2

    backend = load_openapi_endpoints(OPENAPI_SNAPSHOT)
    frontend = load_http_endpoints(HTTP_TS)

    drift = frontend - backend
    unused = backend - frontend - {
        tuple(entry.split(" ", 1)) for entry in _INTENTIONAL_BACKEND_ONLY if " " in entry
    }

    print(f"Backend OpenAPI endpoints: {len(backend)}")
    print(f"Frontend http.ts call sites (unique): {len(frontend)}")
    print(f"Covered: {len(frontend & backend)}")
    print(f"Drift (frontend calls a URL the backend does not expose): {len(drift)}")
    print(f"Backend-only (app does not surface): {len(unused)}")

    if drift:
        print("\nDRIFT — frontend calls these URLs but they are not in OpenAPI:")
        for method, path in sorted(drift):
            print(f"  {method:6}  {path}")
        print("\nFix the frontend call site, or update docs/openapi.json (and sync-types).")

    if args.list_unused and unused:
        print("\nBackend-only endpoints (informational):")
        for method, path in sorted(unused):
            print(f"  {method:6}  {path}")

    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main())
