#!/usr/bin/env python3
"""Generate the persona-certification block in docs/journeys/STATUS.md.

Single source of truth for per-journey *seeded-world* pass/fail. Runs
``travel-agent/scripts/dogfood_journey_persona_cert.py`` for each seeded
persona (token-free, ``AI_MODE=replay``) and rewrites only the auto-generated
block between the ``BEGIN auto:persona-cert`` / ``END auto:persona-cert``
markers in STATUS.md. The human Matrix above it (Static / Mock-walk / Logic /
Maestro / Live / Certified — sourced from many gates) is hand-owned and never
touched here.

    python scripts/sync_journey_status.py             # regenerate the block in place
    python scripts/sync_journey_status.py --check      # CI drift guard: exit 1 if stale
    python scripts/sync_journey_status.py --personas mara,elif

Needs a dogfood-seeded Postgres — the same substrate the persona gate uses.
If a requested persona is unseeded / the certifier errors, this aborts WITHOUT
writing, so a partial run can never corrupt the committed block.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

import yaml

_REPO_ROOT = Path(__file__).resolve().parent.parent
_AGENT_ROOT = Path(os.environ.get("JOURNEY_AGENT_ROOT", _REPO_ROOT / "travel-agent")).resolve()
_STATUS_MD = _REPO_ROOT / "docs" / "journeys" / "STATUS.md"
_AI_MODE = "replay"
_DEFAULT_PERSONAS = ("mara", "elif")


def _agent_python() -> str:
    """The travel-agent venv interpreter (so `make` works without a pre-activated
    venv); falls back to whatever python is running this script."""
    venv = _AGENT_ROOT / ".venv" / "bin" / "python"
    return str(venv) if venv.exists() else sys.executable

def _manifest_journey_ids() -> tuple[str, ...]:
    manifest = yaml.safe_load((_REPO_ROOT / "docs" / "journeys" / "journeys.yaml").read_text())
    return tuple(journey["id"] for journey in manifest.get("journeys", []))


_ALL_JOURNEYS = _manifest_journey_ids()
_UNMAPPED_REASON = "not mapped to a seeded persona — covered by logic + mock-walk gates"
_STATUS_GLYPH = {"pass": "✅ pass", "fail": "🔴 fail", "skip": "⤵️ skip"}

_BEGIN = "<!-- BEGIN auto:persona-cert (generated by scripts/sync_journey_status.py — DO NOT EDIT) -->"
_END = "<!-- END auto:persona-cert -->"
_MX_BEGIN = "<!-- BEGIN auto:journey-matrix (generated by scripts/sync_journey_status.py — DO NOT EDIT) -->"
_MX_END = "<!-- END auto:journey-matrix -->"


class CertError(RuntimeError):
    """A persona certifier did not produce a clean, parseable result."""


def _run_persona_cert(persona: str, journey: str = "all") -> list[dict]:
    """Run the certifier for one persona and return its journey rows.

    Raises CertError on missing script, subprocess failure, non-zero exit, or
    unparseable JSON — so a partial/unseeded run never silently degrades the
    committed block.
    """
    script = _AGENT_ROOT / "scripts" / "dogfood_journey_persona_cert.py"
    if not script.exists():
        raise CertError(f"certifier missing: {script}")

    cmd = [
        _agent_python(),
        "scripts/dogfood_journey_persona_cert.py",
        "--persona",
        persona,
        "--journey",
        journey,
        "--json",
    ]
    env = {**os.environ, "AI_MODE": _AI_MODE, "PYTHONPATH": "."}
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(_AGENT_ROOT),
            env=env,
            capture_output=True,
            text=True,
            timeout=900,
        )
    except subprocess.SubprocessError as exc:  # timeout etc.
        raise CertError(f"{persona}: certifier errored: {exc}") from exc

    try:
        data = json.loads(proc.stdout)
    except (json.JSONDecodeError, ValueError) as exc:
        raise CertError(
            f"{persona}: unparseable certifier output (exit {proc.returncode}); "
            f"stderr: {proc.stderr.strip()[-200:]}"
        ) from exc

    journeys = data.get("journeys", [])
    if not journeys:
        raise CertError(f"{persona}: certifier returned no journeys (unseeded DB?)")
    # A non-zero exit means a real journey FAILED — surface it as data (the block
    # renders 🔴), not as an abort: a fail is a true result worth committing.
    return journeys


def _collect(personas: tuple[str, ...]) -> dict[str, dict]:
    """Merge each persona's runnable journeys into one {id: row} map, then fetch
    the real skip status+reason for any journey no persona ran (so STATUS.md
    shows the certifier's actual skip_reason, not a generic placeholder).
    Aborts on cross-persona overlap."""
    merged: dict[str, dict] = {}
    for persona in personas:
        for row in _run_persona_cert(persona):
            jid = row.get("id")
            if jid in merged:
                raise CertError(
                    f"journey {jid} mapped to two personas "
                    f"({merged[jid]['persona']} + {persona}) — fix the persona map"
                )
            merged[jid] = {**row, "persona": persona}

    # Non-runnable / unmapped journeys surface only under an explicit --journey.
    # Fetch each one's real skip row (persona-agnostic — runs under any persona).
    for jid in _ALL_JOURNEYS:
        if jid in merged:
            continue
        if not personas:
            continue
        try:
            rows = _run_persona_cert(personas[0], journey=jid)
        except CertError:
            continue  # leave it absent → build_block renders "not run"
        if rows:
            merged[jid] = {**rows[0], "persona": "—"}
    return merged


def build_block(personas: tuple[str, ...], by_id: dict[str, dict]) -> str:
    rows = [
        "| # | Persona | Trip | Status | Invariant |",
        "|---|---|---|---|---|",
    ]
    ran = passed = 0  # ran = lived-certified (pass|fail); skips are not "ran"
    skipped: list[str] = []
    unmapped: list[str] = []
    for jid in _ALL_JOURNEYS:
        row = by_id.get(jid)
        if row is None:
            rows.append(f"| {jid} | — | — | not run | {_UNMAPPED_REASON} |")
            unmapped.append(jid)
            continue
        status = row.get("status", "fail")
        glyph = _STATUS_GLYPH.get(status, status)
        reason = row.get("reason") or ""
        invariant = row.get("invariant", "")
        detail = f"{invariant} — {reason}" if reason else invariant
        rows.append(
            f"| {jid} | {row['persona']} | {row.get('trip', '')} | {glyph} | {detail} |"
        )
        if status == "skip":
            skipped.append(jid)
        else:
            ran += 1
            if status == "pass":
                passed += 1

    table = "\n".join(rows)
    persona_list = " + ".join(personas)
    notes = []
    if skipped:
        notes.append(f"{len(skipped)} skipped ({', '.join(skipped)})")
    if unmapped:
        notes.append(f"{len(unmapped)} unmapped ({', '.join(unmapped)})")
    note_suffix = (" · " + " · ".join(notes)) if notes else ""
    return (
        f"{_BEGIN}\n"
        "### Persona journey certification (auto-generated)\n\n"
        f"Source: `dogfood_journey_persona_cert.py --json` for {persona_list} "
        "(seeded world, `AI_MODE=replay`, token-free). Regenerate: "
        "`make dogfood-status-sync`. Drift guard: `make dogfood-status-sync CHECK=1`.\n\n"
        f"{table}\n\n"
        f"**Persona-cert summary:** {passed} / {ran} lived-certified journeys pass{note_suffix}.\n"
        f"{_END}"
    )


def _visual_ids() -> set[str]:
    """Journey IDs that have a dedicated Maestro flow.

    Convention: `.maestro/NN-journey-JJ-*.yaml` where NN is the flow number
    and JJ is the two-digit journey number (e.g. `24-journey-02-create-invite.yaml` → J02).
    Only flows whose filename contains `journey-NN` are counted; generic surface
    flows (trips-home, plan, discover …) are not journey-labelled and not counted.
    """
    maestro_dir = _REPO_ROOT / "travel-app" / ".maestro"
    if not maestro_dir.exists():
        return set()
    import re

    visual: set[str] = set()
    for p in maestro_dir.glob("*-journey-*.yaml"):
        m = re.search(r"journey-(\d{2})", p.name)
        if m:
            visual.add(f"J{m.group(1)}")
    return visual


def _branch_anchor_state(anchor: str, by_id: dict[str, dict]) -> str:
    """Return pass/fail/missing for one registered branch evidence anchor."""
    if anchor.startswith("persona-cert:"):
        jid = anchor.removeprefix("persona-cert:")
        row = by_id.get(jid)
        if row is None or row.get("status") == "skip":
            return "missing"
        return "pass" if row.get("status") == "pass" else "fail"
    return "pass" if (_REPO_ROOT / anchor).exists() else "missing"


def _branch_fidelity_cell(journey: dict, code: str, by_id: dict[str, dict]) -> str | None:
    """Summarize registered branch evidence for one fidelity.

    All anchors listed for a branch/fidelity are required. An empty list is an
    explicit gap. Returns None when this journey has no branch manifest for the
    requested fidelity, allowing the legacy parent-level signal during migration.
    """
    branches = [
        branch
        for branch in journey.get("branches", [])
        if code in branch.get("required_evidence", [])
    ]
    if not branches:
        return None

    passed = 0
    failed = False
    for branch in branches:
        anchors = branch.get("evidence", {}).get(code, [])
        states = [_branch_anchor_state(anchor, by_id) for anchor in anchors]
        if states and all(state == "pass" for state in states):
            passed += 1
        if "fail" in states:
            failed = True

    total = len(branches)
    if failed:
        return f"🔴 {passed}/{total}"
    if passed == total:
        return f"✅ {passed}/{total}"
    if passed:
        return f"◐ {passed}/{total}"
    return f"— 0/{total}"


def build_matrix_block(by_id: dict[str, dict]) -> str:
    """Generated fidelity Matrix for the WHOLE journey set (from journeys.yaml):
    rows = every journey; columns = contract(FE)/logic(BE) derived from which
    test files exist, + visual (Maestro dedicated flow) + lived from the
    persona-cert results in ``by_id``. This replaces the old hand-typed Matrix —
    always accurate, covers J13–J19."""
    from check_journey_registry import _be_test_ids, _fe_mockwalk_ids

    manifest = yaml.safe_load((_REPO_ROOT / "docs" / "journeys" / "journeys.yaml").read_text())
    journeys = manifest.get("journeys", [])
    fe, be, visual = _fe_mockwalk_ids(), _be_test_ids(), _visual_ids()
    lived_glyph = {"pass": "✅", "fail": "🔴", "skip": "⤵️"}

    rows = [
        "| # | Journey | Tier | Contract (FE) | Logic (BE) | Visual (Maestro) | Lived (persona-cert) |",
        "|---|---|---|---|---|---|---|",
    ]
    for j in journeys:
        jid = j["id"]
        lived_row = by_id.get(jid)
        if lived_row is None:
            lived = "—"
        else:
            lived = lived_glyph.get(lived_row.get("status", ""), lived_row.get("status", "—"))
        tier = {
            "golden-path": "golden",
            "holistic-extension": "holistic",
            "customer-extension": "customer",
        }.get(j.get("tier"), j.get("tier", "—"))
        contract = _branch_fidelity_cell(j, "FE", by_id)
        logic = _branch_fidelity_cell(j, "BE", by_id)
        visual_cell = _branch_fidelity_cell(j, "VIS", by_id)
        lived_cell = _branch_fidelity_cell(j, "LIVE", by_id)
        rows.append(
            f"| {jid} | {j['title']} | {tier} | "
            f"{contract or ('✅' if jid in fe else '—')} | "
            f"{logic or ('✅' if jid in be else '—')} | "
            f"{visual_cell or ('✅' if jid in visual else '—')} | "
            f"{lived_cell or lived} |"
        )
    table = "\n".join(rows)
    return (
        f"{_MX_BEGIN}\n"
        "### Journey fidelity matrix (auto-generated)\n\n"
        "Source: `docs/journeys/journeys.yaml` × registered branch evidence where "
        "declared; legacy rows use FE mock-walk / BE pytest / dedicated Maestro "
        "file presence × live persona-cert. "
        "Regenerate: `make dogfood-status-sync`. Set integrity: `make journey-registry-check`. "
        "Legend: ✅ all required branches · ◐ partial · ⤵️ skip · 🔴 fail · — none.\n\n"
        f"{table}\n"
        f"{_MX_END}"
    )


def _splice(source: str, block: str, begin: str, end: str) -> str:
    """Replace the existing marker block, or insert after the human '## Matrix'."""
    if begin in source and end in source:
        pre = source[: source.index(begin)]
        post = source[source.index(end) + len(end) :]
        return f"{pre}{block}{post}"

    # First-time insert: drop the block right after the hand-owned Matrix table.
    anchor = "\n## Matrix\n"
    if anchor not in source:
        raise CertError("STATUS.md has no '## Matrix' section to anchor the block")
    start = source.index(anchor) + len(anchor)
    next_heading = source.find("\n## ", start)
    cut = next_heading if next_heading != -1 else len(source)
    return f"{source[:cut]}\n{block}\n{source[cut:]}"


def _current_block(source: str, begin: str, end: str) -> str | None:
    if begin not in source or end not in source:
        return None
    return source[source.index(begin) : source.index(end) + len(end)]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--personas",
        default=",".join(_DEFAULT_PERSONAS),
        help="comma-separated seeded personas (default: mara,elif)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the committed block is stale (CI drift guard)",
    )
    args = parser.parse_args()
    personas = tuple(p.strip() for p in args.personas.split(",") if p.strip())

    if not _STATUS_MD.exists():
        print(f"✗ STATUS.md not found: {_STATUS_MD}", file=sys.stderr)
        return 2

    try:
        by_id = _collect(personas)
    except CertError as exc:
        print(f"✗ persona-cert sync aborted: {exc}", file=sys.stderr)
        return 2

    source = _STATUS_MD.read_text()
    blocks = [
        ("persona-cert", build_block(personas, by_id), _BEGIN, _END),
        ("journey-matrix", build_matrix_block(by_id), _MX_BEGIN, _MX_END),
    ]

    if args.check:
        stale = [
            name
            for name, block, begin, end in blocks
            if (cur := _current_block(source, begin, end)) is None or cur.strip() != block.strip()
        ]
        if stale:
            print(
                f"✗ STATUS.md auto block(s) STALE or missing: {', '.join(stale)} — "
                "regenerate with `make dogfood-status-sync` and commit.",
                file=sys.stderr,
            )
            return 1
        print("✓ STATUS.md auto blocks (persona-cert + journey-matrix) up to date.")
        return 0

    updated = source
    for _name, block, begin, end in blocks:
        updated = _splice(updated, block, begin, end)
    _STATUS_MD.write_text(updated)
    fails = sum(1 for r in by_id.values() if r.get("status") == "fail")
    print(
        f"✓ Wrote persona-cert + journey-matrix blocks to "
        f"{_STATUS_MD.relative_to(_REPO_ROOT)} ({len(by_id)} journeys, {fails} failing)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
