#!/usr/bin/env python3
"""Generate the persona-certification block in docs/journeys/STATUS.md.

Single source of truth for per-journey *seeded-world* pass/fail. Runs
``travel-agent/scripts/dogfood_journey_persona_cert.py`` for each seeded
persona (token-free, ``AI_MODE=replay``) and rewrites only the auto-generated
block between the ``BEGIN auto:persona-cert`` / ``END auto:persona-cert``
markers in STATUS.md. The human Matrix above it (Static / Mock-walk / Logic /
Maestro / Live / Certified — sourced from many gates) is hand-owned and never
touched here.

    python scripts/sync_journey_status.py             # regenerate the block in place
    python scripts/sync_journey_status.py --check      # CI drift guard: exit 1 if stale
    python scripts/sync_journey_status.py --personas mara,elif

Needs a dogfood-seeded Postgres — the same substrate the persona gate uses.
If a requested persona is unseeded / the certifier errors, this aborts WITHOUT
writing, so a partial run can never corrupt the committed block.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_AGENT_ROOT = _REPO_ROOT / "travel-agent"
_STATUS_MD = _REPO_ROOT / "docs" / "journeys" / "STATUS.md"
_AI_MODE = "replay"
_DEFAULT_PERSONAS = ("mara", "elif")


def _agent_python() -> str:
    """The travel-agent venv interpreter (so `make` works without a pre-activated
    venv); falls back to whatever python is running this script."""
    venv = _AGENT_ROOT / ".venv" / "bin" / "python"
    return str(venv) if venv.exists() else sys.executable

_ALL_JOURNEYS = [f"J{n:02d}" for n in range(1, 20)]
_UNMAPPED_REASON = "not mapped to a seeded persona — covered by logic + mock-walk gates"
_STATUS_GLYPH = {"pass": "✅ pass", "fail": "🔴 fail", "skip": "⤵️ skip"}

_BEGIN = "<!-- BEGIN auto:persona-cert (generated by scripts/sync_journey_status.py — DO NOT EDIT) -->"
_END = "<!-- END auto:persona-cert -->"


class CertError(RuntimeError):
    """A persona certifier did not produce a clean, parseable result."""


def _run_persona_cert(persona: str, journey: str = "all") -> list[dict]:
    """Run the certifier for one persona and return its journey rows.

    Raises CertError on missing script, subprocess failure, non-zero exit, or
    unparseable JSON — so a partial/unseeded run never silently degrades the
    committed block.
    """
    script = _AGENT_ROOT / "scripts" / "dogfood_journey_persona_cert.py"
    if not script.exists():
        raise CertError(f"certifier missing: {script}")

    cmd = [
        _agent_python(),
        "scripts/dogfood_journey_persona_cert.py",
        "--persona",
        persona,
        "--journey",
        journey,
        "--json",
    ]
    env = {**os.environ, "AI_MODE": _AI_MODE, "PYTHONPATH": "."}
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(_AGENT_ROOT),
            env=env,
            capture_output=True,
            text=True,
            timeout=900,
        )
    except subprocess.SubprocessError as exc:  # timeout etc.
        raise CertError(f"{persona}: certifier errored: {exc}") from exc

    try:
        data = json.loads(proc.stdout)
    except (json.JSONDecodeError, ValueError) as exc:
        raise CertError(
            f"{persona}: unparseable certifier output (exit {proc.returncode}); "
            f"stderr: {proc.stderr.strip()[-200:]}"
        ) from exc

    journeys = data.get("journeys", [])
    if not journeys:
        raise CertError(f"{persona}: certifier returned no journeys (unseeded DB?)")
    # A non-zero exit means a real journey FAILED — surface it as data (the block
    # renders 🔴), not as an abort: a fail is a true result worth committing.
    return journeys


def _collect(personas: tuple[str, ...]) -> dict[str, dict]:
    """Merge each persona's runnable journeys into one {id: row} map, then fetch
    the real skip status+reason for any journey no persona ran (so STATUS.md
    shows the certifier's actual skip_reason, not a generic placeholder).
    Aborts on cross-persona overlap."""
    merged: dict[str, dict] = {}
    for persona in personas:
        for row in _run_persona_cert(persona):
            jid = row.get("id")
            if jid in merged:
                raise CertError(
                    f"journey {jid} mapped to two personas "
                    f"({merged[jid]['persona']} + {persona}) — fix the persona map"
                )
            merged[jid] = {**row, "persona": persona}

    # Non-runnable / unmapped journeys surface only under an explicit --journey.
    # Fetch each one's real skip row (persona-agnostic — runs under any persona).
    for jid in _ALL_JOURNEYS:
        if jid in merged:
            continue
        try:
            rows = _run_persona_cert(personas[0], journey=jid)
        except CertError:
            continue  # leave it absent → build_block renders "not run"
        if rows:
            merged[jid] = {**rows[0], "persona": "—"}
    return merged


def build_block(personas: tuple[str, ...], by_id: dict[str, dict]) -> str:
    rows = [
        "| # | Persona | Trip | Status | Invariant |",
        "|---|---|---|---|---|",
    ]
    ran = passed = 0  # ran = lived-certified (pass|fail); skips are not "ran"
    skipped: list[str] = []
    unmapped: list[str] = []
    for jid in _ALL_JOURNEYS:
        row = by_id.get(jid)
        if row is None:
            rows.append(f"| {jid} | — | — | not run | {_UNMAPPED_REASON} |")
            unmapped.append(jid)
            continue
        status = row.get("status", "fail")
        glyph = _STATUS_GLYPH.get(status, status)
        reason = row.get("reason") or ""
        invariant = row.get("invariant", "")
        detail = f"{invariant} — {reason}" if reason else invariant
        rows.append(
            f"| {jid} | {row['persona']} | {row.get('trip', '')} | {glyph} | {detail} |"
        )
        if status == "skip":
            skipped.append(jid)
        else:
            ran += 1
            if status == "pass":
                passed += 1

    table = "\n".join(rows)
    persona_list = " + ".join(personas)
    notes = []
    if skipped:
        notes.append(f"{len(skipped)} skipped ({', '.join(skipped)})")
    if unmapped:
        notes.append(f"{len(unmapped)} unmapped ({', '.join(unmapped)})")
    note_suffix = (" · " + " · ".join(notes)) if notes else ""
    return (
        f"{_BEGIN}\n"
        "### Persona journey certification (auto-generated)\n\n"
        f"Source: `dogfood_journey_persona_cert.py --json` for {persona_list} "
        "(seeded world, `AI_MODE=replay`, token-free). Regenerate: "
        "`make dogfood-status-sync`. Drift guard: `make dogfood-status-sync CHECK=1`.\n\n"
        f"{table}\n\n"
        f"**Persona-cert summary:** {passed} / {ran} lived-certified journeys pass{note_suffix}.\n"
        f"{_END}"
    )


def _splice(source: str, block: str) -> str:
    """Replace the existing marker block, or insert after the human '## Matrix'."""
    if _BEGIN in source and _END in source:
        pre = source[: source.index(_BEGIN)]
        post = source[source.index(_END) + len(_END) :]
        return f"{pre}{block}{post}"

    # First-time insert: drop the block right after the hand-owned Matrix table.
    anchor = "\n## Matrix\n"
    if anchor not in source:
        raise CertError("STATUS.md has no '## Matrix' section to anchor the block")
    # Insert after the Matrix table — before the next '##' heading following it.
    start = source.index(anchor) + len(anchor)
    next_heading = source.find("\n## ", start)
    cut = next_heading if next_heading != -1 else len(source)
    return f"{source[:cut]}\n{block}\n{source[cut:]}"


def _current_block(source: str) -> str | None:
    if _BEGIN not in source or _END not in source:
        return None
    return source[source.index(_BEGIN) : source.index(_END) + len(_END)]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--personas",
        default=",".join(_DEFAULT_PERSONAS),
        help="comma-separated seeded personas (default: mara,elif)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the committed block is stale (CI drift guard)",
    )
    args = parser.parse_args()
    personas = tuple(p.strip() for p in args.personas.split(",") if p.strip())

    if not _STATUS_MD.exists():
        print(f"✗ STATUS.md not found: {_STATUS_MD}", file=sys.stderr)
        return 2

    try:
        by_id = _collect(personas)
    except CertError as exc:
        print(f"✗ persona-cert sync aborted: {exc}", file=sys.stderr)
        return 2

    block = build_block(personas, by_id)
    source = _STATUS_MD.read_text()

    if args.check:
        current = _current_block(source)
        if current is None:
            print(
                "✗ STATUS.md is missing the auto:persona-cert block — run "
                "`make dogfood-status-sync`.",
                file=sys.stderr,
            )
            return 1
        if current.strip() != block.strip():
            print(
                "✗ STATUS.md persona-cert block is STALE — regenerate with "
                "`make dogfood-status-sync` and commit.",
                file=sys.stderr,
            )
            return 1
        print("✓ STATUS.md persona-cert block is up to date.")
        return 0

    _STATUS_MD.write_text(_splice(source, block))
    fails = sum(1 for r in by_id.values() if r.get("status") == "fail")
    print(
        f"✓ Wrote persona-cert block to {_STATUS_MD.relative_to(_REPO_ROOT)} "
        f"({len(by_id)} mapped journeys, {fails} failing)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
