"""07 · Components: every piece of the Places kit as used on 01 to 04, at phone width, with its name, where it comes from, and when it is used."""
from fix import *
from kinds import *
import gen21, gen22
import instruments as I
def cell(name, origin, html, use, w=393, status='DRAWN'):
    sc = {'DRAWN': GOLDD, 'ADAPTED': OX, 'NEW': INK}.get(status, GOLDD)
    return (f'<div style="width: {w}px; flex: none; display: flex; flex-direction: column; gap: 8px;">'
            f'<div style="display: flex; align-items: baseline; gap: 10px;"><span style="{MONO} font-size: 11px; font-weight: 700; letter-spacing: 1.1px; color: {INK};">{name}</span><span class="fn" style="color: {GOLDD};">{origin}</span><span class="fn" style="margin-left: auto; color: {sc};">{status}</span></div>'
            f'<div style="width: {w}px; background: {PAPER}; border-radius: 12px; padding: 18px 0; box-sizing: border-box; {SANS} color: {INK};">{html}</div>'
            f'<div style="font-size: 12.5px; line-height: 17px; color: {MUTE};">{use}</div></div>')
G = lambda h: gut(h)
def strip(inner): return inner
def swatch(name, hexv, dark=False): return f'<div style="display: flex; flex-direction: column; gap: 6px; width: 84px;"><div style="height: 44px; border-radius: 10px; background: {hexv}; border: 1px solid rgba(27,23,20,0.10);"></div><span class="fn" style="color: {ANCHOR};">{name}</span><span class="fn" style="color: {GHOST};">{hexv}</span></div>'
def chrome():
    return [cell('anchor', 'kit · Home', anchor('NEW YORK', 'FRIDAY 5:40 PM') + orientation('The pier at sunset, then the film on the lawn. Saturday.', 'From Maya&rsquo;s share · Sunset Park'), 'Every field opens this way: a mono scope with the city&rsquo;s chevron, the time, the map; then the serif sentence that is the weekend and one muted line under it. Content before chrome.'),
            cell('anchor · back', 'kit · Home', anchor('MOVE DINNER?', 'SATURDAY', back=True, sub='With Maya and Alex') + G(f'<div style="margin-top: 18px;">{title("A page opened from the field", 20, 25, 600)}</div>'), 'A page opened from the field: the chevron back, the page&rsquo;s name as the scope, its one-line sub, the time and the map unchanged.'),
            cell('ask', 'Places', ask() + ask(q='Near Red Hook, Saturday') + ask(q='Saturday evening', ctx='Around dinner'), 'The question as a quiet hairline row, not a box: empty; with a question typed; with a question and a context. Chips are ink pills with a cross.'),
            cell('section · kick · tab bar', 'kit · Home', sect('Any day', 0) + G(kick('SATURDAY, IN THE LIGHT · FROM MAYA&rsquo;S SHARE')) + f'<div style="margin-top: 18px;">{TABBAR}</div>', 'A section is sans 13 with a hairline; a kick inside a section is mono gold with a hairline. The tab bar is the app&rsquo;s, Places lit.')]
def rows():
    return [cell('row · serif', 'kit · Home', G('<div>' + prow('The noodle counter', 'HAND-PULLED · NO WAIT BEFORE 12:30 · CASH', first=True) + prow('The Harbor Print Room', 'TUE–SUN 11–6 · ROOMS REMADE, TO SUNDAY', unc(UNK_ROOM)) + prow('The waterfront loop', 'FIVE KILOMETRES, FLAT · SHADED AFTER 2', last=True) + '</div>'), 'The everyday row: a serif name, one mono fact line, a chevron; an unconfirmed line in muted sans when something is not known. No thumbnail.'),
            cell('row · numbered', 'Places', G(redhook_rows(True)), 'The pocket&rsquo;s places, numbered to match the map; the number is an ink disc with a mono numeral, never a person.'),
            cell('row · people', 'kit · Home', G('<div>' + arow('Priya · the greenmarket · ' + dim('the pigeons have a system · Saturday'), avatars=['P']) + arow('Sam · Canal Hall · ' + dim('sit on the left, that&rsquo;s where the speakers are'), avatars=['S'], last=True) + '</div>' + f'<div style="margin-top: 14px;">{people_row(["M", "A"], "Dinner with Maya and Alex", "Saturday 8:15 · the noodle counter · yours")}</div>'), 'A person as the subject: a solid ink disc with a white initial, the line in ink with the rest dimmed. The people row is the arrangement&rsquo;s strip: a facepile, the name, one line of state.'),
            cell('doors', 'kit · Home', G(door('The pier') + doors(('Ask Maya and Alex about 8:45', GOLDD), ('Change the wording', MUTE)) + door_list(['Another neighborhood', 'Sunday, all day'])), 'A continuation is a text arrow at 13/500: gold for the primary, muted for the secondary; one per line, or a pair on one line where the second is the quiet alternative. Never a pill.')]
def human():
    return [cell('note · carded', 'canon · focus_human_note', G(card(author_row('M', 'Maya', 'THURSDAY · TO FRIENDS') + quote(MAYA_ROOM) + place_strip('The Harbor Print Room', 'RED HOOK · TUE–SUN 11–6') + door('Reply to Maya'))), 'A friend&rsquo;s contribution: the author row, her words in serif, the place it concerns as a strip, one door. The only card that carries a person&rsquo;s words.'),
            cell('note · bare · share row', 'Places', G(author_row('P', 'Priya', 'SATURDAY · TO FRIENDS') + quote(PRIYA_PIGEONS) + place_strip('The greenmarket', 'DOWNTOWN · SATURDAY 8–1')) + G('<div style="margin-top: 16px;">' + share_row('T', 'Theo', 'TUESDAY', THEO_BREAD, 'THE GREENMARKET · DOWNTOWN', last=True) + '</div>'), 'The same contribution on the paper when it is not the lead; and the From friends list row: disc, name, when, the words at 15, the place as a fact line.'),
            cell('readback', 'canon · execution_ledger', G(readback('SENT', 'Asked Maya and Alex about 8:45 · Friday 12:34 PM · no answer yet') + '<div style="height: 12px;"></div>' + readback('MOVED', 'Dinner · Saturday 8:45 · the noodle counter · Maya and Alex notified · 2:10 PM') + '<div style="height: 12px;"></div>' + readback('CHANGED · 5:40 PM', 'The noodle counter stops taking orders at 9 tonight', OX)), 'One line of state after an effect: the state as a mono label, the fact in sans. Sent is not arranged; notified appears only after the move; a change names its source.'),
            cell('composer · ask · answer', 'Places · Chat', G(composer('Reply', 'Saturday afternoon, then? I want the side room.', to='TO MAYA') + '<div style="height: 12px;"></div>' + bubble('is it ticketed? and can I get there by ferry on Saturday?') + '<div style="height: 12px;"></div>' + answer('Whether Rooms Remade is ticketed hasn&rsquo;t been confirmed; the workshop is open Tuesday to Sunday, 11 to 6.')), 'The composer says who receives it above the field. A private question to Vesper is an umber bubble; the answer is serif on the paper.')]
def cards():
    return [cell('card · prepared message', 'kit · Home', G(card(f'<div class="kickm">TO MAYA AND ALEX · NOT SENT</div><div style="{SERIF} font-size: 17px; line-height: 24px; color: {INK}; margin-top: 8px;">{gen21.MSG}</div>')), 'A message not yet sent: the recipients and the state as a kick, the words in serif. Home&rsquo;s card, with a shadow and no border.'),
            cell('sequence rail', 'canon · seq_strip', G(card(title('Saturday, in order', 20, 25, 600) + fn('FROM MAYA&rsquo;S SHARE, TUESDAY', 4) + seq_strip([('7:04', 'The pier at sunset', 'The west pier faces it; it turns cold fast.', '9 MIN ON FOOT TO THE LAWN'), ('8:30', 'Playtime on the lawn by the pier', 'Tati&rsquo;s city of glass, free.', '')]))), 'A prepared possibility as a sequence: time, a node on a gold line, the name, one detail, the leg between. Order is the explanation. Not used on 01 since the arc took its place; kept for arrangements.'),
            cell('browse shelf', 'canon · field_browse_shelf', G(browse_shelf([('The noodle counter', 'Hand-pulled at the counter', 'CASH'), ('The lunch counter on Columbia Street', 'One plate a day · standing room', 'TILL 4')], 'ANY DAY · SIX PLACES')), 'The everyday six as pairs: a hatched photo slot, a sans name, one line, one mono chip. Photo or hatch, never a drawing.'),
            cell('photo slot · cover · ghost rows', 'canon', G(photo_plate(120) + '<div style="height: 12px;"></div>' + cover(None, 'READING · 6 MIN', 'The working waterfront that refused to close', 150) + '<div style="height: 12px;"></div>' + ghost_rows(2)), 'A photo slot is a hatched plate with its label. The editorial cover is the same slot with a gradient and the reading&rsquo;s kick and title. Ghost rows stand for results not yet back.')]
def instruments():
    return [cell('the day line', 'instruments.py · from times', G(kick('SATURDAY · THE PIER, THEN THE LAWN') + I.pier_line()), 'The whole day on one track: the light as a gold wash from sunrise to sunset, the pier as the gold pill at its end, the film as ink after dark, low water as a bracket below. Two labels; the sentence carries the rest. Positions come from the times. Replaced the two-curve chart on September 8.'),
            cell('the evening', 'instruments.py · from times', G(gen21.band_evening([('20:45', 'DINNER 8:45', 'ring'), ('21:00', '', 'dot')], right='LAST ORDERS 9 · CAFÉ TILL 11')), 'The evening on one track from times, not pixels: the hour as the gold block, dinner as the ring, a change as the dot; a mark&rsquo;s label moves right, or to the end, when it would collide.'),
            cell('burden strip', 'canon · instruments', G(burden_strip()), 'Movement only: dots on foot, the crossing as one solid bar, and the moving total, which is what the number means and all it means. The headway sits on the bar; the wait it implies is drawn apart in the comparison below and never folded in here. The strip sits under every map.'),
            cell('two ways in', 'instruments.py · one minutes scale, from a named origin', G(I.access_compare([('SUNSET PARK', [(3, 'foot'), (2, 'wait'), (20, 'ride'), (9, 'foot')], 'THE N OR R · 32 MOVING, 2 DRAWN, EVERY 4'), ('RED HOOK', [(6, 'foot'), (20, 'wait'), (25, 'ride'), (9, 'foot')], 'THE FERRY · 40 MOVING, 20 DRAWN, EVERY 40')], origin='FROM CANAL STREET')), 'Two access structures on one minutes scale from a named origin: dots on foot, a dashed bar for waiting, a solid bar for the ride; each row prints moving+wait for the one wait drawn, which is a scenario and not a range; the possible total follows from the headway and is named in the row&rsquo;s own line. Waiting is drawn apart from movement so the decisive premise is visible.'),
            cell('the flood section', 'instruments.py · ground to scale', G(g.FLOOD(130)), 'Ground to scale: the pier on the creek bed, the 1911 sill 0.6 m above it, the harbor at high water between the two; water shows only where the ground is below it; the bar says how tall the drawing is.'),
            cell('the cliff section', 'instruments.py · the same renderer', G(I.section([(0, 40), (150, 40), (180, 36), (200, 0), (330, 0)], 0.3, [(4, 47, 'THE TOWN · THE READING ROOM', 'start', INK), (206, 7, 'THE QUAY · SEA LEVEL', 'start', INK)], scale_m='m', h=118, zmax=54)), 'Sorrento with the same renderer: 180 metres on the map, forty metres down.'),
            cell('map · fragment', 'Places · 01', G(REDHOOK_MAP), 'The one map: land and water, two streets, the pier&rsquo;s shape, a ferry glyph at the landing, gold-ringed numbers. Illustrative geometry, not routing; the next step is a fragment cut from real map data.'),
            cell('map · unavailable · pending', 'Places · 03', G(f'<div style="height: 72px; border-radius: 12px; background: {WASH}; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 3px; text-align: center; padding: 0 20px;"><div style="font-size: 14px; font-weight: 600; color: {INK};">The map isn&rsquo;t available right now</div><div style="font-size: 13px; color: {MUTE};">Everything here is still here</div></div>') + f'<div style="margin: 14px 22px 0 22px; height: 2px; border-radius: 1px; background: rgba(27,23,20,0.08); position: relative;"><div style="position: absolute; left: 0; top: 0; height: 2px; width: 38%; border-radius: 1px; background: {GOLDD};"></div></div>', 'The map&rsquo;s slot when the map fails: one line, in the slot, not a banner. The progress hairline under the question when results are pending.')]

def field_more():
    return [cell('branch lead', 'canon · field_branch_lead', G(branch_lead()), 'Three ways into the same afternoon, each with a different access structure; a hatched glyph plate, a sans name, one line. For a field that opens onto neighbourhoods rather than places.', status='NEW'),
            cell('returned understanding', 'canon · field_returned_understanding', G(returned_understanding()), 'Something learned elsewhere, applied here: one kick, one serif sentence, one door. The only Europe on a New York page, and the reason Places is one root across cities.', status='NEW'),
            cell('provenance label', 'canon · provenance_label', G(provenance_label() + f'<div style="margin-top: 14px;">{serifline("The pier at sunset, then the film on the lawn. Saturday.", 20, 26)}</div>'), 'When Places is reached from Home, one mono line says where the envelope came from; navigational, never a consumer tab.', status='NEW'),
            cell('balanced fallback', 'canon · field_balanced_fallback', G(f'<div style="height: 60px; border-radius: 12px; background: {WASH}; display: flex; align-items: center; justify-content: center;"><span class="fn" style="color: {MUTE};">A QUIET SATURDAY · NOTHING LEADS</span></div>' + '<div style="margin-top: 12px;">' + prow('The greenmarket', 'SATURDAY 8–1 · DOWNTOWN', first=True) + prow('Playtime on the lawn by the pier', '8:30 · FREE · SUNSET PARK', last=True) + '</div>'), 'No strong lead need not mean no value: a worthwhile neutral field of plain rows, with no backstage label and no invented recommendation.', status='DRAWN')]
def focus():
    return [cell('identity map', 'canon · focus_identity_map', G(identity_map()), 'The place page&rsquo;s map: the one place as an ink disc with a gold ring, the landing as a dot with its minutes; water, two streets, nothing else. The map is the object, never a provider tile.', status='NEW'),
            cell('verdict · basis', 'canon · focus_verdict · why_this', G(verdict('Go on a weekday for the side room; Saturday for the crossing itself.', 'MAYA AND PRIYA · HOURS FROM THE LISTING · TICKETING UNCONFIRMED')), 'One serif claim and the mono line that says what it rests on and what is unconfirmed. Uncarded; conviction is earned by the basis, not by a container.', status='NEW'),
            cell('hours register · change', 'The Page', G(hours_register([('HOURS', 'Tue–Sun 11–6'), ('THE EXHIBITION', 'Rooms Remade, to Sunday'), ('TICKETS', 'Not confirmed either way')], change='Closed today for a private event; posted this morning on the workshop&rsquo;s listing. Sunday is unchanged.')), 'The facts as a register: mono keys, sans values, a hairline each. A change is a strip with its source; the register never argues.', status='ADAPTED'),
            cell('trace · horizon doors', 'canon · focus_relationship_trace · focus_horizon_doors', G(relationship_trace('Kept Tuesday, from Maya&rsquo;s share.', 'NOT YET VISITED') + '<div style="margin-top: 16px;">' + horizon_doors([('ACCESS', 'The ferry against the B61: what each asks of the afternoon'), ('AROUND', 'The pier and the pool, from the landing')]) + '</div>'), 'Your relationship to the place as one readback, only when there is positive continuity to show; a newcomer gets no &ldquo;nothing yet&rdquo; slot. Typed edges with a stated relation; a causal or historical relation is allowed, not only nearby.', status='NEW'),
            cell('possibility row · stub', 'canon · focus_possibility_row · The Page', G(possibility_row('The Red Hook pool, before', 'Lap swim, then the Print Room at 11', 'SATURDAY 7–8:30 AM · BRING A LOCK') + '<div style="margin-top: 18px;">' + stub('The old ferry waiting room', 'Benches, the harbor, usually nobody.') + '</div>'), 'A nearby possibility with one reason and one burden, on the same edge as the rows around it; no plate, since an empty slot earns nothing. A stub is a place with little known: what is known, and a plain line saying that is all.', status='ADAPTED')]
def path_live():
    return [cell('evidence apparatus', 'canon · path_evidence_apparatus', G(evidence_apparatus('WHY VESPER THINKS THIS', ['Rooms Remade closes Sunday; Saturday is the last day the crossing and the exhibition line up', 'The workshop closes at 6; a 2:00 ferry leaves two hours upstairs and the walk', 'Maya and Priya both went on weekdays, for the empty rooms'])), 'Why, as a numbered list of facts in ink; gold numerals. Vertical, at most three; never a paragraph.', status='NEW'),
            cell('consequence · next rows', 'canon · path_consequence · path_next_rows', G(consequence('WHAT THIS CHANGES SATURDAY', 'The Print Room by 2:30, the crossing back at 5:10; the pier at sunset is another neighborhood.') + next_rows(['The pier, faces the harbor and the Statue', 'The lunch counter on Columbia Street, till 4'], places=True)), 'What the fact changes, in one serif sentence; then at most two typed next steps as rows with arrows.', status='NEW'),
            cell('temporal posture · fallback', 'canon · live_temporal_posture · live_fallback', G(temporal_posture('HOLD', 'Nothing needs booking. The ferry is every 40 minutes; the workshop holds no times.', 'NOTHING TO CONFIRM') + '<div style="margin-top: 16px;">' + temporal_posture('ACT NOW', 'Sunday is the last day; the 11:20 ferry puts you upstairs by noon.', 'SUNDAY, THE LAST DAY') + '</div>' + '<div style="margin-top: 16px;">' + live_fallback('IF THE EXHIBITION IS TICKETED AND SOLD OUT', 'The workshop floor is open without a ticket; the pier and the pool are the afternoon.') + '</div>'), 'The day&rsquo;s posture as one state with a dot: hold, act now, done; small status, never gamified. The fallback keeps the intention and drops the fixed edge.', status='NEW'),
            cell('burden receipt · plural comparison', 'canon · live_burden_receipt · social_plural_comparison', G(burden_receipt('WHAT THE CROSSING ASKS', 'ON FOOT', '9 minutes from the landing, level, exposed along the water') + '<div style="margin-top: 16px;">' + plural_comparison((('M', 'Maya', 'THURSDAY'), 'THE SIDE ROOM', MAYA_ROOM), (('P', 'Priya', 'A RAINY TUESDAY'), 'THE BACK ROOM', 'The back room to myself for an hour.')) + '</div>'), 'The receipt is evidence of what a route asks, not a second action surface. Two people on one place, side by side; neither becomes a taste profile.', status='NEW')]
def omitted():
    return [notecol('Taken, adapted, left out', [
        ('TAKEN FROM THE UNION AND THE PAGE', N('Twenty-two kinds now have a drawing on the chosen terms: the twelve on the first rows of this sheet and the ten on the rows above. Eleven of them are used on 08, the place page, which is why they exist; the rest are drawn once here for a page that will need them.')),
        ('ADAPTED', N('The hours register and the stub come from The Page (August 8) with their prose removed. The canon&rsquo;s solid action seams, on the field and the page, are drawn as text doors, per the founder&rsquo;s choice against the pill. The why-this inspector is the basis line under a verdict, not a separate door.')),
        ('EXCLUSIONS NARROWED · SEPTEMBER 9', N('Two universal exclusions are withdrawn: &ldquo;surfacing what you were not looking for is Home&rsquo;s job&rdquo; and &ldquo;never explain why a note matters&rdquo;. The Product Model (§3) admits causal, historical, cultural, relational and counterfactual understanding on Places. The restraint stays: the flood mechanism, the access comparison and the returned understanding are the forms it takes; nothing explanatory is added everywhere, and social placement is unchanged.')),
        ('LEFT OUT, WITH THE REASON', tbl(['KIND', 'WHY NOT'], [['Candidate set, candidate rows, &ldquo;Add to day&rdquo;', 'The plan surface those served was retired with the Home pivot; adding to a day is a mechanism'], ['The stage, the arrangement side by side, the arrangement set', 'Arrangements are Plan&rsquo;s and Home&rsquo;s; Places shows one arrangement as a strip and a readback, never edits it'], ['The lag register, as a module', 'Left out as a module only. The connection it carried is not: an earned causal, historical, cultural or relational connection may arrive as a returned understanding or as one line under a note, when it changes what the person notices (08.7, 01&rsquo;s Worth understanding). Not every place gets one'], ['Relational relevance, as a universal line', 'Left out as a rule for every note. When the connection is Vesper&rsquo;s contribution and not a restatement of the note, one sentence may say why it bears on this place; usually the note and its place carry it and nothing is added'], ['Search and map affordances as a toolbar', 'The question is a quiet line; the map is one glyph in the anchor'], ['Live instrument as a sequence', 'The sequence rail exists for arrangements; on a place page the day band and the posture carry time']]))], w=1180)]
def tokens():
    sw = '<div style="display: flex; gap: 12px; flex-wrap: wrap;">' + ''.join(swatch(n, v) for n, v in [('INK', INK), ('INK 2', INK2), ('MUTE', MUTE), ('ANCHOR', ANCHOR), ('GHOST', GHOST), ('GOLD', GOLD), ('GOLD DARK', GOLDD), ('UMBER', UMBER), ('OX', OX), ('WATER', WATER), ('CARD', CARD), ('WASH', WASH), ('PAPER', PAPER), ('BOARD', BOARD)]) + '</div>'
    ty = ('<div style="display: flex; flex-direction: column; gap: 10px;">' + f'<div style="{SERIF} font-weight: 600; font-size: 30px; line-height: 34px; letter-spacing: -0.01em;">Serif 30/34 · the orientation</div>' + title('Serif 20/25 · a page title', 20, 25, 600) + title('Serif 17/22 · a unit title', 17, 22) + title('Serif 16/21 · a row name', 16, 21)
          + f'<div style="font-size: 15px; line-height: 20px;">Sans 15/20 · a people row, a shelf name at 600</div><div style="font-size: 14px; line-height: 19px; color: {INK2};">Sans 14/19 · body</div><div style="font-size: 13px; line-height: 18px; color: {MUTE};">Sans 13/18 · supporting, unconfirmed</div><div style="font-size: 12.5px; line-height: 17px; color: {MUTE};">Sans 12.5/17 · the line under the orientation</div>'
          + f'<div style="{MONO} font-weight: 700; font-size: 11px; letter-spacing: 1.15px;">MONO 11 · THE ANCHOR, A READBACK LABEL</div><div class="fn" style="color: {ANCHOR};">MONO 10 · A FACT LINE, AN INSTRUMENT LABEL · THE FLOOR</div></div>')
    rad = '<div style="display: flex; gap: 14px; align-items: flex-end;">' + ''.join(f'<div style="display: flex; flex-direction: column; gap: 6px; align-items: center;"><div style="width: 64px; height: 44px; border-radius: {r}px; background: {CARD}; border: 1px solid rgba(27,23,20,0.14);"></div><span class="fn" style="color: {ANCHOR};">{l}</span></div>' for r, l in [(18, '18 · CARD'), (14, '14 · MAP'), (12, '12 · PLATE, SLOT'), (10, '10 · GHOST'), (999, '999 · DISC, CHIP')]) + '</div>'
    return [cell('colour', 'kit', G(sw), 'Ink for words and now; gold for the plan; umber for you and the private bubble; ox for a change; water for the harbor; card, wash, paper and board as the four grounds.', w=832),
            cell('type', 'kit', G(ty), 'Three voices: serif reads, sans operates, mono stamps. Ten pixels is the floor, inside instruments included.'),
            cell('radius', 'kit', G(rad), 'Five radii and nothing else declares a corner.')]
def board():
    notes = [notecol('How to read this sheet', [('WHAT IT IS', N('Every piece the seven boards use, rendered once at phone width from the same generator that draws them (docs/working/design-gen/places/kit3.py and the instruments in gen19v3.py). The origin beside each name says where the piece comes from: Home&rsquo;s kit, the a26e3228 canon&rsquo;s kinds and instruments, or Places itself.')), ('WHAT IT IS NOT', N('Not a design system and not a token rollout; nothing here is shared with Home, Chat or Life by being drawn here. The proposed Places-scoped tokens remain proposals in the response doc.')), ('HISTORICAL, NOT CURRENT', N('The a26e3228 specimen sheets, The Page of August 8 (f4eee076) and the Entity lab&rsquo;s invariant-body page (dd48304b 09, 11, 12) are references this sheet drew from, not current rules. The current rule for what a place page reads is the selected column of the table on 08 (purpose-responsive reading under an invariant shell). Where a drawing here and one there disagree, 08 governs.')), ('RULES CARRIED', N('Photo or hatch, never a drawing. One instrument per unit, its labels off its lines, at the 10px mono floor. Serif names, mono facts. Solid discs for people, ink numerals for map places. Text arrow doors, one primary where the content calls for one. No design doctrine inside a phone.'))], w=760)]
    return rows_page(1900, '07 · COMPONENTS · 09-09', '07 · Components', 'Every piece of the Places kit at phone width: chrome, rows, human units, cards and kinds, instruments; then the field, focus, path, live and social kinds taken from the a26e3228 union and The Page and drawn on the chosen terms, marked drawn, adapted or new; what was left out and why; tokens. The place page on 08 is where the new kinds are used.',
                     [('CHROME', 'The anchor, the sentence, the question, the sections', chrome()), ('ROWS AND DOORS', 'Serif rows, numbered rows, people, continuations', rows()), ('HUMAN UNITS', 'Notes, readbacks, the composer, the private question', human()), ('CARDS AND KINDS', 'The prepared message, the rail, the shelf, the slots', cards()), ('INSTRUMENTS · FROM DATA', 'The pier&rsquo;s day, the evening, the burden strip, two ways in', instruments()[:4]), ('INSTRUMENTS, CONTINUED', 'The sections, the map, its slot', instruments()[4:]), ('FIELD, CONTINUED', 'Branch lead, returned understanding, provenance, the balanced fallback', field_more()), ('FOCUS · THE PLACE PAGE', 'Identity, verdict, hours, trace, horizons, possibility, stub', focus()[:4]), ('FOCUS, CONTINUED · PATH', 'Possibility, stub, evidence, consequence', [focus()[4]] + path_live()[:2]), ('LIVE · SOCIAL', 'Posture, fallback, receipt, two people', path_live()[2:]), ('TAKEN, ADAPTED, LEFT OUT', '', omitted()), ('TOKENS', 'Colour, type, radius', tokens()), ('NOTES', '', notes)], 9000)
if __name__ == '__main__':
    import os; os.makedirs('out2', exist_ok=True); h = board(); open('out2/07 - Components.dc.html', 'w').write(h); print('wrote 07', len(h))
