"""07 · Components: every piece of the Places kit as used on 01 to 04, at phone width, with its name, where it comes from, and when it is used."""
from fix import *
import gen21, gen22
def cell(name, origin, html, use, w=393):
    return (f'<div style="width: {w}px; flex: none; display: flex; flex-direction: column; gap: 8px;">'
            f'<div style="display: flex; align-items: baseline; gap: 10px;"><span style="{MONO} font-size: 11px; font-weight: 700; letter-spacing: 1.1px; color: {INK};">{name}</span><span class="fn" style="color: {GOLDD};">{origin}</span></div>'
            f'<div style="width: {w}px; background: {PAPER}; border-radius: 12px; padding: 18px 0; box-sizing: border-box; {SANS} color: {INK};">{html}</div>'
            f'<div style="font-size: 12.5px; line-height: 17px; color: {MUTE};">{use}</div></div>')
G = lambda h: gut(h)
def strip(inner): return inner
def swatch(name, hexv, dark=False): return f'<div style="display: flex; flex-direction: column; gap: 6px; width: 84px;"><div style="height: 44px; border-radius: 10px; background: {hexv}; border: 1px solid rgba(27,23,20,0.10);"></div><span class="fn" style="color: {ANCHOR};">{name}</span><span class="fn" style="color: {GHOST};">{hexv}</span></div>'
def chrome():
    return [cell('anchor', 'kit · Home', anchor('NEW YORK', 'FRIDAY 5:40 PM') + orientation('The pier at sunset, with Maya. Saturday, 7:04.', 'Kept from her share · Sunset Park · the film on the lawn after'), 'Every field opens this way: a mono scope with the city&rsquo;s chevron, the time, the map; then the serif sentence that is the weekend and one muted line under it. Content before chrome.'),
            cell('anchor · back', 'kit · Home', anchor('MOVE DINNER?', 'SATURDAY', back=True, sub='With Maya and Alex') + G(f'<div style="margin-top: 18px;">{title("A page opened from the field", 20, 25, 600)}</div>'), 'A page opened from the field: the chevron back, the page&rsquo;s name as the scope, its one-line sub, the time and the map unchanged.'),
            cell('ask', 'Places', ask() + ask(q='Near Red Hook, Saturday') + ask(q='Saturday evening', ctx='Around dinner'), 'The question as a quiet hairline row, not a box: empty; with a question typed; with a question and a context. Chips are ink pills with a cross.'),
            cell('section · kick · tab bar', 'kit · Home', sect('Any day', 0) + G(kick('SATURDAY, IN THE LIGHT · KEPT WITH MAYA')) + f'<div style="margin-top: 18px;">{TABBAR}</div>', 'A section is sans 13 with a hairline; a kick inside a section is mono gold with a hairline. The tab bar is the app&rsquo;s, Places lit.')]
def rows():
    return [cell('row · serif', 'kit · Home', G('<div>' + prow('The noodle counter', 'HAND-PULLED · NO WAIT BEFORE 12:30 · CASH', first=True) + prow('The Harbor Print Room', 'TUE–SUN 11–6 · ROOMS REMADE, TO SUNDAY', unc(UNK_ROOM)) + prow('The waterfront loop', 'FIVE KILOMETRES, FLAT · SHADED AFTER 2', last=True) + '</div>'), 'The everyday row: a serif name, one mono fact line, a chevron; an unconfirmed line in muted sans when something is not known. No thumbnail.'),
            cell('row · numbered', 'Places', G(redhook_rows(True)), 'The pocket&rsquo;s places, numbered to match the map; the number is an ink disc with a mono numeral, never a person.'),
            cell('row · people', 'kit · Home', G('<div>' + arow('Priya · the greenmarket · ' + dim('the pigeons have a system · Saturday'), avatars=['P']) + arow('Sam · Canal Hall · ' + dim('sit on the left, that&rsquo;s where the speakers are'), avatars=['S'], last=True) + '</div>' + f'<div style="margin-top: 14px;">{people_row(["M", "A"], "Dinner with Maya and Alex", "Saturday 8:15 · the noodle counter · yours")}</div>'), 'A person as the subject: a solid ink disc with a white initial, the line in ink with the rest dimmed. The people row is the arrangement&rsquo;s strip: a facepile, the name, one line of state.'),
            cell('doors', 'kit · Home', G(door('The pier, with Maya') + doors(('Ask Maya and Alex about 8:45', GOLDD), ('Change the wording', MUTE)) + door_list(['Another neighborhood', 'Sunday, all day'])), 'A continuation is a text arrow at 13/500: gold for the primary, muted for the secondary; one per line, or a pair on one line where the second is the quiet alternative. Never a pill.')]
def human():
    return [cell('note · carded', 'canon · focus_human_note', G(card(author_row('M', 'Maya', 'THURSDAY · TO FRIENDS') + quote(MAYA_ROOM) + place_strip('The Harbor Print Room', 'RED HOOK · TUE–SUN 11–6') + door('Reply to Maya'))), 'A friend&rsquo;s contribution: the author row, her words in serif, the place it concerns as a strip, one door. The only card that carries a person&rsquo;s words.'),
            cell('note · bare · share row', 'Places', G(author_row('P', 'Priya', 'SATURDAY · TO FRIENDS') + quote(PRIYA_PIGEONS) + place_strip('The greenmarket', 'DOWNTOWN · SATURDAY 8–1')) + G('<div style="margin-top: 16px;">' + share_row('T', 'Theo', 'TUESDAY', THEO_BREAD, 'THE GREENMARKET · DOWNTOWN', last=True) + '</div>'), 'The same contribution on the paper when it is not the lead; and the From friends list row: disc, name, when, the words at 15, the place as a fact line.'),
            cell('readback', 'canon · execution_ledger', G(readback('SENT', 'Asked Maya and Alex about 8:45 · Friday 12:34 PM · no answer yet') + '<div style="height: 10px;"></div>' + readback('MOVED', 'Dinner · Saturday 8:45 · the noodle counter · Maya and Alex notified · 2:10 PM') + '<div style="height: 10px;"></div>' + readback('CHANGED · 5:40 PM', 'The noodle counter stops taking orders at 9 tonight', OX)), 'One line of state after an effect: the state as a mono label, the fact in sans. Sent is not arranged; notified appears only after the move; a change names its source.'),
            cell('composer · ask · answer', 'Places · Chat', G(composer('Reply', 'Saturday afternoon, then? I want the side room.', to='TO MAYA') + '<div style="height: 14px;"></div>' + bubble('is it ticketed? and can I get there by ferry on Saturday?') + '<div style="height: 10px;"></div>' + answer('Whether Rooms Remade is ticketed hasn&rsquo;t been confirmed; the workshop is open Tuesday to Sunday, 11 to 6.')), 'The composer says who receives it above the field. A private question to Vesper is an umber bubble; the answer is serif on the paper.')]
def cards():
    return [cell('card · prepared message', 'kit · Home', G(card(f'<div class="kickm">TO MAYA AND ALEX · NOT SENT</div><div style="{SERIF} font-size: 17px; line-height: 24px; color: {INK}; margin-top: 8px;">{gen21.MSG}</div>')), 'A message not yet sent: the recipients and the state as a kick, the words in serif. Home&rsquo;s card, with a shadow and no border.'),
            cell('sequence rail', 'canon · seq_strip', G(card(title('Saturday, in order', 20, 25, 600) + fn('KEPT WITH MAYA · FROM HER SHARE, TUESDAY', 4) + seq_strip([('7:04', 'The pier at sunset', 'The west pier faces it; it turns cold fast.', '9 MIN ON FOOT TO THE LAWN'), ('8:30', 'Playtime on the lawn by the pier', 'Tati&rsquo;s city of glass, free.', '')]))), 'A prepared possibility as a sequence: time, a node on a gold line, the name, one detail, the leg between. Order is the explanation. Not used on 01 since the arc took its place; kept for arrangements.'),
            cell('browse shelf', 'canon · field_browse_shelf', G(browse_shelf([('The noodle counter', 'Hand-pulled at the counter', 'CASH'), ('The lunch counter on Columbia Street', 'One plate a day · standing room', 'TILL 4')], 'ANY DAY · SIX PLACES')), 'The everyday six as pairs: a hatched photo slot, a sans name, one line, one mono chip. Photo or hatch, never a drawing.'),
            cell('photo slot · cover · ghost rows', 'canon', G(photo_plate(120) + '<div style="height: 12px;"></div>' + cover(None, 'READING · 6 MIN', 'The working waterfront that refused to close', 150) + '<div style="height: 12px;"></div>' + ghost_rows(2)), 'A photo slot is a hatched plate with its label. The editorial cover is the same slot with a gradient and the reading&rsquo;s kick and title. Ghost rows stand for results not yet back.')]
def instruments():
    return [cell('daylight arc · film bar', 'canon · instruments', G(kick('SATURDAY, IN THE LIGHT · KEPT WITH MAYA') + g.daylight_arc(True) + g.film_bar()), 'The day in the light: sunrise to sunset, the plan as the gold end of the arc, what comes after dark as a bar on its own row. Gold is the plan.'),
            cell('tide curve', 'canon · instruments', G(kick('THE PIER, EARLIER · LOW WATER') + g.tide_curve()), 'The harbor as a body of water: high and low as the curve, the plan on the low shore, sunset as the ink dot. Labels in the water or above the curve, never on it.'),
            cell('burden strip', 'canon · instruments', G(burden_strip()), 'Door to door: dots on foot, the crossing as one solid bar, one number. The strip under every map and on the place page.'),
            cell('day band', 'canon · instruments', G(gen21.band_evening(200, 'DINNER 8:45', [(214, 0, '', 'dot')], right='LAST ORDERS 9 · CAFÉ TILL 11')), 'The evening on one track: the hour as the gold block, dinner as the ring after it, a change as the ink dot; doors and closing times as the labels.'),
            cell('two thresholds', 'canon · path_difference_diagram', G(title('Two piers, two directions', 17, 22) + sup('Same evening light, opposite views.') + g.two_piers_diagram()), 'Two places compared on the axis that separates them, drawn side by side; each half carries its two mono facts.'),
            cell('cliff section', 'Places · 03', G(kick('WORTH KNOWING BEFORE YOU GO') + gen22.cliff_section()), 'A place explained by a section rather than a map: the town, the drop, the quay; the map distance against the ground.'),
            cell('map · fragment', 'Places · 01', G(REDHOOK_MAP), 'The one map: land and water, two streets, the pier&rsquo;s shape, a ferry glyph at the landing, gold-ringed numbers. Illustrative geometry, not routing. Its slot says so in one line when it is unavailable.'),
            cell('map · unavailable · pending', 'Places · 03', G(f'<div style="height: 72px; border-radius: 12px; background: {WASH}; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 3px; text-align: center; padding: 0 20px;"><div style="font-size: 14px; font-weight: 600; color: {INK};">The map isn&rsquo;t available right now</div><div style="font-size: 13px; color: {MUTE};">Everything here is still here</div></div>') + f'<div style="margin: 14px 22px 0 22px; height: 2px; border-radius: 1px; background: rgba(27,23,20,0.08); position: relative;"><div style="position: absolute; left: 0; top: 0; height: 2px; width: 38%; border-radius: 1px; background: {GOLDD};"></div></div>', 'The map&rsquo;s slot when the map fails: one line, in the slot, not a banner. The progress hairline under the question when results are pending: no percentage, no words.')]
def tokens():
    sw = '<div style="display: flex; gap: 12px; flex-wrap: wrap;">' + ''.join(swatch(n, v) for n, v in [('INK', INK), ('INK 2', INK2), ('MUTE', MUTE), ('ANCHOR', ANCHOR), ('GHOST', GHOST), ('GOLD', GOLD), ('GOLD DARK', GOLDD), ('UMBER', UMBER), ('OX', OX), ('WATER', WATER), ('CARD', CARD), ('WASH', WASH), ('PAPER', PAPER), ('BOARD', BOARD)]) + '</div>'
    ty = ('<div style="display: flex; flex-direction: column; gap: 10px;">' + f'<div style="{SERIF} font-weight: 600; font-size: 30px; line-height: 34px; letter-spacing: -0.01em;">Serif 30/34 · the orientation</div>' + title('Serif 20/25 · a page title', 20, 25, 600) + title('Serif 17/22 · a unit title', 17, 22) + title('Serif 16/21 · a row name', 16, 21)
          + f'<div style="font-size: 15px; line-height: 20px;">Sans 15/20 · a people row, a shelf name at 600</div><div style="font-size: 14px; line-height: 19px; color: {INK2};">Sans 14/19 · body</div><div style="font-size: 13px; line-height: 18px; color: {MUTE};">Sans 13/18 · supporting, unconfirmed</div><div style="font-size: 12.5px; line-height: 17px; color: {MUTE};">Sans 12.5/17 · the line under the orientation</div>'
          + f'<div style="{MONO} font-weight: 700; font-size: 11px; letter-spacing: 1.15px;">MONO 11 · THE ANCHOR, A READBACK LABEL</div><div class="fn" style="color: {ANCHOR};">MONO 10 · A FACT LINE, AN INSTRUMENT LABEL · THE FLOOR</div></div>')
    rad = '<div style="display: flex; gap: 14px; align-items: flex-end;">' + ''.join(f'<div style="display: flex; flex-direction: column; gap: 6px; align-items: center;"><div style="width: 64px; height: 44px; border-radius: {r}px; background: {CARD}; border: 1px solid rgba(27,23,20,0.14);"></div><span class="fn" style="color: {ANCHOR};">{l}</span></div>' for r, l in [(18, '18 · CARD'), (14, '14 · MAP'), (12, '12 · PLATE, SLOT'), (10, '10 · GHOST'), (999, '999 · DISC, CHIP')]) + '</div>'
    return [cell('colour', 'kit', G(sw), 'Ink for words and now; gold for the plan; umber for you and the private bubble; ox for a change; water for the harbor; card, wash, paper and board as the four grounds.', w=832),
            cell('type', 'kit', G(ty), 'Three voices: serif reads, sans operates, mono stamps. Ten pixels is the floor, inside instruments included.'),
            cell('radius', 'kit', G(rad), 'Five radii and nothing else declares a corner.')]
def board():
    notes = [notecol('How to read this sheet', [('WHAT IT IS', N('Every piece the seven boards use, rendered once at phone width from the same generator that draws them (docs/working/design-gen/places/kit3.py and the instruments in gen19v3.py). The origin beside each name says where the piece comes from: Home&rsquo;s kit, the a26e3228 canon&rsquo;s kinds and instruments, or Places itself.')), ('WHAT IT IS NOT', N('Not a design system and not a token rollout; nothing here is shared with Home, Chat or Life by being drawn here. The proposed Places-scoped tokens remain proposals in the response doc.')), ('RULES CARRIED', N('Photo or hatch, never a drawing. One instrument per unit, its labels off its lines, at the 10px mono floor. Serif names, mono facts. Solid discs for people, ink numerals for map places. Text arrow doors, one primary where the content calls for one. No design doctrine inside a phone.'))], w=760)]
    return rows_page(1900, '07 · COMPONENTS · 09-08', '07 · Components', 'Every piece of the Places kit as used on 01 to 04, at phone width: chrome, rows, human units, cards and kinds, instruments, tokens. Each with its name, its origin and when it is used.',
                     [('CHROME', 'The anchor, the sentence, the question, the sections', chrome()), ('ROWS AND DOORS', 'Serif rows, numbered rows, people, continuations', rows()), ('HUMAN UNITS', 'Notes, readbacks, the composer, the private question', human()), ('CARDS AND KINDS', 'The prepared message, the rail, the shelf, the slots', cards()), ('INSTRUMENTS', 'The arc, the tide, the burden strip, the day band, the thresholds, the section, the map', instruments()[:4]), ('INSTRUMENTS, CONTINUED', '', instruments()[4:]), ('TOKENS', 'Colour, type, radius', tokens()), ('NOTES', '', notes)], 7000)
if __name__ == '__main__':
    import os; os.makedirs('out2', exist_ok=True); h = board(); open('out2/07 - Components.dc.html', 'w').write(h); print('wrote 07', len(h))
